### ISSUE TITLE
Missing assembly in new NUnit Console 3.9.0?

### ISSUE THREAD

**Issue by jjvdgeer** [nunit/nunit-console#467] opened 2018-09-06 06:01 UTC
I installed the new NUnit Console 3.9.0 (the .msi) and when I gave it a testrun it failed with:

System.IO.FileNotFoundException: 'Could not load file or assembly 'nunit.engine.api, Version=3.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.'

Which is a pity because I had rather looked forward to getting rid of those failing builds due to a SocketException...

**Comment by jjvdgeer** [comment] 2018-09-06 06:06
I downloaded the zip file where this dll is provided. It seems copying it into the program folder resolves the problem.

**Comment by Hu3bl** [comment] 2018-09-06 06:10
Same issue here! Copying into the nunit console folder resolves the problem for me as well.

**Comment by rprouse** [comment] 2018-09-06 12:51
@jjvdgeer and @Hu3bl when you installed, did you do an upgrade, or did you do a fresh install? I tested the install last night and it worked fine. This morning on my work computer, I downloaded and did a fresh install and it works here too. As you can see from the screenshot below, `nunit.engine.api.dll` is included in my install and the date is correct for when I built it. I assume it was missing from yours when you installed, not corrupt or incorrect?

![image](https://user-images.githubusercontent.com/493828/45158395-d541ff00-b1b1-11e8-914e-b0f8c1deca75.png)

I've marked as confirm not because I am doubting your report, but because we need to get to the bottom of why it is happening to you and not me so I can fix it.

**Comment by rprouse** [comment] 2018-09-06 13:01
I've managed to reproduce by installing 3.8 then installing 3.9. When I do that, `nunit.engine.api.dll` and `nunit.engine.api.xml` are deleted. Our WiX install hasn't changed in ages, although we did move it back into the Console repository. Has anyone run into this sort of thing before?

I am going to check our WiX files for anything that might have changed in the move. If anyone has experience with WiX or MSIs and can help or offer advice, I'd appreciate it. I am going to keep a full backup of this release so hopefully I can repackage and re-release quickly once we figure this out.

**Workaround** - Uninstall previous versions of the NUnit Console before installing 3.9

**Comment by ChrisMaddock** [comment] 2018-09-06 13:16
@rprouse - I'd guess the issue is caused because nunit.engine.api.dll went out in NUnit Console 3.8.0 with file version 3.8.0.0 - where's as in NUnit Console has version 3.0.0.0. We have problems with wix installers before trying to 'downgrade assemblies' - it won't 'just happen' by default, I don't think. I imagine there's someway we can force it.

We had a problem with the api assembly version when moving to the new csproj - but maybe put in the wrong fix. 😞 (https://github.com/nunit/nunit-console/pull/419)

Sorry - afraid that's all I have time for now - might be able to put a bit more time into this toniht.

**Comment by rprouse** [comment] 2018-09-06 13:20
I've done a diff between the WiX files used to create the 3.8 install and the 3.9 install and there are only minor changes based on the source of the files when compiling the MSI. The component GUID hasn't changed and the changes for this component are the same as for all the others.

The code for this component looks like the others in https://github.com/nunit/nunit-console/blob/master/msi/nunit/engine-files.wxi

```xml
<Component Id="NUNIT.ENGINE.API" Location="local" Guid="6986F077-DF9F-4B4B-A3F5-5915A118AFC4">
    <File Id="nunit.engine.api.dll"
            ProcessorArchitecture="msil"
            Source="$(var.InstallImage)bin/nunit.engine.api.dll" />
    <File Id="nunit.engine.api.xml"
            Source="$(var.InstallImage)bin/nunit.engine.api.xml" />
</Component>
```

**Comment by jnm2** [comment] 2018-09-06 13:27
@rprouse Since the problem is that WiX won't overwrite a DLL with a newer file version by default, and as @ChrisMaddock points out, the file version is changing from 3.8.0.0 in the 3.8 release to 3.0.0.0 in the 3.9 release, maybe you need something like this? https://stackoverflow.com/a/32607186

**Comment by rprouse** [comment] 2018-09-06 13:38
I found this in the install log for that assembly,

```
MSI (c) (00:7C) [09:28:27:110]: Disallowing installation of component: {6986F077-DF9F-4B4B-A3F5-5915A118AFC4} since the same component with higher versioned keyfile exists
```

Related article, https://blogs.msdn.microsoft.com/astebner/2015/11/16/why-windows-installer-removes-files-during-a-major-upgrade-if-they-go-backwards-in-version-numbers/

I think this is because we switched from `AssemblyFileVersion` to `AssemblyInformationalVersion` for the Engine API in this PR, https://github.com/nunit/nunit-console/pull/447

**Comment by rprouse** [comment] 2018-09-06 13:41
@jnm2 you did that PR. Do you see any reason we couldn't just add `AssemblyFileVersion` back to the Engine API?

**Comment by jnm2** [comment] 2018-09-06 13:43
@rprouse Sure, whatever unblocks you. What happens if you use `[assembly: AssemblyVersion("3.9.0.0")]` though? That'll set the file version to `3.9.0.0` instead of `3.9.0` which IIRC is represented in Windows' file info as `3.9.0.-1`.

**Comment by jnm2** [comment] 2018-09-06 13:46
@rprouse I'm confused though. The problem is the component `{6986F077-DF9F-4B4B-A3F5-5915A118AFC4}` with the keyfile `3.0.0.0`, so how will adding back `AssemblyFileVersion` fix that problem?

**Comment by rprouse** [comment] 2018-09-06 14:14
@jnm2 we increment the file version for the API with each release and that kept it installing on each upgrade, but we leave the `AssemblyVersion` at 3.0.0.0 so that references to it continue to work despite the version. I think that removing the file version caused the version that the MSI sees to drop from 3.8 to 3.0.

**Comment by rprouse** [comment] 2018-09-06 14:16
@jnm2, here are the 3.8 and 3.9 files which shows the problem,

![image](https://user-images.githubusercontent.com/493828/45163238-ea248f80-b1bd-11e8-9676-f627337ea367.png)

**Comment by jnm2** [comment] 2018-09-06 14:17
@rprouse Oh, I see, you want the file version to be 3.9.0.0 while the assembly version is 3.0.0.0. That makes sense.

**Comment by rprouse** [comment] 2018-09-06 14:20
I will repackage and get an update to the MSI out today.

**Closed** 2018-09-06 23:53 UTC
Labels: is:build, pri:critical
