### ISSUE TITLE
Execution hangs when --timeout occurs in TearDown

### ISSUE THREAD

**Issue by simarust** [nunit/nunit-console#354] opened 2018-01-22 10:38 UTC
We discovered a misbehavior when running the NUnit Console Runner using the `--timeout` option.
If the timeout occurs in a TearDown method the execution hangs.

**Reproducer:**
(called with `--timeout=2000`)

```
[TestFixture]
public class TimeoutTestsWithSetUpAndTearDown
{
    [SetUp]
    public void SetUp()
    {
        Thread.Sleep(1000);
    }

    [TearDown]
    public void TearDown()
    {
        Thread.Sleep(1000);
    }

    [Test]
    public void ShortTest()
    {
        Thread.Sleep(500);
        Assert.Pass();
    }
}
```

**Comment by CharliePoole** [comment] 2018-01-22 22:42
This appears to be a duplicate of nunit/nunit#352, which has been around for years, but I never thought about this implication of it.

Briefly, we cancel the thread to implement timeout. If teardown is being executed, that means we are in a under the control of a `finally` block, which leads to a hang when we try to cancel the thread. We need to either fix nunit/nunit#352 and see if it fixes this one or somehow avoid trying to cancel if TearDown is in process.

**Comment by ChrisMaddock** [comment] 2018-07-08 11:56
Looks like https://github.com/nunit/nunit/issues/352 has just been fixed.

@jnm2 - you've been closer to that issue than I have - this case is covered, correct?

**Comment by jnm2** [comment] 2018-07-08 13:36
@ChrisMaddock Yes, this is the same issue.

**Comment by ChrisMaddock** [comment] 2018-07-08 17:40
For the records - I've not put this in the 3.9 milestone, as there was no change in the console/engine.

**Closed** 2018-07-08 17:40 UTC
Labels: is:bug, pri:normal
