### ISSUE TITLE
Explicit & Category Handling has Changed from 3.6.1 to 3.8

### ISSUE THREAD

**Issue by JPVenson** [nunit/nunit-console#423] opened 2018-05-24 12:50 UTC
Hey,

Today i observed a change in handling Explicit tests:

Assume test Method:

```
[Test]
[Category("Any")]
[Explicit]
public void Test(){
    Assert.Fail()
}
```

Using console runner command line:

`nunit3-console.exe --skipnontestassemblies --shadowcopy --labels=ALL --where "cat == Any" "Test.sln" --agents=1 --domain=Single --result=nunit.results.xml`

Result:
Nunit 3.6.1: The Test does not run and therefore do not fail
Nunit 3.8: The Test will be executed and will fail.

**Comment by rprouse** [comment] 2018-06-05 15:34
I am going to close this as a duplicate of #134. There is much discussion of how Explicit tests should be run. In your example the way it is working in 3.8 is how we designed it. If a test is included in a filter, it is considered to be explicitly run. See #134 for ideas on making selecting explicit tests more explicit and please weigh in with your ideas.

**Closed by rprouse** 2018-06-05 15:34 UTC
