### ISSUE TITLE
3.9 release date

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit-console#390] opened 2018-03-23 12:28 UTC
Opening so users have an issue to follow for updates as we zero in on a potential release date for
https://github.com/nunit/nunit-console/milestone/7.

We've had feedback that nunit/nunit-console#372 is helping, but some users have policies which don't allow the deployment of prerelease assemblies. In the meantime, others are still [running into the issue](https://github.com/nunit/nunit-console/issues/225#issuecomment-375648682) which is present in 3.8.

[Edit: Nice issue number.]

**Comment by ChrisMaddock** [comment] 2018-03-25 12:57
I've added a couple of regressions to the 3.9 milestone that it would be good to investigate first.

I agree we should do a new release fairly promptly - @BlythMeister's fix is significant for a number of users. 🙂

**Comment by MJLHThomassen-Eurocom** [comment] 2018-05-01 08:17
Any updates on this? I'm also running into #370 alot. What is the current "workaround" if any untill release?

**Comment by ChrisMaddock** [comment] 2018-05-01 08:28
@MJLHThomassen-Eurocom - you may be better to instead reference the latest build of master from our MyGet feed - see the README for details

**Comment by BlythMeister** [comment] 2018-05-01 08:46
My current workaround is to look at the NUnit result XML if i get a -5 and only fail my build if there is a failure recorded in the XML.

But it's not a perfect situation!

**Comment by MJLHThomassen-Eurocom** [comment] 2018-05-01 08:51
@ChrisMaddock 

I just tried this, however I'm also using the nunit-extension-vs-project-loader, installed via chocolately, and for some reason v3.9.0 installed from myget does not discover the extension properly and thus i cant test my current setup (since i point my console runner to the .sln file). I could try to run individual assemblies.

@BlythMeister Thanks for the suggestion!

**Comment by ChrisMaddock** [comment] 2018-05-01 10:51
@MJLHThomassen-Eurocom That shouldn't be the case. Could you open a new issue describing exactly which packages you're installing from where?

**Comment by dzmitry-lahoda** [comment] 2018-05-21 09:52
Waiting for this release. I our case, as I know, #370  fails our gated checking .

**Comment by rprouse** [comment] 2018-05-22 19:28
@dzmitry-lahoda our milestone for the 3.9 release is out in the fall. We might move that up to summer, but until then, can you use one of our MyGet builds?

**Comment by ChrisMaddock** [comment] 2018-08-09 13:49
@rprouse - What's your latest thinking on this release? It would be good to get #372 out in the wild.

Personally, I'd like to fix everything in the 3.9 milestone before a release, but I don't have the time for that at the moment, and it seems unlikely to happen! I'd be keen to tie up #436, given that's close to being finalised - otherwise, I think the rest could be pushed out. The remainder are bugs in 3.8 - it's unfortunate they'll stay for 3.9, but we can't do everything. 😞

**Comment by rprouse** [comment] 2018-08-09 14:52
@ChrisMaddock what is your timing for #436? I should have time this weekend or next weekend. I'm away on vacation at the end of the month, so if we don't get it out soon, it will be September...

**Comment by ChrisMaddock** [comment] 2018-08-09 15:30
Won't be able to look this weekend, possibly next weekend.

Might be better to go ahead without it? It's not a 'new' issue.

**Comment by ChrisMaddock** [comment] 2018-08-11 12:01
Managed to get back to #436 - hopefully we can get that in. 🙂

**Comment by rprouse** [comment] 2018-08-16 01:31
Good to know @ChrisMaddock. I'm going through and doing some cleanup in preparation for a release now. It looks like #435 is merged so we are good to go 😄

**Comment by rprouse** [comment] 2018-08-23 00:49
@nunit/engine-team I am going to hold off on the 3.9 release until I get back from vacation at the beginning of September. I could get the release out now, but if there are any problems with the release, I won't be available next week to deal with them. I'm back Sept 3rd and will do the release soon after that.

**Comment by jnm2** [comment] 2018-08-25 14:13
@rprouse Is there a realistic shot at getting at least the .NET Framework replacement of Mono.Cecil in 3.9 since it's so close (https://github.com/nunit/nunit-console/pull/462)? I apologize for how the timing turned out.
One thought I had since #462 reimplements assembly reading which is so fundamental to the engine: what if we fly it as a 3.9 prerelease in the NuGet.org feed and push off the 3.9 release until we have some verification from users, or else start a 3.10 beta soon after releasing 3.9?

**Comment by rprouse** [comment] 2018-08-25 15:44
@jnm2, that isn't much runway for such a big change. I also have a big PR out merging the .NET Standard engine back into the main projects using multi-targeting. We're going to conflict, but feel free to move forward with your work, I will deal with it on my end 😄

**Comment by BlythMeister** [comment] 2018-08-25 15:45
Seems risky to add big changes in...this release has a large show stopping bug fix that people are crying out for

**Comment by mikkelbu** [comment] 2018-08-26 17:51
I think a beta will be a good idea, especially if it contains the large changes mentioned about. Then we just need to do some "advertising" for it on Twitter, Gitter etc. and hopefully we will get som more people testing it.

**Comment by jrodrigv** [comment] 2018-09-03 09:05
Hi all,

Is there any expected date for this release? 

Kind Regards

**Comment by ChrisMaddock** [comment] 2018-09-03 09:07
Hi @jrodrigv - see @rprouse's comment above.

> I'm back Sept 3rd and will do the release soon after that.

**Comment by rprouse** [comment] 2018-09-05 01:28
As an FYI, I am currently cleaning up issues and getting ready to do the release. I am aiming for tomorrow  (Sep 5) if all goes well.

**Closed** 2018-09-06 23:53 UTC
