### ISSUE TITLE
Socket Exception when stopping Remote Agent

### ISSUE THREAD

**Issue by eberlid** [nunit/nunit-console#171] opened 2017-02-04 11:23 UTC
This problem exists using NUnit 3.6.

The TCP channel may throw a Socket Exception (0x80004005) when calling `Stop` on the Agent. We cannot reproduce the problem deterministically, but we are able run tests so that the exception occurs with a high probability.

Our test toolchain consists of a python script which calls the `nunit3-console.exe` (I'll provide more information about the test setup on request). The problem exists _rarely_ when calling the console runner from python with these arguments
`nunit3-console.exe myTestAssembl.dll --work=[pathToWorkDir] --where=Category==Default`
The likelihood that the problem occurs can be _increased_ by creating Threads in Python which will call the console runners with different work directories for each Thread Runner in parallel. However, adding `--trace=Debug` reduces the likelihood that the problem occurs (also logging process activity with procmon reduces the frequency the problem occurs).

Inspecting log results and procmon logs yields that the Agent receives the `Stop` call and sets its `stopSignal`. Once the `stopSignal` is signaled, the Agent terminates successfully. However, the `ProcessRunner` ends up in exception state because the underlying TCP channel to the Agent throws a Socket Exception with error Code 0x80004005.

AFAIK the Process Runner wants to be sure that Agent Process still exists, i.e., it has not terminated due to some unexpected error, and therefore catches all exceptions when calling `Stop`. I changed the behavior in a way that the Process Runner 'pings' the Agent first to make sure the process is still alive (and by catching all exceptions) and then stopping the Agent (and ignoring SocketException). See this change in this commit: https://github.com/eberlid/nunit-console/commit/82685137f9363ffffedf218b94fa212f280e2b4b

(Please let me know if there is a more appropriate way to share this commit with you, rather than just copy paste the URL in here).

With this patch, the problem did not occur so far.

**Comment by CharliePoole** [comment] 2017-02-04 17:30
Best thing to do is to create a pull request, which allows us to comment more readily, even line-by-line.

It's interesting to think about multiple copies of the console runner executing. I would think that might cause a problem, since there would be multiple TestAgency servers set up. I'll have to look at the code to remind myself how their URIs are assigned. Normally, the engine assumes it is handling all the parallelism, not that it is done from outside.

We'll be happy to look at your PR in more detail. THanks for your work.

**Comment by BlythMeister** [comment] 2017-03-29 10:23
I have noticed also seeing this exception on occasion using 3.6 which we did not see using 3.5.
We have the exact same setup as the reporter with multiple instances of nunit console being called from threads in our FAKE build script.
I've seen other reports of the "--explore" command being used, we are not using this command

**Comment by jnm2** [comment] 2017-05-29 22:22
We believe this was fixed by https://github.com/nunit/nunit-console/pull/223 which will be released as part of 3.7. If you'd like to confirm sooner that the issue is fixed, please try `3.7.0-dev-03641` from the `https://ci.appveyor.com/nuget/nunit-console` NuGet feed.

If it turns out that this does not fix your issue, please reopen and comment.

**Closed** 2017-05-29 22:22 UTC
Labels: is:bug, pri:high

**Comment by demonix** [comment] 2017-06-02 04:50
Hi!
We've tried 3.7.0-dev-03644 and it still crash with Socket Exception (0x80004005) under teamcity. Stack trace is the same as before update (v 3.6.1)
