### ISSUE TITLE
nunit3-console.exe (3.7.0) returns -1 even though tests all succeeded

### ISSUE THREAD

**Issue by frankshearar** [nunit/nunit-console#315] opened 2017-11-20 21:54 UTC
The below contains a typical example of the error. ConsoleRunner.INVALID_ARG is returned even though the tests ran (presumably because the arguments are valid!) and all passed..

[jenkins] $ cmd.exe /C " "C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe" /nr:false /t:test /p:environment=inmemory,category="(cat == Service or cat == Integration) and cat != Flakey and cat != EndToEnd and cat != ETW" /v:m build.targets " && exit %%ERRORLEVEL%%
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

  NUnit Console Runner 3.7.0 
  Copyright (c) 2017 Charlie Poole, Rob Prouse
  
  Runtime Environment
     OS Version: Microsoft Windows NT 10.0.14393.0
    CLR Version: 4.0.30319.42000
  
  Test Files
      <the various test assemblies>
  
  Test Filters
      Where: (cat == Service or cat == Integration) and cat != Flakey and cat != EndToEnd and cat != ETW

((test output))

  Run Settings
      DomainUsage: Single
      DisposeRunners: True
      WorkDirectory: d:\jenkins\workspace\some\path
      ImageRuntimeVersion: 4.0.30319
      ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
      ImageRequiresX86: False
      ImageRequiresDefaultAppDomainAssemblyResolver: False
      NumberOfTestWorkers: 24
  
  Test Run Summary
    Overall result: Warning
    Test Count: 1184, Passed: 1162, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 22
      Skipped Tests - Ignored: 22, Explicit: 0, Other: 0
    Start time: 2017-11-20 18:15:05Z
      End time: 2017-11-20 18:19:12Z
      Duration: 246.944 seconds
  
  Results (nunit2) saved as TestResults.xml
d:\jenkins\workspace\tni.critical.test.integration-build.from.artefact-nunit3\build.targets(153,5): error MSB3073: The command "C:\Users\scauto1\.nuget\packages\NUnit.ConsoleRunner\3.7.0\tools\nunit3-console.exe ((test assemblies)) --domain=Single  --labels=On --where "(cat == Service or cat == Integration) and cat != Flakey and cat != EndToEnd and cat != ETW"  --result=TestResults.xml;format=nunit2" exited with code -1.
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure

**Comment by CharliePoole** [comment] 2017-11-20 22:08
Your command-lines contain no test assembly and none is listed under Test Files in your output. Somehow tests appear to run. Can you clarify?

**Comment by frankshearar** [comment] 2017-11-20 22:14
I elided sensitive bits out of the logs. Oh dang it, I had put something that GitHub must have interpreted as an HTML tag, and removed. I'll try edit the post.

**Comment by frankshearar** [comment] 2017-11-20 22:18
I took a look at ConsoleRunner's source, and this looked like it MIGHT let tests run and still return INVALID_ARGS? https://github.com/nunit/nunit-console/blob/416b54d2a215466a861b3fbea82adeb3c820ec62/src/NUnitConsole/nunit3-console/Program.cs#L116-L124

**Comment by CharliePoole** [comment] 2017-11-20 22:25
That does look suspicious.

**Comment by frankshearar** [comment] 2017-11-21 01:04
It happens on other --where options, like "cat != External and cat != EndToEnd and cat != Flakey". To be honest, I strongly suspect something Weird happening in the tests, or the test builder, or something like that. We have several different build definitions running where we never see this, and a few that have (recently!) started always dying like this.

**Comment by frankshearar** [comment] 2017-11-22 17:56
I can confirm that it's not the --where argument that's causing the issue.

I have an abstract generic class of T, and three [TestFixture] subclasses with different Ts. If I [Ignore] the three TestFixtures, nunit3-console.exe correctly returns 0. If I remove the [Ignore] from even one of the fixtures, it returns -1. I don't yet know exactly why.

**Comment by CharliePoole** [comment] 2017-11-24 14:37
Can you provide a minimal example?

**Comment by kditrj2d** [comment] 2018-07-27 12:54
I notice that the original poster never returned to this...

I too am seeing the runner return -1 (INVALID_ARG), despite all of the tests appearing to be executed.  (I have quite a few tests marked to be ignored and a couple that are currently inconclusive).

I am using the console runner from version 3.7.0.  Here is the command-line.  I have put new-lines in between each parameter to make it read easier here.  The fixture list consists of 37 (space-delimited) items:

nunit3-console.exe
fixture-list
--work=C:\Temp\OutputFiles
--noheader
--framework=net-4.0
--process:Multiple
--result=C:\Temp\NunitOutput.xml
--agents=4
--where !(cat==Developmentt||cat==Integration||cat==RabbitMQInstalled)

I see this output from the end of the run, but the runner returns -1:

Run Settings
    ProcessModel: Multiple
    RuntimeFramework: net-4.0
    DisposeRunners: True
    WorkDirectory: C:\Temp\OutputFiles
    MaxAgents: 4
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Warning
  Test Count: 20542, Passed: 20464, Failed: 0, Warnings: 0, Inconclusive: 2, Skipped: 76
    Skipped Tests - Ignored: 76, Explicit: 0, Other: 0
  Start time: 2018-07-27 11:05:01Z
    End time: 2018-07-27 11:13:58Z
    Duration: 537.907 seconds

Results (nunit3) saved as C:\Temp\NUnitResults.xml

I have tried with 3.8.0 to the same result.  (I reverted to 3.7.0 because I read about an issue with the 3.8.0 runner returning -5 when app domains are not being properly released and I thought that this might be causing the non-zero return value, but having reverted and found the same behaviour I got MSBuild to output the return value and it is -1 not -5.)

Did you ever manage to reproduce this behaviour?  If so, is there a fix yet?

**Comment by frankshearar** [comment] 2018-07-27 17:30
I never had the time to try for a minimum repro, sadly. The suite of tests is massive, and we did a bunch of funky things, so I always thought that perhaps it was our fault. Except for the fact that I could not understand how we'd see an INVALID_ARG...

**Comment by CharliePoole** [comment] 2018-07-27 18:14
I doubt that it's your fault. More likely, your test brings out a corner case that NUnit doesn't deal with.

**Comment by mikkelbu** [comment] 2018-07-30 12:07
@frankshearar Do any of your tests output "Error:" or "Warning:"? Since apparently msbuild interprets these these string in a special manner, see e.g. last 3-5 comments in #444 for more info.

**Comment by frankshearar** [comment] 2018-07-30 18:33
Yep, a WHOLE PILE do.

**Comment by CharliePoole** [comment] 2022-01-13 09:55
This issue has had no further commentary for quite a while. I'm closing it but we'll continue to monitor it for any added information.

**Closed by CharliePoole** 2022-01-13 09:55 UTC
Labels: Needs Confirmation
