### ISSUE TITLE
--where filters consider assembly path on disk as part of match when filtering by 'test'

### ISSUE THREAD

**Issue by sectoreleven** [nunit/nunit-console#1030] opened 2021-11-05 15:02 UTC
When using the --where command-line option of the console runner with a 'test' filter, the path of the assembly on disk is being used as part of the match. We are using NUnit Console 3.11.1.

In our use case, we have a series of tests where the test classes all include the word 'Next' in their name. We had been using a `--where 'test=~Next'` filter at the command line to select just these tests for a specific run. (Due to other contraints, we are unable to separate these tests out to a separate assembly at this time.)

Everything works fine until we place the assembly under test into a folder on disk that also contains the string 'Next' as part of the path; when that is the case, all tests in the assembly are run.

We have already updated our test paradigm to use a different folder name, and have changed our filter to `class=~Next`, so this may be more a documentation/design question. The [Test Selection Language](https://docs.nunit.org/articles/nunit/running-tests/Test-Selection-Language.html ) page of the NUnit docs state that the `test` key word uses the "fully qualified test name as assigned by NUnit", but is this behavior of including the disk path by design?

**Comment by CharliePoole** [comment] 2021-11-05 15:35
This is somewhat speculative and will need to be checked but I believe your expression is selecting the "test" represented by the assembly itself... i.e. the suite containing all other tests in the assembly.

As you may know, NUnit uses the word "test" somewhat generally. It may represent a method, a single test case with parameters, a class, a namespace or even an assembly. However, since `where` filters are intended to apply __within__ an assembly, we should probably exclude this match.

Again... investigation is needed, but most likely this is an issue with the nunit framework rather than the console or engine, which merely pass the filter onward.

**Comment by CharliePoole** [comment] 2022-01-13 09:17
I'm unable to reproduce this using the latest console and framework, so I'm closing. Comments are still accepted here if you can come up with a test case for the current versions.

**Closed by CharliePoole** 2022-01-13 09:17 UTC
Labels: Needs Confirmation
