### ISSUE TITLE
Nunit-Console 3.10 inTeamCity

### ISSUE THREAD

**Issue by elinato** [nunit/nunit-console#593] opened 2019-03-25 07:49 UTC
After updaing to nunit-console 3.10 in TeamCity I get this error: 

`Step 13/16: Run tests (NUnit)
[08:30:20]	[Step 13/16] NUnit console tool was not found. Check path to NUnit console tool build step setting.
Current value: "C:\BuildAgent\tools\NUnit.Console.3.10.0", used full path: "C:\BuildAgent\tools\NUnit.Console.3.10.0"
Looking for NUnit console tool in the directory "C:\BuildAgent\tools\NUnit.Console.3.10.0"
The directory "C:\BuildAgent\tools\NUnit.Console.3.10.0" does not contain the NUnit console tool
[08:30:22]	[Step 13/16] Error message is logged
[08:30:22]	[Step 13/16] NUnit console tool was not found. Check path to NUnit console tool build step setting.
Current value: "C:\BuildAgent\tools\NUnit.Console.3.10.0", used full path: "C:\BuildAgent\tools\NUnit.Console.3.10.0"
Looking for NUnit console tool in the directory "C:\BuildAgent\tools\NUnit.Console.3.10.0"
The directory "C:\BuildAgent\tools\NUnit.Console.3.10.0" does not contain the NUnit console tool
[08:30:20]	[Step 13/16] Step Run tests (NUnit) failed with unexpected error`

I installed nunit-console from TeamCity Tools

**Comment by ChrisMaddock** [comment] 2019-03-25 08:58
TeamCity is a closed-source tool, so there's not a lot we can do to help I'm afraid. I suspect that it might be using the zip file, which has been repackaged slightly to allow the .NET Standard engine to be packaged as well.

@NikolayPianikov - can you advise at all?

**Comment by NikolayPianikov** [comment] 2019-03-25 13:35
`NUnit.Console-3.10.0.zip` contains a different file structure in the comparison of previous versions. Thus TeamCity cannot find an executable to run tests.

**Comment by NikolayPianikov** [comment] 2019-03-25 13:38
@elinato you could use a previous version of the NUnit console as workaround.

**Comment by rprouse** [comment] 2019-03-26 00:14
Thanks @NikolayPianikov. Did you enter a TeamCity bug? Why doesn't TeamCity just use the NuGet packages?

I am going to close this on our end. Feel free to keep commenting.

**Closed by rprouse** 2019-03-26 00:14 UTC
Labels: confirm

**Comment by NikolayPianikov** [comment] 2019-03-26 13:18
@rprouse we are using github API to get links to files like `nunit.console.x.x.x.zip` from the TeamCity `tools` UI. We does not make any other actions in TeamCity to prepare this zip files to avoid negative impact caused by our changes. We just unpack them on a TeamCity agent side and run test using `nunit3-console.exe` fro the root folder of this archives. We are not using nuget packages because we do not want to rely on logic of resolving dependencies to make executable pack including all required extensions.

Also it would be great to update `NUnit.Extension.TeamCityEventListener` to `1.0.6` in the zip file. When an user install `NUnit.Console` via nuget it will run test with  version `1.0.6` of NUnit.Extension.TeamCityEventListener, but if he download the zip file he will use `1.0.4`

**Comment by NikolayPianikov** [comment] 2019-03-26 13:27
I've created [this issue](https://youtrack.jetbrains.com/issue/TW-59741) in our issue tracker. But users should update TeamCity to newest version with fixes in the future to use 3.10 and it is sad.

**Comment by CharliePoole** [comment] 2019-03-26 15:27
@NikolayPianikov @rprouse 
Correct me if I'm wrong, but my memory of how we planned for this updating to work was...

1. @NikolayPianikov would do releases of the extension whenever he wanted.
2. When he felt it was appropriate, he would file an issue to have the NUnit packaging contain some new release, possibly including a PR.
3. The NUnit project team would review that and decide whether to merge the new version into the NUnit packaging.
4. Once merged, it would be available in all dev builds and production releases after that point.

If NUnit is including 1.0.4 while the extension is up to 1.0.6, then something probably didn't work as planned. :smile: 

IMO this is how any independent extension ought to work.

**Comment by NikolayPianikov** [comment] 2019-03-26 19:01
@CharliePoole yes you are right. Actually our QA did not have enough time (few days) to check latest changes in 1.0.6 and it is important question, but it is not so visible for users.
The very important question is about incompatibility between TeamCity and latest NUnit zip file. Unfortunately now users cannot use 3.10 there. I've already made a fix where TeamCity 2018/2019 can find the executable file by the path `bin\net35` but there is a significant time gap when users will update their TeamCity.
If there was a way somehow to return a compatibility by composing zip file again we could update our extension too :)

**Comment by CharliePoole** [comment] 2019-03-26 19:31
As you may know, I don't work on the console / engine team any longer so it would be up to someone else to give you an answer. Even so, because I was involved in the beginning, I feel I should make a comment.

In the beginning of NUnit 3, we recommended to JetBrains that they use the new engine API, which we intended to keep stable. JetBrains was suspicious of this because we all know such promises are not always kept. In fact, however, that API has remained stable through 10 releases.

Strangely (at least to me) JetBrains instead chose to rely on special messages, which NUnit does not directly support. Now we learn for the first time that they rely on a specific file layout, which isn't part of any public API.

If you can't trust us to do what we say we will do, then why would you rely on things about which we have said nothing?

Of course, the question is rhetorical. I realize that you personally have not made these decisions. It really does seem, however, that the company is willing to suffer a lot of inconvenience in order to avoid open communication about what they are doing and what they need.

As I said, I am no longer involved in this and have no influence on the outcome. That's why I feel free to speak so frankly.

**Comment by ChrisMaddock** [comment] 2019-03-27 08:24
> Also it would be great to update NUnit.Extension.TeamCityEventListener to 1.0.6 in the zip file. When an user install NUnit.Console via nuget it will run test with version 1.0.6 of NUnit.Extension.TeamCityEventListener, but if he download the zip file he will use 1.0.4

There's two different workflows here:

**msi/zip**

Both these packages should automatically pull in the latest version of each extension. The fact this hasn't happened here looks like a bug, I guess due to some stale state. I'll file an issue now.

**NuGet packages**
Currently extension versions here require updating by hand. I agree that it should be for the extension maintainer to file a PR/issue to do that - apologies if it wasn't clear before Nikolay. We could potentially change these to be auto-updating in future...PRs welcome! 😉

**Comment by ChrisMaddock** [comment] 2019-03-27 08:29
With the zip structure, I thought this might happen with 3.10. Unfortunately, I'm not sure what better solution there is. The console is developing, and now packaged for multiple different platforms and our old zip structure had no way to contain that. The alternative was that we could have created multiple zips, but that would require renaming the zip, and no doubt would have broken TeamCity's process too.

> We are not using nuget packages because we do not want to rely on logic of resolving dependencies to make executable pack including all required extensions.

This is an interesting comment! To me, TeamCity relying on the NuGet package instead seems the most future-proof way of managing this. This way, both NUnit and TC can expect/create packaging to a defined spec. I'm not sure we possibly can guarantee the same, with the zip file.

**Comment by CharliePoole** [comment] 2019-03-27 08:48
@ChrisMaddock Why would you want to automatically distribute something without testing it? When @NikolayPianikov releases a new version, it's his job to ensure it works with all past versions of the engine (unless he sets a min version on the extension). It would seem that nunit shouldn't incorporate the extension in a package without some testing as well.

When we talked about my separately handling some extensions, that was my assumption too. It's possible for an extension to break the engine in various ways even for a user who doesn't make use of that extension.

**Comment by NikolayPianikov** [comment] 2019-03-27 09:18
@ChrisMaddock I am not sure I understand what do you mean referencing on a new engine API? 

As I remember originally the TeamCity extension was created before the time when TeamCity makes a decision to support real time integration with NUnit. Before it TeamCity was downloading tests result from xml files at a build finish. 

Each TeamCity extension was checked by integration tests. Also I was testing them manually for basic scenarios. Any TeamCity extension (including beta versions) will be not published to Nuget without these tests. But specifically for version 1.0.6 I would like this extension should be tested additionally.

**Comment by NikolayPianikov** [comment] 2019-03-27 09:52
@ChrisMaddock yes I understand your points about the zip structure and file names. As I mentioned above I've already made fixes in TeamCity 2018/2019. For current installations it would be a problem, so we could solve this issue for instance by using alternative zip files only for all .net frameworks, excluding net20. Also it could be done only for some limited period of time.

Regarding the `an interesting comment!'. There are several points:
- the restoring of NuGet packages under quite significant set of operation systems is not simple task, also it would be a cause of undesirable dependencies
- TeamCity should work without internet. In this case user could download a released zip file from github and upload it manually. It is not so easy to do manually for a nuget package with a set of dependencies

**Comment by CharliePoole** [comment] 2019-03-27 11:55
@NikolayPianikov When you and I had a meeting with someone else (a manager?) from JetBrains, I discussed the possibility of using the Engine API directly, without the intermediary step of creating special messages. That JB guy told me that the decision was made because our API had changed in the past. As I told him, we __never had an API__ before NUnit 3.0. That's what I mean by the "new" API. Because of past problems, we promised users we would keep the API constant, only adding to it and not changing anything. That has remained true.

The TC extension was first written for a very simple purpose: to provide progress info while the test ran. Initially, you still got the final results from the XML. At some point, it was decided to get all the info from the extension, which became very complex as a result. That is why we were having that particular meeting. I felt that it was too complex for us to maintain, especially since JB reveals almost no information about what it needs to have done. As a result, you took it over. As it stands, you are pretty much the only one who has a high level of understanding about both the teamcity extension and NUnit itself. That's why changes get made, like the zip file structure, which could impact you negatively.

Regarding testing... yes, you test very thoroughly. IMO, better than the NUnit team WRT your extension. But you don't (can't) test against releases that have not yet come out. Any change to what is packaged automatically will be when a new engine release is made. By definition, you will not have tested that release, rather only the prior one. So somebody ought to test it! An automatic process that included testing would be OK but not one that just picks up the latest release without any check. At least that's my view. The testing would not be hard and in fact could be the same tests you already run.
