### ISSUE TITLE
Missing output with failed test stack traces for Assert.Multiple

### ISSUE THREAD

**Issue by gps7** [nunit/nunit-console#1192] opened 2022-06-28 10:58 UTC
Hi,
I am missing test output with stack traces for failed tests. For running example test fails but output not showing any information about failures nor even mention that test has failed:

[Test]
public void AssertMultiple()
{
	Assert.Multiple(() =>
	{
		ValidateInteger();
		Assert.That("a", Is.EqualTo("b"), "String");
		ValidateInteger();
	});
}

private void ValidateInteger() => Assert.That(1, Is.EqualTo(2), "Integer");
Running Nunit console with fallowing command line provides empty TEST_OUTPUT.log file:
"nunit3-console.exe" MyTests.dll --test=MyTests.TestClass.AssertMultiple --out=TEST_OUTPUT.log

I've tried to run v3.15.0. I assume this also affects the Test Centric since it shows failing test but output is always empty. I've expect to see not only failures but also 3 stack traces for 3 failures.

List of affected applications:
- Nunit-console
- [Adapter @ Visual Studio](https://user-images.githubusercontent.com/439844/175824288-7387a863-06bd-41c9-966f-d418b51f49f8.png)
- [TestCentric](https://user-images.githubusercontent.com/21167960/176107084-f1899f00-4591-469d-9b53-c12273a8bbf2.PNG)

I am using Framework 4.8.

This is a fallow up issue after creating issue [#4129 ](https://github.com/nunit/nunit/issues/4129)at Nunit. Please refer to this item for more details if needed.

**Comment by gps7** [comment] 2022-06-29 05:47
Thanks for clearing the idea, then still question for me how I can easily combine output file with test results (with stack traces) into single file? 
With regards console output I can see full stack traces shown correctly in the console view as well as in the XML result file but still missing this information in the TestCentric as well as in Adapter used by Visual Studio by Test Explorer.

**Comment by CharliePoole** [comment] 2022-06-29 13:13
@gps7 When using the console app from the command line, you can redirect the output with `> FILENAME`, if you are using windows. Isn't that what you are looking for? If not, please be more specific. I'll be happy to reopen this if you come up with some new functionality, which would be useful to all users.

NOTE: Use your own OS's command sequences if you aren't on windows. It's always a good idea say what OS you are using when posting an issue about an application, which runs under multiple operating systems.:-)

With respect to the other runners (TestCentric GUI and NUnit3 VS Adapter), this is the console runner project. As explained in more depth in the comments I linked above, their code and functionality is different. They each receive all the same information from the framework but of course may display it differently. That's what runners do!

My suggestion: make sure you are happy with this issue (the console) being closed and then see if you want to ask for new functionality from either of the other two runners, using their individual issue reporting.

**Comment by CharliePoole** [comment] 2022-06-30 12:55
Yes, the result file has two kinds of error results provided. The `<assertion>` elements contain the newer format, which was added to support multiple assertions and warnings. The message shown under the `<failure>` element was kept for compatibility with older runners, which don't understand the `<assertion>` elements. It is also used when converting from nunit3 to nunit2 format.

The nunit3-console runner understands and uses the new format. When you run it directly from the command-line on your own machine or a server, it displays each error separately, with its own stack trace. If you had a case where running `nunit3-console.exe` __directly__ did not show them separately, that would be a bug.

You suggest that the older format (in `<failure>` element) should be modified to have separate stack traces. That would be a change in the framework, where the XML originates. The engine only adds a `<test-run>` element to wrap all the assemblies. But that isn't possible in any case because this info is provided for backward compatibility and your change would make it incompatible. Older runners expect __one__ message and __one__ stacktrace inside the `<failure>` element.

I can see that your server display uses the old format. Can you explain where that display comes from?

**Comment by gps7** [comment] 2022-06-30 15:52
Sorry @CharliePoole , I am reading emails but I have no idea on which github source Nunit framework and Adapter is located. I've already raised question on [Nunit github ](https://github.com/nunit/nunit/issues/4129) and they offered to ask here. With regards TestCentric I know about it but was not sure if I should raise issue there since I noticed similar behavior in other products. So I will create a new ticket for that if it has own engine.
It is good idea to verify the OpenCover since all request comes via this command utility. I will try this out tomorrow and see results. If nobody else is having such a problem on Azure DevOps then obviously something is missing or outdated in our builds despite fact source control server version is almost latest. Thanks for support.

**Comment by CharliePoole** [comment] 2022-06-30 16:40
Sorry for being a little testy, @gps7. I'm afraid that my leaving NUnit to do the GUI is a sore point for me and possibly others as well, so let's get into it on the TC project instead.

Summarizing...

* NUnit Framework creates all the XML for each assembly at the end of the run. In addition, it sends noifications as each test is run.
* The engine basically passes the XML on to any runner that uses it, adding a `<test-run>` element to wrap all the assemblies in the final result. It also passes on the notifications and adds start of run and end of run notifications.
* A runner like nunit3-console can use the notifications and/or final result to display or save whatever it likes.
* The vs-adapter acts as a runner on behalf of Test Explorer, vstest.exe or dotnet CLI. It too does what it likes with the output but is, of course, limited to what VS can understand when running in that environment.

For all the projects under github.com/nunit, we can transfer an issue for you if it isn't in the right place. Sometimes, however, it isn't clear or multiple projects are involved, so separate issues work better. TC GUI issues have to go to the gui repo, with which you are already familiar.

**Comment by gps7** [comment] 2022-06-30 17:04
@CharliePoole thanks for detailed summary since was really hard to get how this part of Nunit works. I've created a new issue on TC, then same problem will be for vs-adapter. I believe the vs-adapter located here: https://github.com/nunit/nunit3-vs-adapter

**Comment by gps7** [comment] 2022-07-01 06:37
I've eliminated OpenCover from Azure DevOps build and result is still same. Here is the executed command line this time:
```
Execute nunit3-console (File version 3.15.0.0, Product version 3.15.0): D:\TfsBuildAgent2020\_work\301\s\Utility\NUnit3\NUnit3-bin\nunit3-console.exe "Eaf.CellAutomation.UnitTests.dll" "Eaf.Core.UnitTests.dll" "Eaf.Equipment.Implementation.UnitTests.dll" "Eaf.Equipment.Interfaces.UnitTests.dll" "Eaf.Equipment.MergeModel.UnitTests.dll" "Eaf.Equipment.TraceJoin.UnitTests.dll" "Eaf.EquipmentConnector.CommandTranslation.UnitTests.dll" "Eaf.EquipmentConnector.UnitTests.dll" "Eaf.UnitTests.dll" "Eaf.ComponentTests.dll" "Eaf.Core.ComponentTests.dll" "Eaf.Equipment.TraceJoin.ComponentTests.dll" --process:Multiple --x86 --agents=1 --skipnontestassemblies --result="D:\TfsBuildAgent2020\_work\301\TestResults\results.xml" --out="D:\TfsBuildAgent2020\_work\301\TestResults\output.log"
Working Directory: D:\TfsBuildAgent2020\_work\301\s\Source\Implementation\bin
NUnit Console 3.15.0 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
Friday, July 1, 2022 8:24:10 AM
```
And test overview is still same:

![Build_server_test_results without OpenCover](https://user-images.githubusercontent.com/21167960/176837602-023acc5e-c7e3-4cbf-81bc-14b10325c517.PNG)

I have no explanation on this and no ideas anymore what else I can try it out to determine the source of this test results.

**Comment by CharliePoole** [comment] 2022-07-01 11:52
OK. I'll try to duplicate this myself.

**Comment by CharliePoole** [comment] 2022-07-01 15:58
I'm pretty convinced that Azure is actually the cause of the problem. I believe it reads the TestCentric.xml file and only looks at the legacy failure element. In addition to the problem with `Assert.Multiple` this means that it probably will not report warnings. That's surprising to me given how long those features have been present in NUnit - but less surprising when I consider that it's Microsoft. Test Explorer doesn't handle either of those features well either. In fact the legacy message was created primarily for use under Test Explorer.

I'm closing this again and I'll see about filing an issue with the Azure team.

**Closed by CharliePoole** 2022-07-01 15:58 UTC
Labels: Not a Bug

**Comment by CharliePoole** [comment] 2022-07-01 16:04
@gps7 If there were an option in the console like `--copyOutput=FILE` do you think that would help? My thinking is that it should take __all__ output displayed to the console and __also__ send it to a file. That would include NUnit's own error messages as well as output written by your test (currently handled by `--out`)

I can't promise fast action, but if it makes sense and you file an issue, I'll put it on the backlog for version 4.

**Comment by gps7** [comment] 2022-07-01 16:31
@CharliePoole thanks for analysis and great support. Offered feature would be a great benefit for us to have output of all information combined and this would help to have one source instead multiple sources. Additionally, start of test as well as test results with count of failed and successful tests would be a great advantage for us. I was planning to create a new feature request for this next week.
