### ISSUE TITLE
nunit3-console.exe delete automatically 

### ISSUE THREAD

**Issue by AnuruddhaMk** [nunit/nunit-console#432] opened 2018-06-25 09:11 UTC
I have some automation jobs in jenkins..when I try to build the project sometime "nunit3-console.exe" setup file automatticlly delete...what is the issue here

**Comment by mikkelbu** [comment] 2018-06-25 17:22
Hi @AnuruddhaMk 
We will need some more information in order to be able to help you (the more information you provide then better we can answer).
* When you write "when I try to build the project" do you mean the nunit-console project?
* If the file `nunit3-console.exe` is deleted then I think that the problem is in your automatic job. Can you provide this?

**Comment by AnuruddhaMk** [comment] 2018-06-26 07:52
Hi @mikkelbu 
Project Build is successfully competed but after one or two days when jenkins try to build(we scheduled to Auto build this project) build faild due to nunit3-console.exe missing from location then we need to manually copy to this file...we can write a simple script to download the "nunit3-console.exe" when if it's didn't exist but before that we need to know issue.

**Comment by mikkelbu** [comment] 2018-06-26 08:12
Hi @AnuruddhaMk 
There is no functionality in the nunit-console to delete itself after X days (or similar).

This much more sounds like at Jenkins problem like https://issues.jenkins-ci.org/browse/JENKINS-26238 or https://issues.jenkins-ci.org/browse/JENKINS-19686, but I also think that for them to be able to help you, you will need to provide more information than you have currently done (e.g. setup, installed version, configurations, buildscript etc.). So I propose that you create an issue at https://issues.jenkins-ci.org.

**Comment by ChrisMaddock** [comment] 2018-07-08 11:32
Closing this, as it looks like the problem may lie outside of NUnit.

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2018-07-08 11:32 UTC
Labels: is:question
