### ISSUE TITLE
<TestAssemly.dll>.config files not loaded when using an .nunit project file and --process=Multiple

### ISSUE THREAD

**Issue by chrisalbrecht** [nunit/nunit-console#418] opened 2018-05-11 12:12 UTC
Using a .nunit file to run multiple assemblies and --process=Multiple will no longer attempt to load a `<TestAssemblyName>.dll.config` file for each assembly, where as versions 3.7 and earlier would.

The command line i'm using is:
`nunit3-console NUnitProjectFile.nunit --process=Multiple`

My .nunit file is like this:

```
<NUnitProject>
  <Settings activeconfig="Release"/>
  <Config name="Release" binpathtype="Auto">
    <assembly path="TestAssembly1.dll" />
    <assembly path="TestAssembly2.dll" />
  </Config>
</NUnitProject>
```

Previously this would result in the respective `TestAssemblyN.dll.config` being loaded for each test assembly, but this is no longer the case as of 3.8. Now the only config file that is attempted to be loaded is `NUnitProjectFile.nunit.config` (can be seen in SysInternals Process Explorer during a test run).

This seems to be related to the change in behaviour noted in issue [#382](https://github.com/nunit/nunit-console/issues/382).

**Comment by rprouse** [comment] 2018-05-14 13:18
You are probably right, this is most likely caused by #382 and may be a duplicate.

**Comment by ChrisMaddock** [comment] 2018-07-08 11:36
Adding this to 3.9 alongside #382 - to make sure it gets fixed

**Comment by fredericDelaporte** [comment] 2019-09-15 13:43
This trouble of .config file not loaded also occurs with 3.10.0 when using `--process=separate` command line argument. Not specifying the process option dodges the issue. This has been reproduced with [this project](https://github.com/nhibernate/nhibernate-core/blob/02a631586558d09a917cde77a86bdfd9b09009c6/NHibernate.nunit) and the command line `nunit3-console --agents=1 --process=separate NHibernate.nunit`. With 3.7.0 we were not having the issue.

**Comment by WenningQiu** [comment] 2020-04-21 14:10
> This trouble of .config file not loaded also occurs with 3.10.0 when using `--process=separate` command line argument. Not specifying the process option dodges the issue. This has been reproduced with [this project](https://github.com/nhibernate/nhibernate-core/blob/02a631586558d09a917cde77a86bdfd9b09009c6/NHibernate.nunit) and the command line `nunit3-console --agents=1 --process=separate NHibernate.nunit`. With 3.7.0 we were not having the issue.

Same behavior still exists in 3.11.1

**Comment by CharliePoole** [comment] 2021-11-07 22:48
Does anyone remember when we __started__ doing the 3.7 behavior, which is no longer there? I know that we originally __required__ a single config file for an nunit project. See, for example [this article](http://charliepoole.org/technical/how-nunit-finds-config-files.html), which I wrote in 2005.

I believe we made the change to using separate configs if a general config was not provided sometime at the start of NUnit 3 and I'd like to update the article.

**Comment by CharliePoole** [comment] 2021-11-16 16:51
I looked at the history between 3.7 and 3.8. In 3.8, we included a change to allow specifying the config on the command-line. In the case of a list of assemblies, the default (test.dll.config) was used if nothing was provided. In the case of a project, also resulted in the default: a single project config. To fix, we would probably have to check whether the default project config was present and take action in it's absence. @nunit/engine-team Does somebody want to work on this?

**Comment by CharliePoole** [comment] 2021-11-16 16:51
PS: Does not appear at all related to #382, which I fixed.

**Comment by CharliePoole** [comment] 2021-11-22 09:36
@nunit/engine-team 

Does anyone want to take this issue on? We're now about a week away from the scheduled release date. One step might be to create a test that proves the issue is still there after the other fixes we've done.

**Comment by mikkelbu** [comment] 2021-11-24 22:11
@CharliePoole I don't have time for it the next couple of weeks. Currently, I'm not even able to read and respond to all the notifications I get from github at the moment :(

**Comment by CharliePoole** [comment] 2021-11-25 01:31
I'll take a look. If it's complicated, I'll postpone.

**Comment by CharliePoole** [comment] 2021-11-26 06:05
Even though the fix to #382 didn't deal with this directly, it had the side effect of eliminating the problem. However, it may have also eliminated the use of the combined config file for a project (project.name.config). I'm adding some logging so we can see what's going on in the internal trace.

**Comment by CharliePoole** [comment] 2021-11-26 11:04
Will update the project loader extension to handle the use of `projectname.config` as the default value if the file exists in the same directory as the project itself. See nunit/nunit-project-loader#44.

**Comment by CharliePoole** [comment] 2021-11-26 11:20
Azure failure in creating msi package. I haven't made any changes to this and it worked on Monday. I presume something has changed in the supported environment but i don't have sufficient access to fix it - not to mention my lack of knowledge of Azure. Can some other @nunit/engine-team member look at this? Otherwise, I'll bypass the check and merge the trivial logging changes I made.

**Comment by CharliePoole** [comment] 2021-11-26 15:16
I have verified manually by code inspection that `ProjectService` sets the config to `projectname.config` IFF the project itself doesn't provide a setting and the file exists. That means changing `nunit-project-loader` is unnecessary for now. It doesn't need to be changed in the future provided we like how things currently work, i.e.

1. If the user sets a config file from the command-line, we use that.
2. If the project loader sets a config file and the user doesn't, we use the setting from the project config.
3. If neither of the above applies, and `projectname.config` exists, we use it.
4. In all other cases, we use the individual `test.dll.config` for each assembly.

If we want any of the above to change, we should create a new issue.

I'll keep this one open for now so we can look at the Azure problem.

**Comment by CharliePoole** [comment] 2021-11-26 22:22
Closing as fixed as a result of fixing #382

**Closed by CharliePoole** 2021-11-26 22:22 UTC
Labels: is:bug, pri:high

**Comment by mikkelbu** [comment] 2021-11-28 10:59
> Azure failure in creating msi package. I haven't made any changes to this and it worked on Monday. I presume something has changed in the supported environment but i don't have sufficient access to fix it - not to mention my lack of knowledge of Azure. Can some other @nunit/engine-team member look at this? Otherwise, I'll bypass the check and merge the trivial logging changes I made.

I took a look at it, and the successful builds use image 20211110.1 and the failing 20211122.1 which is a new image released 3 days ago, so I would guess that triggering a build on master (or on other branches) will fail with the same results (I cannot do this from this computer). 

Looking at the diff between the images - https://github.com/actions/virtual-environments/pull/4569/files - I can see that several packages/components related to WIX have been removed from Visual Studio and instead the program `WiX Toolset v3.11.2.4516` has been installed. So I guess we can fix the problem by using this program to create the MSI rather than VS. I'll see if I have time to look at it tonight (otherwise I don't think I've time before Tuesday/Wednesday). Although, I don't know anything about WiX and MSI :)

Ps. We are not the only ones affected by this
* actions/virtual-environments#4419
* actions/virtual-environments#4582
* actions/virtual-environments#4573
* ...

**Comment by mikkelbu** [comment] 2021-11-28 11:02
EDIT: Or actually, perhaps we should just wait a couple of days, as it seems like they have reverted the change, and thus it will start working again next week - https://github.com/actions/virtual-environments/issues/4419#issuecomment-980209725

**Comment by CharliePoole** [comment] 2021-11-28 11:35
@mikkelbu Once again, thanks for finding the time! Waiting will work for now.

I'm pretty familiar with WIX but I've never liked using the VS extension. Our build is manual but it depends on the `wixproj` file, which imports some targets that are pretty irrelevant to our use. I'll see if I can get rid of that in the script when I have a chance.
