### ISSUE TITLE
"Execution terminated after first error" does not fail the console runner

### ISSUE THREAD

**Issue by Sam13** [nunit/nunit-console#282] opened 2017-08-18 13:48 UTC
After updating to NUnit 3.7.1 (Console runner 3.7.0) I noticed that some of my tests are no longer executed. I use the option to stop on first failure. 
When analyzing the log file I found out that there was an exception in tear down which was reported correctly in the console but the console runner itself does not report failure.
Is it intended that tear down (and maybe also setup) exceptions no longer fail the test run?

Details:
```
5) TearDown Error : SomeIntegrationTest.Test<Enum1>(Param1,False,True)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
   at SomeIntegrationTest....

Execution terminated after first error

Run Settings
    RuntimeFramework: net-4.5
    DisposeRunners: True
    WorkDirectory: C:/Teamcity/BuildAgent/work/52362ff0ee379106/bin/x64/Debug
    StopOnError: True
    MaxAgents: 1
    NumberOfTestWorkers: 1
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False

Test Run Summary
  Overall result: Failed
  Test Count: 1840, Passed: 621, Failed: 0, Warnings: 0, Inconclusive: 200, Skipped: 1019
    Skipped Tests - Ignored: 5, Explicit: 1014, Other: 0
  Start time: 2017-08-18 12:59:21Z
    End time: 2017-08-18 13:09:08Z
    Duration: 586.926 seconds
```

**Comment by CharliePoole** [comment] 2017-08-18 15:35
The error is reported, as you say, and the run indicates that the overall result is failure. I'm guessing that the failure is in a OneTimeTearDown method because no test cases are reported as failing. Is that correct? What exactly is different from when you have run the tests before? Does it change as a result of upgrading the framework or the console runner?

**Comment by ChrisMaddock** [comment] 2017-08-18 15:54
I presume you're referring to the `--stoponerror` flag, @Sam13?

@CharliePoole - this sounds like it could be caused by the changes to make OneTimeTearDown a separate WorkItem, and thus all OneTimeTearDowns running right at the end of the process? So hopefully would be fixed by https://github.com/nunit/nunit/pull/2350?

Sam - could you try the latest build of NUnit framework master from https://www.myget.org/F/nunit/api/v2? If my guess is right - it should already be fixed.

**Comment by CharliePoole** [comment] 2017-08-18 15:57
@ChrisMaddock Nevertheless, I'd like to hear what @Sam13 thinks the console should be showing, because what I'm seeing in the issue looks like correct output to me.

**Comment by ChrisMaddock** [comment] 2017-08-18 16:01
Sorry - I've totally mis-read this. Removed my comment.

**Comment by Sam13** [comment] 2017-08-21 10:27
@CharliePoole The output is correct, but the process exit code of NUnit console is 0 which does not fail the build...

**Comment by ChrisMaddock** [comment] 2017-08-21 10:48
That would be a bug. To help debugging, could you add your xml result file to this issue?

**Comment by Sam13** [comment] 2017-08-21 12:28
I had to strip some stuff out, but should be sufficient to fix the issue
[IntegrationTest.x64.Release.TestResult.txt](https://github.com/nunit/nunit-console/files/1238767/IntegrationTest.x64.Release.TestResult.txt)

**Comment by CharliePoole** [comment] 2017-08-21 12:35
Based on the console output, I would guess that none of the five errors were errors in test cases. That is, they might be errors in test discovery or in the fixture onetimestartup/teardown code. Historically, NUnit only reported test case errors, which is what the "failed" count reflects. Gradually, we added display of error messages when the failure was in the fixture itself rather than in an individual test case. We also show the overall result as "Failed" when any of those non-testcase errors occur. It looks like we never dealt with the return code, however.

**Comment by CharliePoole** [comment] 2017-08-21 12:43
TestResult seems to confirm my guess.

We should decide what the return code should be in these cases. One approach would be to return the number of errors and failures displayed, even if they are not test case errors. Another would be to create a new negative return code value indicating that onetime setup or teardown errors occured even though all test cases passed. A third simple approach would be to return the existing "unexpected error" code.

**Closed** 2018-11-19 01:53 UTC
Labels: confirm, is:bug
