### ISSUE TITLE
test-run xml counts incorrect in certain test failure situations

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#342] opened 2018-01-10 12:05 UTC
@Majorie1234 commented on [Wed Jan 10 2018](https://github.com/nunit/nunit/issues/2653)

<img width="479" alt="capture" src="https://user-images.githubusercontent.com/35286915/34769993-8f93a8c0-f625-11e7-9206-0cd42a5e0118.PNG">
<img width="872" alt="capture" src="https://user-images.githubusercontent.com/35286915/34770034-b58e6ff6-f625-11e7-8008-13b9fbc4d049.PNG">

  The test run attributes like no of passed and failed tests are not correctly updated in the xml report generated..however the command prompt console shows these values correctly..what am i doing wrong
  

---

@ChrisMaddock commented on [Wed Jan 10 2018](https://github.com/nunit/nunit/issues/2653#issuecomment-356583387)

This part of the report is generated by the NUnit Engine.

I'll move this issue over to that repository, and comment further over there.

**Comment by ChrisMaddock** [comment] 2018-01-10 12:07
Interesting! I don't see this problem in the general case - I imagine it might be something to do with where your failure takes place.

Where does the failure shown on the console occur - is it in a TestCaseSource or something? Can you share the full results xml please?

**Comment by CharliePoole** [comment] 2018-01-10 14:57
The summary report is generated by the console runner based on details of the test case results. The summary counts in the test-suite elements of the XML are generated by the framework. The summary in the test-run element is generated by the engine based in the individual assembly test-suite elements, and it is most likely not the problem.

The framework-generated summaries just add up the contained results based on the test status of individual cases.

The console summary uses a different principal. It counts a test as a failure if it was never run because of a failure in a higher level setup. We do that because users asked for it many years ago.

We list one time setup failures in the detail part of the report so users will know where the "extra" failures came from.

My guess is that examination of the full XML will show that the problem is due to console augmenting the failure count by design. Note that if we didn't do that, you would have failures with a failure count of zero.

**Comment by Majorie1234** [comment] 2018-01-11 04:16
[testresult.zip](https://github.com/nunit/nunit-console/files/1621225/testresult.zip)

**Comment by Majorie1234** [comment] 2018-01-11 04:22
Even the passed test count is incorrect.
The same report generated using nunit 2 format gives the correct count though.
[testresultnunit2.zip](https://github.com/nunit/nunit-console/files/1621238/testresultnunit2.zip)

**Comment by CharliePoole** [comment] 2018-01-11 16:58
Reviewing the attached nunit3 zip, here's what I see.

Assembly 1: total="2" passed="0" failed="0" inconclusive="0" skipped="0"
Assembly 2: total="4" passed="0" failed="0" inconclusive="0" skipped="0"
    Test Run: total="6" passed="0" failed="0" inconclusive="0" skipped="0"

That adds up, so the engine is doing it's job properly. The error is in the info further down in the file, which is created by the framework. I'll close this as not a bug and re-open the framework issue.

**Closed** 2018-01-11 16:59 UTC
Labels: closed:notabug

**Comment by CharliePoole** [comment] 2018-01-11 17:07
Following up on the comment about the XML output for nunit v2 tests... The tests are run using entirely different code and the summary XML is created using different code that is based on compatibility with the old NUnit V2 output. Naturally, the results are not necessarily going to be the same.
