### ISSUE TITLE
NUnit3 Runner skips end of line char in regular expression

### ISSUE THREAD

**Issue by niks-** [nunit/nunit-console#56] opened 2016-09-11 21:09 UTC
I have 5 tests with the following full names:
NUnit3_Suites.MainSuite.Category1.Categoty1Test.category1_test_1
NUnit3_Suites.MainSuite.Category1.Categoty1Test.category1_test_2
NUnit3_Suites.MainSuite.Category1.TestSuite1.TestSuite1Test.testsuite1_test_1
NUnit3_Suites.MainSuite.Category1.TestSuite1.TestSuite1Test.testsuite1_test_2
NUnit3_Suites.MainSuite.Category1.TestSuite1.TestSuite1Test.testsuite1_test_3

I am trying to run tests by the following command:
nunit3-console.exe NUnit3-Suites.dll --where "test=~NUnit3_Suites.MainSuite.Category1.\w+.\w+$"

I expect only first two tests will be run. However it runs all of them http://prntscr.com/cgvpjk
I verified the regular expression I used with this  https://regex101.com/ online tool -> I found only two matches http://prntscr.com/cgvruy
I also verified with C# code Regex.IsMatch which is mentioned you use inside NUnit for reg.exp.
The result - also only two matches found http://prntscr.com/cgvw2o

It seems NUnit skips the "end-of-line" ($) symbol in regular expression. Could you please check on your side within NUnit source code

**Comment by CharliePoole** [comment] 2016-09-11 22:07
Try this

```
nunit3-console.exe NUnit3-Suites.dll --where "test=~/NUnit3_Suites.MainSuite.Category1.\w+.\w+$/"
```

**Comment by niks-** [comment] 2016-09-12 04:09
It runs nothing http://prntscr.com/cgz9nj

**Comment by niks-** [comment] 2016-09-14 19:08
Could you please confirm if it is a bug?

**Comment by CharliePoole** [comment] 2016-09-15 17:09
As a test, try replacing each \w+ with [A-Za-z0-9_]+

Also, what culture are you running under and what version of .NET is used for your code tests - the NUnit engine uses .NET 2.0.

**Comment by niks-** [comment] 2016-09-16 05:33
Project was targeted to .NET 4.5. I re-targeted it to .NET 2.0, rebuild and re-verified with previous regexp and with "[A-Za-z0-9_]+" replacement.
Result is the same - http://prntscr.com/cikhru. It still runs tests which should not.

Culture is default {en-US} without any customization http://prntscr.com/cikiyg

**Comment by niks-** [comment] 2016-09-26 05:40
Any updates?

**Comment by rprouse** [comment] 2016-10-12 00:43
@niks- it is likely a bug, but I am putting the confirm label on this so that an @nunit/core-team or @nunit/contributors can look at it.

**Comment by constructor-igor** [comment] 2016-10-30 14:02
I reproduced the issue

**Comment by constructor-igor** [comment] 2016-10-30 14:15
I try to test the issue with help of regex.Match:

2 tests (with expected "True") failed

```
    [TestFixture]
    public class RegexpIssue56Tests
    {
        [TestCase("NUnit_v3_samples.Issue56.Category1Test.category1_test_1", true)]
        [TestCase("NUnit_v3_samples.Issue56.Category1Test.category1_test_2", true)]
        [TestCase("NUnit_v3_samples.Issue56.NameSpace2.TestSuite1Test.testsuite1_test_1", false)]
        [TestCase("NUnit_v3_samples.Issue56.NameSpace2.TestSuite1Test.testsuite1_test_2", false)]
        [TestCase("NUnit_v3_samples.Issue56.NameSpace2.TestSuite1Test.testsuite1_test_3", false)]
        public void Test(string fullTestName, bool expected)
        {
            Regex regex = new Regex(@"~NUnit_v3_samples.Issue56.\w+.\w+$");
            Match match = regex.Match(fullTestName);
            Assert.That(match.Success, Is.EqualTo(expected));
        }
    }
```
![image](https://cloud.githubusercontent.com/assets/1849690/19837131/0989445e-9ebc-11e6-9bf1-237b235ec2d1.png)

**Comment by constructor-igor** [comment] 2016-10-30 20:04
As I understand, relevant code of filter execution implemented in project https://github.com/nunit/nunit
Please, let me know name of relevant test class? I want to prepare test.

**Comment by CharliePoole** [comment] 2017-05-01 18:40
Unfortunately, nobody has assigned this to themselves, so it has not been addressed for a long time.  I'm reviewing some old issues and looking back at this one I notice that the character '.' is not escaped in the pattern. Since '.' matches any character, I would expect strange results when it is used in a situation where you expect a literal '.'. Furthermore, the cases that are acting strangely are those that have three '.' characters rather than just two.

**Comment by tom-dudley** [comment] 2017-05-07 10:49
OK I've had a look at this and I think I see what's going on. [This](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs#L314) is the offending line. Basically we're calling `filter.Pass` which is `return Match(test) || MatchParent(test) || MatchDescendant(test);` and so the wrong tests get picked up since `MatchParent` is true. Is this just a simple case of changing that line to `if (_childFilter.Match(test))`, which seems to be the correct method to use? I'm a bit confused as to what the difference between `Match` and `Pass` is for the filters.

**Comment by CharliePoole** [comment] 2017-05-07 15:18
@tom-dudley I understand your point, but it seems separate from the issue how we match. or don't match a regex. That is, if the line in question is an error, then we would have a failure for the simplest sort of tests as well.

There's some history here, and we may need to review it to see if fundamental changes to the logic of test filter are needed. Some simpler test cases may help to narrow it down.

We are using an ITestFilter here. It only exposes `Pass` and 'IsExplicitMatch`. Originally, it only had only `Pass`, but I added the second method a few years ago to deal with some issues around `[Explicit]`. The other public methods of TestFilter are public primarily so we can test them. Historically, NUnit didn't expose internals to its tests. We could probably (have to check) make those internal for clarity.

`Pass` means, basically, "run this test." `Match` means that the test, taken in isolation, passes the filter.

Consider two cases, no filter and a filter naming a single fixture...

1. With no filter (i.e the empty filter), the first match passes every time so `Pass` succeeds immediately on every test, just as we want.

2. With a fixture naming a single fixture, the case varies...
  * If we are above the fixture in the hierarchy, `MatchDescendant` passes. That causes us to descend another level in executing tests. If we didn't do that, we would never reach the fixture.
  * When we reach the fixture, `Match` itself passes, as we would expect.
  * When we are below the fixture, `MatchParent` passes, because we want to run all children of the fixture. (Explicit tests are dealt with separately)
  * When we are in some other branch, e.g. in a sibling fixture, no match passes and we don't run the test.

If we were to replace `Pass` with `Match`, then only the exact fixture would pass, but we would never reach it in our descent. And even if we could reach it, it's children would not pass either.

There is a fundamental inefficiency here, which we have always recognized: It should be possible to skip testing with `MatchParent` if we know that we are under a test in the hierarchy that has already matched. However, running some tests many years ago, I found out that the savings would be fairly small and the complexity of a self-modifying filter would be... complicating. :smile:

**Comment by tom-dudley** [comment] 2017-05-07 20:31
The XML doc for `Pass` says `<returns>True if the test passes the filter, otherwise false</returns>` and for `Match` in `ValueMatch` filter says `<returns>True for a match, false otherwise.</returns>`. To me this sounds like they're doing the same thing, i.e. seeing if a test matches the given filter. I'm still confused by the different method names here (or is it just historical?)

This may be a simplistic view, but I'm assuming the output we want is a list of tests to run, so why the need for `Pass` at all? Would something like the following not suffice?
```
public List<ITest> AddMatchingTests(ITest parentTest, ITestFilter filter, List<ITest> testsToRun)
{
    foreach (ITest test in parentTest.Tests)
    {
        if (filter.Match(test))
        {
            testsToRun.Add(test);
        }
        AddMatchingTests(test, filter, testsToRun);
    }
    return testsToRun;
}
```
or alternatively, on `TestFilter` itself:
```
public List<ITest> AddMatching(ITest parentTest, List<ITest> testsToRun)
{
    foreach (ITest test in parentTest.Tests)
    {
        if (this.Match(test, testsToRun))
        {
            testsToRun.Add(test);
        }
        AddMatching(test, testsToRun);
    }
    return testsToRun;
}
```

**Comment by CharliePoole** [comment] 2017-05-07 21:29
We may need to take this elsewhere, since it isn't very closely connected with the particular issue - an issue filed on the console runner rather than the framework. But let's try another round. 😄

Consider my earlier example of a filter that is intended to run a single fixture. Your suggestion would give us a list with one item, the fixture itself. But that begs the question. We still wouldn't know how to run that fixture, since it's not something you can simply execute. In fact, assuming it's My.Test.Fixture, we actually have to run...

* The test representing the assembly
* The test representing the namespace My
* The test representing the namespace Test
* The test representing Fixture itself
* All of the individual tests, which are children of Fixture, except those marked [Explicit

Just having a list containing Fixture doesn't tell us how to do that unless we write more code, which will end up looking a lot like what we already have.

I don't see this discussion as tying into the actual reported error, which is what we should discuss here. Unless you can bring it back to that issue, I think we should discuss the general design of filtering in a separate framework issue or on the mailing list.

**Comment by CharliePoole** [comment] 2017-05-07 21:33
Can we close this issue? @constructor-igor indicated a long time ago that he reproduced it, but then showed an example where the regex works exactly as reported in the original. So, unless I'm not understanding, the problem is not actually there.

**Comment by tom-dudley** [comment] 2017-05-07 22:05
I don't think it should be closed, as I'm able to reproduce the original bug (where the last 3 tests are picked up when they shouldn't be when filtering). The tests which @constructor-igor wrote show that the .NET regex works as it should. They don't however test what happens when you supply that as a regex filter, which hits the code in `CompositeWorkItem` and subsequently calls `filter.Pass`. This is why I was mentioning `Pass` and `Match`.

I'd be happy to discuss this elsewhere, but I'm fairly certain its at least tangentially related :)

**Comment by tom-dudley** [comment] 2017-05-07 22:33
What you said regarding children makes sense actually. So I think what it happening here is that the regex matches `NUnit3_Suites.MainSuite.Category1.TestSuite1.TestSuite1Test` and in order to run that test we run its children. You can ignore my previous ramblings!

This actually means everything is working as intended and is down to incorrect understanding of what the "test=~" expression will match on (in this case, a TestFixture). I do see a valid use case however where the test selection language makes the distinction between `test` in the general sense and `actualtest` in the sense of a method with the `[Test]` attribute. I believe that is what @niks- was trying to accomplish here, and I would have done the same.

That being said, it's definitely a separate discussion so I'm no longer against this being closed.

**Comment by CharliePoole** [comment] 2017-05-07 22:44
Ah! Now I understand...

Since everything is a test, you have to be careful with any expressions that could match at several levels in the tree. This doesn't generally come up with simple equality matching, but it can happen very easily with a regular expression. In addition, I think the use of "." in the pattern rather than "\." is confusing the issue.

Closing this.

**Closed by CharliePoole** 2017-05-07 22:44 UTC
Labels: is:bug, pri:normal

**Comment by CharliePoole** [comment] 2017-05-07 22:48
@tom-dudley Note that "test" refers to the test name, which is an arbitrary string. OTOH "class" can be used to refer to the full name of the class and "method" is the name of the method. Users can change their test names using certain attributes but the class and method remain the same.
