### ISSUE TITLE
NUnit3 console execute on .netCore 3.1" on Windows command line-InvalidCastException : Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler' using latest released packages..

### ISSUE THREAD

**Issue by Kieran-Boland** [nunit/nunit-console#1018] opened 2021-09-24 07:44 UTC
**ISSUE:**
Trying to run a Visual Studio 2019 Community Edition, C# & Selenium Webdriver Nunit project in via "Console mode" (instead of via the Visual Studio G.U.I.
Getting the following errors (similar to previous issues "#475" & "#792".

**IS THERE A WORKAROUND AVAILABLE** (i.e.. in #792 (24th June 2020) CharliePoole commented: 

    "The 3.11.1 NUnit Framework supports .NET Core but the Console runner does not yet support it. 
     We hope to have support in the 3.12 release of the console runner.

     For now, your options are

       1. Run using NUnitLite, which is distributed along with the NUnit framework.
       2. Use dotnet CLI.
       3. Run in the test explorer under Visual Studio.

    Options 2 and 3 require use of the NUnit 3 VS adapter."

**Question. Do you have any details of how to implement the NUnitLite workaround as mentioned above? 
                  (I see an NUnitlite.dll in the \NUnit-console\bin\netcoreapp3.1 folder.)** 

------------------------

c:\Selenium\NUnit-console\bin\net35>**nunit3-console.exe --trace=Debug "C:\Selenium\Projects\CP4NA_Nimrod_BVT_Firefox\bin\Debug\netcoreapp3.1\CP4NA_Nimrod_BVT_Firefox.dll"**
NUnit Console Runner 3.12.0 (.NET 2.0)
Copyright (c) 2021 Charlie Poole, Rob Prouse
Friday 24 September 2021 07:52:22

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    C:\Selenium\Projects\CP4NA_Nimrod_BVT_Firefox\bin\Debug\netcoreapp3.1\CP4NA_Nimrod_BVT_Firefox.dll

Errors, Failures and Warnings

1) Error :
         **NUnit.Engine.NUnitEngineException : The NUnit 3 driver encountered an error while executing reflected code.
         ----> System.InvalidCastException : Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
         --NUnitEngineException
         The NUnit 3 driver encountered an error while executing reflected code.**

------------------------

**(A)** Full Command Used:  nunit3-console.exe --trace=Debug "C:\Selenium\Projects\CP4NA_Nimrod_BVT_Firefox\bin\Debug\netcoreapp3.1\CP4NA_Nimrod_BVT_Firefox.dll"

**(B)** Method of Installation: NuGet for the NUnit testing framework.
     Nunit-Console installed using a ZIP download file from the Nunit website: https://nunit.org/download/
     (Version:  NUnit Console 3.12,  January 17, 2021 )

**(C)** Log file attached.

**(D)** All versions of the software in use:

              PM> Get-Package 
              Id                 
              Selenium.WebDriver , {Version: 3.141.0}
              System.Drawing.Common , {Version: 5.0.2}  
              Microsoft.NET.Test.Sdk , {Version: 16.5.0}
              NUnit , {Version: 3.13.2} 
              DotNetSeleniumExtras.WaitHelpers , {Version: 3.11.0}                                                                       
              Selenium.Support , {Version: 3.141.0}   
              NUnit3TestAdapter, {Version: 4.0.0}
              Selenium.Firefox.WebDriver,  {Version: 0.27.0}  "Marionette (Win64)"  
              coverlet.collector, {Version: 3.1.0}   
              SSH.NET , {Version: 2020.0.1} 
              NUnit.Console , {Version: 3.12.0}

              Microsoft Visual Studio Community 2019, Version: 16.11.3
              Project:
                   - Target framework: .NET Core 3.1
                   - Output type:  Console Application

**(E)** No difference when running the command with the **--inprocess** flag.

[InternalTrace.12604.log](https://github.com/nunit/nunit-console/files/7223851/InternalTrace.12604.log)
[InternalTrace.13412.CP4NA_Nimrod_BVT_Firefox.dll.log](https://github.com/nunit/nunit-console/files/7223854/InternalTrace.13412.CP4NA_Nimrod_BVT_Firefox.dll.log)
[nunit-agent_13412.log](https://github.com/nunit/nunit-console/files/7223862/nunit-agent_13412.log)

**Comment by ds-vinny** [comment] 2021-10-02 07:51
I am also seeing this error on the latest version and hope to help confirm the issue.
I created a [Hello World Project](https://github.com/ds-vinny/RecreatingConsoleRunnerError) to provide a way to replicate the issue. 
Notes: I am using the Nunit Console Runner 3.12.0 that I installed with chocolatey.

Steps To Reproduce Issue
1. Clone the [Hello World Project](https://github.com/ds-vinny/RecreatingConsoleRunnerError)
2. Navigate to the RecreatingConsoleRunnerError\bin\Debug\net5.0 Directory with PowerShell
3. Run the following command _nunit3-console.exe .\RecreatingConsoleRunnerError.dll --where "cat == Hello"_

![image](https://user-images.githubusercontent.com/67294328/135708269-22778ebc-2eaa-406a-af73-3edef0ea06fd.png)

I hope this helps confirm the issue. Let me know if there is any other information that is needed or would be helpful to resolve this.

**Comment by mikkelbu** [comment] 2021-10-02 21:19
@Kieran-Boland as far as I can tell you are using the regular NUnit Console to run .NET Core 3.1 tests and this is not supported. You can try the .NET Core NUnit Console 3.12.0-beta2 - https://github.com/nunit/nunit-console/releases/tag/v3.12.0-beta2 - to run the tests, but there are some know problems with this console, hence the beta.

Charlie's alternatives above still hold
* Using the NUnit adapter and then either run the tests from VS or using `dotnet test`
* Using the NUnitLite

For the latter see https://docs.nunit.org/articles/nunit/running-tests/NUnitLite-Runner.html. The documentation is almost correct, but the  Program.cs mentioned is no longer automatically added, due to some changes in the NuGet packing.

So if one creates a project like this
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnitLite" Version="3.13.2" />
  </ItemGroup>

</Project>
```
and with a C# like - the important part is the `Main`, the tests could be in other files, this is just for simplicity in this example
```csharp
using NUnit.Framework;
using NUnitLite;

namespace TestNUnitLite
{
    class Program
    {
        public static int Main(string[] args)
        {
            return new AutoRun().Execute(args);
        }


        [TestCase(1)]
        [TestCase(2)]
        public void Test(int number)
        {
            Assert.That(number, Is.GreaterThan(0));
        }
    }
}
```
Then when I execute this program I get
```
PS C:\Users\Mikkel N. Bundgaard\source\repos\TestNUnitLite\TestNUnitLite\bin\Debug\net5.0> .\TestNUnitLite.exe
NUnitLite 3.13.2 (.NET Standard 2.0)
Copyright (c) 2021 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows 10.0.19043
  CLR Version: 5.0.7

Test Files
    .../repos/TestNUnitLite/TestNUnitLite/bin/Debug/net5.0/TestNUnitLite.dll

Test Discovery
  Start time: 2021-10-02 21:13:58Z
    End time: 2021-10-02 21:13:58Z
    Duration: 0.039 seconds

Run Settings
    Number of Test Workers: 8
    Work Directory: ...\repos\TestNUnitLite\TestNUnitLite\bin\Debug\net5.0
    Internal Trace: Off

Test Run Summary
  Overall result: Passed
  Test Count: 2, Passed: 2, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2021-10-02 21:13:58Z
    End time: 2021-10-02 21:13:58Z
    Duration: 0.018 seconds

Results (nunit3) saved as ...\repos\TestNUnitLite\TestNUnitLite\bin\Debug\net5.0\TestResult.xml
```
and NUnitLite supports many of the same options as the console. I'm marking this as an answered question, as we already have issues on the NUnit Console not supporting .NET Core, but note that we will still see additional comments on this issue.

**Closed by mikkelbu** 2021-10-02 21:19 UTC
Labels: is:bug, confirm
