### ISSUE TITLE
Only 1 agent running with multiple projects and --process=Multiple

### ISSUE THREAD

**Issue by Matteoz991** [nunit/nunit-console#382] opened 2018-03-05 09:46 UTC
Using a .nunit file to run multiple projects and --process=Multiple will only run one agent process per time while with version 3.6.1 i was able to run one agent per test project.

The command line i'm using is:
nunit3-console InsertAnyPathHere\MyNunitProjFile.nunit --x86 --dispose-runners --process=Multiple

My .nunit file is like this: 
```
<NUnitProject>
  <Settings activeconfig="Release" processModel="Multiple" domainUsage="Default" />
  <Config name="Release" runtimeFramework="net-4.0" binpathtype="Manual">
    <assembly path="folder/folder/folder/MyTestDll.dll" />
    <assembly path="folder/folder/folder/MyTestDll1.dll" />
    <assembly path="folder/folder/folder/MyTestDll2.dll" />
    <assembly path="folder/folder/folder/MyTestDll3.dll" />
    <assembly path="folder/folder/folder/MyTestDll4.dll" />
    <assembly path="folder/folder/folder/MyTestDll5.dll" />
    <assembly path="folder/folder/folder/MyTestDll6.dll" />
    <assembly path="folder/folder/folder/MyTestDll7.dll" />
    <assembly path="folder/folder/folder/MyTestDll8.dll" />
  </Config>
</NUnitProject>
```

I couldnt find any way to run again, as per version 3.6.1, more than one agent per time.

**Comment by ChrisMaddock** [comment] 2018-03-05 10:54
This should be fixed in NUnit Console 3.8 ,as per https://github.com/nunit/nunit-console/issues/116. Please try updating, let us know if this is still a problem.

**Comment by ChrisMaddock** [comment] 2018-03-05 13:13
Actually, this could be a different issue - `--process=multiple` would previously have forced multiple processes.

Can you try: a) updating the the latest console, and b) removing the `--x86` flag, and see if the results are different in either case?

**Comment by Matteoz991** [comment] 2018-03-05 13:45
So.. i've try to update to the latest official release 3.8, and downloading the latest code from git and with both i have only 1 agent running per time.. even without --x86 flag.

I took a look at the source code and i think the problem is because the number of agents running is based on the SubPackages count in TestPackage class but the moment this is verified this count is equal to 1 and the SubPackages from the .nunit file are loaded only after inside the agent itself. I could be wrong but i hope it helps.

**Comment by rprouse** [comment] 2018-03-05 15:03
Thanks for the help @Matteoz991. You are probably right in your analysis, we've seen similar issues before.

**Comment by CharliePoole** [comment] 2018-03-05 19:10
@ChrisMaddock Issue #116 dealt with choosing the correct runner, so multiple processes are used. It didn't deal with how many of those processes would run in parallel, because it was assumed that the normal default of "all of them" would apply.

@Matteoz991 Try using --agents on the command-line to specify how many processes should run at one time.

**Comment by Matteoz991** [comment] 2018-03-06 07:04
@CharliePoole always one.

**Comment by CharliePoole** [comment] 2018-03-06 07:44
@Matteoz991 I think you are right about the subpackage count. Originally, it was used to select the default runner (multiple if > 1) and the number of agents. The fix dealt with the default runner but not the number of agents.

In order to fix the chosen runner, we simply assumed that any project file could have more than one assembly and used multiple. 

In order to fix the number of agents, however, we can't do that because we need to know the actual number of assemblies to be run. TThe package that is currently being examined is not the package for the project but for the command-line itself. The single subpackage is the project and that's what has to be expanded to the second level in order to know how many assemblies are involved. Most likely, this is best handled by postponing the decision about number of agents until after we expand the projects.

**Comment by chrisalbrecht** [comment] 2018-05-11 12:13
Is there any reason that lines 87-88 which were removed here (https://github.com/nunit/nunit-console/commit/ee01734adb0942b66f79ba5f3c4d55a85d7713ea?diff=unified#diff-9f6ecbd64f15202ce4fdb0b5d36ae575L87) can't be restored (or at least moved down after the `case ProcessModel.Multiple` statement)? 

I think the removal of these two lines is the reason for this change in behaviour. Prior to this the `MultipleTestRunner` was being initialized with the .nunit file as the top level TestProject which would result in an agent being invoked per assembly (since an an `ITestEngineRunner` runner would be created for each SubPackage/assembly here: https://github.com/nunit/nunit-console/blob/f8bc46bcd6e81f52e0336d4f171fa899e424b79b/src/NUnitEngine/nunit.engine/Runners/AggregatingTestRunner.cs#L66). 

Now the `MultipleTestRunner` is being initialized with the a .nunit file as a SubPackage only one `ITestEngineRunner`, and therefore a single agent, is invoked for the .nunit file.

**Comment by ChrisMaddock** [comment] 2018-12-22 14:30
Issue confirmed. Interestingly, I see this working as expected (in multiple processes) WITHOUT the explicit ` --process=Multiple` flag.

**Comment by CharliePoole** [comment] 2021-11-10 02:04
@nunit/engine-team Looking for input on this one.

In experiments, I have been able to make this work but I break 81 tests in the process.

The tests, which are broken, are mostly in `MasterTestRunnerTests` and are very tightly specified. For example, there's a test which says if I run a command-line with two assemblies and one project containing another two assemblies, I get a `MultipleTestProcessRunner` with three `ProcessRunners` under it. Now I get four of them, which is what is needed to run all the tests in parallel. In other words, the tests are mostly testing internal structure rather than results. We need tests like that but we probably have too many.

In my view, we should break those kinds of tests and change them to reflect what now actually happens. We could also simply remove a lot of them. Ideally, we should add tests, which test the actual parallel behavior we want to see, but that might be harder than making the change itself.

What do you think?

Charlie

**Comment by rprouse** [comment] 2021-11-14 20:34
@CharliePoole proper tests would be better, but you have a lot on your plate trying to get the release out, so I'd suggest being pragmatic and updating the existing tests.

**Comment by CharliePoole** [comment] 2021-11-14 20:47
@rprouse I'll go with that approach. BTW, I should make clear to all of the @nunit/engine-team that I volunteered to serve as a temporary _Release Manager_ for 3.13, not to take on all the pending issues. I plan to do the release when the (approximate) scheduled date arrives, postponing any issues that aren't done.

**Comment by CharliePoole** [comment] 2021-11-16 16:26
Ready for review by @nunit/engine-team. Fixed by counting leaf nodes in the tree of packages rather than using subpackages. After expansion, each leaf node is by definition an assembly.

At the same time changed the code so that the processor count could be injected from the tests, rather than relying on `Environment.ProcessorCount` and added more tests of the LevelOfParallelism property,

**Closed** 2021-11-17 05:08 UTC
Labels: is:bug, pri:normal, awaiting:review
