### ISSUE TITLE
Some questions on compiling

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/nunit-console#232] opened 2017-05-30 13:40 UTC
I have some questions:
1) why <a href="https://github.com/nunit/nunit-console/blob/e39fc7fed5d122aff26eb7b22b565c35b34a6e2c/src/NUnitEngine/nunit.engine/XmlHelper.cs#L32">this line<a> is not under conditional directive ? I am trying to build this project for .NET framework 4.5, and I don't have v2.0 installed. During compilation it give me an error about Attribute duplication.
2) <a href="https://github.com/nunit/nunit-console/blob/1bea82f0c6511c496fa26e2511b1a31f49cc1f81/src/NUnitEngine/nunit.engine/Extensibility/ExtensionNode.cs#L134">this line</a> give an error
<code>Error CS0618: Warning as Error: `System.AppDomain.CreateInstanceFromAndUnwrap(string, string, bool, System.Reflection.BindingFlags, System.Reflection.Binder, object[], System.Globalization.CultureInfo, object[], System.Security.Policy.Evidence)' is obsolete: `Use an overload that does not take an Evidence parameter' (CS0618) (nunit.engine)</code>
in <a href="https://github.com/nunit/nunit-console/blob/1bea82f0c6511c496fa26e2511b1a31f49cc1f81/src/NUnitEngine/nunit.engine/Drivers/NUnit3FrameworkDriver.cs#L169">some other place</a> it was placed under NET_4_0, but not here.
3) Some more similar errors <a href="https://github.com/nunit/nunit-console/blob/1bea82f0c6511c496fa26e2511b1a31f49cc1f81/src/NUnitEngine/nunit.engine/Services/DomainManager.cs#L67-L75">here</a>

**Comment by rprouse** [comment] 2017-05-30 13:55
> why this line is not under conditional directive ?

The NUnit engine and console are both compiled .NET 2.0 so that they can run test under the .NET Framework 2.0 and onwards. If they were compiled .NET 4.5, they could run .NET 2.0 tests, but only under .NET 4.5. There are some different behaviors in different versions of the .NET Framework (and Mono), so it is important to some users to run their tests under the framework they are targeting, not under a newer framework.

Your remaining errors are also because you are attempting to compile with a newer target than the project specifies.

If you are compiling this project under Mono, you need to the .NET 2.0 targets installed. Unfortunately, recent versions of Mono do not ship with those targets, so you need to install Mono 3.x and upgrade to latest to get them.

**Comment by rprouse** [comment] 2017-05-30 13:57
The various `NET_4_0` defines are left over from when that code was shared with the NUnitLite runner and could be removed in this project as they are unused.

**Comment by ArsenShnurkov** [comment] 2017-05-30 14:00
I don't want to install v2.0 (because I already have 4.5 installed). Please improve this code to be able to build with 4.5+. I think that this my use case is valid.

**Comment by CharliePoole** [comment] 2017-05-30 14:59
@rprouse maybe we should remove all the leftover conditionals since they cause confusion.

**Comment by ArsenShnurkov** [comment] 2017-05-30 15:39
I will apply patches anyway, so the is no difference to keep conditionals, or not

**Comment by CharliePoole** [comment] 2017-05-30 16:15
Conditionals that are never true may be confusing to a lot of people. :smile:

**Comment by CharliePoole** [comment] 2017-05-30 16:16
OTOH if we wanted to actually __support__ building for 4.5, adding proper conditionals would make sense. I'm thinking about this because I may create a fork for building on Mono.

**Comment by ArsenShnurkov** [comment] 2017-05-31 00:24
https://stackoverflow.com/questions/3436526/detect-target-framework-version-at-compile-time
https://stackoverflow.com/questions/4824732/seeking-alternative-to-appdomain-createdomainstring-evidence-due-to-obsolete

**Comment by ArsenShnurkov** [comment] 2017-05-31 13:04
@CharliePoole
https://github.com/ArsenShnurkov/nunit-console/commit/ee90d9a5116d7efa3862323e985a546d728de86f

**Comment by rprouse** [comment] 2017-05-31 16:53
@ArsenShnurkov I believe that the NET_2_0 needs to be defined in the CSPROJ files. Most of our developers use Visual Studio to build, so your changes would break the build for them.

**Comment by ArsenShnurkov** [comment] 2017-05-31 17:06
Earlier you told me 2 things (and very insist on them, like force me to explaining why i want them):
1) developers (like me) should never-never build something themselves (they should use prepackaged binaries); So your Visual Studio developers will use .nuget packages and be happy with your 2.0 built binaries.
2) developers (like me) should never-never build without Caja (they should your the process provided by your team).

Now you say the totally opposite. Somehow YOUR developers don't use Caja and they BUILD instead of using of readymade binary .nuget packages. Where is the logic?

I already wrote above, that NET_2_0 can be passed from Caja through .csproj into c# compiler.
(with msbuild /p:... command line parameter, and a slightly changed .csproj
see https://stackoverflow.com/questions/479979/msbuild-defining-conditional-compilation-symbols)

**Comment by rprouse** [comment] 2017-05-31 17:17
I mean the developers on our team use Visual Studio to work and debug while they are working on the console and engine. Building in Visual Studio needs to continue to work for the people who work on NUnit.

Before we check in, we also ensure that everything builds correctly with Cake and that all tests pass. We also only use the Cake build to produce binary packages that get distributed.

When I said that developers shouldn't have to build themselves, I was referring to people who use the NUnit Console and Engine. We provide binaries that will run on .NET and Mono that can be downloaded as a ZIP file, an MSI installer for Windows and as NuGet packages.

**Comment by ArsenShnurkov** [comment] 2017-05-31 17:28
The change of
#if NET_2_0
to
#if !NET_4_0
will keep current 2.0 code. Is this the only thing which stop you from accepting such variant?

**Comment by CharliePoole** [comment] 2017-05-31 18:54
@ArsenShnurkov You keep closing and re-opening this. However, you brought up something which I feel we need to decide, so please don't close it again even if you have lost interest.

It's kind of like when you report a crime but then want the police to forget it. They generally won't. 😄

**Comment by ArsenShnurkov** [comment] 2017-05-31 18:57
1) yes, team should support build on 4.0+, because there is such use case - users of mono on linux, where thereis no 2.0.
2) no, you don't need to support build. Building is the work of distributions maintainers.
3) i don't know abount windows, because don't have it

I closed this, because decide to provide PR later

**Comment by CharliePoole** [comment] 2017-05-31 19:20
We do our general discussion on issues, code discussion usually on PRs. If you do a PR, use "Fixes #" on it to point to this.

About your points...
1. We are already discussing this in another issue with respect to the framework. We will probably abandon use of the obsolete profiles but haven't done it yet. While we still support framework build with the 2.0 profile, I think we also have to support the runner.

2. I think you are right for those who use the version from the distro. Others have asked us to provide newer binary packages than what their distro has - not GenToo, obviously.

3. That must be very nice. :smile:

**Comment by CharliePoole** [comment] 2017-05-31 19:29
@nunit/core-team @nunit/engine-team 

We marked this as a question and answered it. However, I'd like to leave it as a question for ourselves, possibly leading to a feature at some point. Really, a series of questions...

1. Should we build and test using .NET 4.5 for the engine and runner?

2. Should we package the engine and runner for 4.5.

3. Should we distribute that package (if we build it) for linux only?

4. Should we distribute __actual__ packages for any distro, e.g. `.deb` or should we leave that for other people?

Background for this is that I have always felt we under-support linux, which is my preferred platform. Also, I'm toying with the idea of going full-on linux in my own open source work after I transition away from the NUnit team. Conceivably, I could do that within the project but my sense is that the team's ideas about what we should support may be diverging from my own and I'd like to be free to do my own thing and also get out of the way of the direction you guys are going to be taking.

**Comment by ChrisMaddock** [comment] 2017-05-31 21:04
Tricky one.

- I don't think we should merge any conditionals, without the CI and infrastructure to test for regression. That adds overhead.
- I'm feel quite aware that this is the first request for .NET 4.5 build in 18 months since the 3.0 release.
- Is it no longer possible to install the components to build pre-.NET 4.5 code on mono? This feels like a big oversight on their part - everything I work with is pre-4.5.
- Linux packaging seems so much more fragmented than Windows - it feels like we'd need a different maintainer for each package! As a general concept, I'm a fan of the software author also controlling packaging and distribution - but that require a willing package maintainer - and it's not something I could offer to do.

If we can build and push (any) Linux related package in an automated fashion, which can be contributed by someone knowledgeable, and require little future maintenance, I don't see the harm. I imagine @rprouse may have more to say on this however, as the man who does the releases.

Anything which requires more, e.g. re-targeting the code, I think we need to consider demand. (And that's not to rule it out - I have no idea what the demand for a gentoo package is!) As ever, we need to work out where our limited resources are best spent.

**Comment by ChrisMaddock** [comment] 2017-05-31 21:10
What are we actually looking to support with this change. Building on the latest versions of mono, or a particular packaging method?

I believe it's the former, and I'd be slightly more inclined to make changes for that.

**Comment by CharliePoole** [comment] 2017-05-31 23:45
Well, working backward on your two notes, we aren't looking to support anything - it's a question. :smile:

But the answer may have us supporting something!

We target 2.0, 3.5, 4.0 and 4.5 on Mono. The first three have actually not existed for quite a while. This was in no way an oversight on the part of the mono folks. It was discussed quite a bit and is a deliberate design decision. On Windows, you may only have 2.0 installed, in which case you have to have a 2.0 build. On Mono, this has not been the case for many years. Very early on, Mono combined what they used to call "profiles" (2.0, 3.5, etc.) into a single set of assemblies. With that change, it was no longer possible to have __only__ 2.0, for example. If you had mono at all, you had all the profiles. What they have done recently is to eliminate the ability to __act__ as if you only had 2.0 by targeting it. If you are a pure mono guy, this makes total sense and it's the existence of separate 2.0, 3.5, etc. runtimes that doesn't make sense.

To me, that all means we have to change. For a long time we resisted because we wanted to be able to run with old versions of mono. But those versions are now downright ancient. Even the relatively old mono releases supplied with the more conservative distros are purely 4.5+ equivalent.

So, at a minimum, I think we have to stop targeting anything but 4.5 on Mono. Whether we do that with a 4.5 build or a mono build is probably the question to ask next.

We don't have to change our NuGet packaging, since only 4.5 will ever get picked up on modern monos.

At a maximum, we might want to start producing some native packages for various distributions. Traditionally, in the Linux environment, this is __not__ done by the package authors, so your inclination to do it yourself may not be understood by the packagers. Generally, the packagers for a distro are creating a whole bunch of packages to include in that distribution. If they decide to include NUnit, then they package it. We can do (or maybe I can do post-NUnit) a few things:
* Provide packagers with a good starting point. That probably means a good linux build script that meets their standards (which differ for each distribution).
* Do some packaging in some formats for new stuff that has not yet made it into the distribution. Generally, that would involve work by somebody who knows the distribution in question. I plan to work on a .deb package, which would handle Debian and its derivatives. I planned to do this myself because the idea of the NUnit Project maintaining deb packages has been talked about before without generating much enthusiasm.

This has been sort of a brain dump! Hope it answered most of your questions.

**Comment by rprouse** [comment] 2017-06-01 00:08
We should also throw into the mix the fact that Mono.Cecil has stopped supporting .NET 2.0, so we cannot take any updates or fixes to Mono.Cecil if we continue to target 2.0. At some point, we are going to be forced to move to .NET 3.5 as a minimum if we need any of the Mono.Cecil updates. Personally, I don't see an issue with running your .NET 2.0 tests under 3.5 despite the minor differences, but I may be in a minority 😄

**Comment by ChrisMaddock** [comment] 2017-07-02 12:12
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/nunit/nunit-distribution/issues/18](https://trello.com/c/waKXUs4E/1-https-githubcom-nunit-nunit-distribution-issues-18)

**Comment by ChrisMaddock** [comment] 2020-09-01 18:13
Closing this issue. This isn't a scenario we support at this point in time.

**Closed by ChrisMaddock** 2020-09-01 18:13 UTC
Labels: is:question
