### ISSUE TITLE
NUnit.Engine.TestEngine with a version greater than or equal to 3.0 not found

### ISSUE THREAD

**Issue by AhlamJelti** [nunit/nunit-console#945] opened 2021-05-07 22:13 UTC
i use NUnit.Engine.APi to run Test From other assembly .. but i had this error "'NUnit.Engine.TestEngine with a version greater than or equal to 3.0 not found'" when i install package Nunit.Engine i don't have this error but still the code coudn't Load teh assembly that i specified by path 

        ITestEngine engine = TestEngineActivator.CreateInstance();
        TestPackage package = new TestPackage(@"PaTH\TestScenariotSpecflow.dll");
        ITestRunner runner = engine.GetRunner(package);

        // Run all the tests in the assembly
        XmlNode testResult = runner.Run(listener: null, TestFilter.Empty);
the program is excuted but i couldn't run the tests also if i use incorrect path i don't have any message error .
PS : i wanna run some scenario created in gherkin i used specflow + NUnit

**Comment by CharliePoole** [comment] 2021-05-07 22:24
If you don't install the engine package, then you don't have the engine. That's normal.

The failure to load and run your tests could be a bug or it could be something you are doing wrong. To figure it out we would need some more information about how your project is set up.  The assembly, which specflow creates, is the one you must add to the  test package. You must ensure that the necessary dependencies, including the NUnit framework, are all available.

Also, please tell us what runtime you target. .NET Core and .NET Framework work a bit differently.

**Comment by CharliePoole** [comment] 2021-05-08 01:27
Are your tests able to run using the NUnit console runner?

**Comment by AhlamJelti** [comment] 2021-05-08 18:15
@CharliePoole Now i use this code 
Process p = new Process();
			// Redirect the output stream of the child process.
			p.StartInfo.UseShellExecute = false;
			p.StartInfo.RedirectStandardOutput = true;
			p.StartInfo.FileName = "C:\\Users\\ahjelti\\source\\repos\\Test_Auto\\packages\\NUnit.ConsoleRunner.3.10.0\\tools\\nunit3-console.exe";
			//p.StartInfo.FileName = "D:\\VS19\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe";
			p.StartInfo.Arguments = "C:\\Users\\ahjelti\\source\\repos\\Test_Auto\\TestScenariotSpecflow\\bin\\Debug\\net461\\TestScenariotSpecflow.dll";
			//p.StartInfo.Arguments = "--where cat == ContactCreation";
			p.StartInfo.ErrorDialog = true;
			p.Start();
			// Do not wait for the child process to exit before
			// reading to the end of its redirected stream.
			// p.WaitForExit();
			// Read the output stream first and then wait.
			string output = p.StandardOutput.ReadToEnd();
			p.WaitForExit();

- It works , should i do another thing   ?

**Comment by CharliePoole** [comment] 2021-05-08 18:29
@AhlamJelti Oh... I didn't mean use it programmatically, I only wondered if your tests work using it in the normal way, i.e. from the command-line. However, even though you did something much more complicated, you have succeeded in proving that the tests themselves are not the cause of the problem. :smiley: 

So... to go back to the original approach of using the engine alone (which is a good approach)...

1. Is the engine (nunit.engine.dll) located in the same directory as your executing program?
2. Are it's dependencies (nunit.engine.core.dll, testcentric.engine.metadata.dll) present as well?
3. Is the path set into the TestPackage the full and correct path to the test assembly?

**Comment by AhlamJelti** [comment] 2021-05-08 19:06
Yes the dependencies are in' \ConsoleApp4\bin\Debug' in the same directory of my project " ConsoleApp4" . and yes it's the correct path to the test assembly . but what i wanna told you sir in the code i refference to nunit.engine not nunit.engine.api i mean to " Using NUnit.Engine " 

using NUnit.Engine;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            ITestEngine engine = TestEngineActivator.CreateInstance();
            TestPackage package = new TestPackage("C:\\Users\\ahjelti\\source\\repos\\Test_Auto\\TestScenariotSpecflow\\bin\\Debug\\net461\\TestScenariotSpecflow.dll");
            ITestRunner runner = engine.GetRunner(package);

            // Run all the tests in the assembly
            XmlNode testResult = runner.Run(listener: null, TestFilter.Empty);
        }
    }
}
i do it correctly ?

**Comment by CharliePoole** [comment] 2021-05-08 22:20
Short: Yes,  that's correct. 

Longer: Yes, because "Using" is not what is meant by reference. Using is just part of the C# language and the statement will give an error if you don't have a proper reference. Your program compiles, therefore all your references are correct. In fact, there is no Api namespace for you to  specify. nunit.engine, nunit.engine.core and nunit.engine.api are based in the NUnit.Engine namespace.

BUT...

That's only when you compile. It says nothing about whether the assemblies are all present when you run. That's why we have to examine the directory _in which you run the tests_ to see if all the needed parts are there.

Let's be more specific.

1. What dlls are present in the `C:\Users\ahjelti\source\repos\Test_Auto\TestScenariotSpecflow\bin\Debug\net461` directory?
2. When you say "I can't run the tests" exactly what do you mean? What happens when you execute?

Charlie

**Comment by AhlamJelti** [comment] 2021-05-09 02:52
Thank u For answer , there is a lot of dlls in this directory : 
Some of them : 
Nunit.engine.api.dll,Nunit.engine.core.dll, Nunit.engine.dll, nunit.framework.dll, TestScenariotSpecflow.dll,WebDriver,Cucumber.Messages.dll,Gherkin.dll.BoDI.dll,Google.Protubuf.dll,netstandar.dll; Newtonsoft.json.dll,NUnit3.TestAdapter,TechTalk.Specflow.dll..
2 - i add Console.WritLine("OK") at the end of the code .. so i see the " OK" in The Console but Nothing Change , The Code should create  instance of ChromeDriver and  Run The test   but it's not the case and i don't have any error message and if i write incorrect path also i see the same result .

**Comment by CharliePoole** [comment] 2021-05-09 03:07
Were you expecting the engine to produce some kind of output? That's not what it does. It just runs tests, sends events and returns a result. You aren't handling events and you don't do anything with the result. I guess your tests are probably running OK!

**Comment by CharliePoole** [comment] 2022-01-13 09:46
I believe this has been answered, so I'm closing the issue. We'll still see and respond to any further comments posted here.

**Closed by CharliePoole** 2022-01-13 09:46 UTC
Labels: Bug, Needs Confirmation
