### ISSUE TITLE
Nunit-Console exe 3.11.1 throws an exception - NUnit.Engine.NUnitEngineUnloadException : Exception encountered unloading application domain

### ISSUE THREAD

**Issue by hemrajpatil1** [nunit/nunit-console#840] opened 2020-12-01 08:28 UTC
We are running NUnit console from Jenkins job and nunit is producing results correctly it seems but at end nunit throws an exception - NUnit.Engine.NUnitEngineUnloadException : Exception encountered unloading application domain and that stuck the Jenkins job till we abort the job.

Nunit-console.exe version - 3.11.1
Command - "nunit3-console.exe" "Solidworks.DevTests.dll"  "--result:Solidworks.DevTests.xml" --labels=Before --inprocess --trace=Debug

![image](https://user-images.githubusercontent.com/75294002/100712758-48f70480-33d9-11eb-8724-886e5c0e4c54.png)
![image](https://user-images.githubusercontent.com/75294002/100712888-7cd22a00-33d9-11eb-9e46-0cc99a624e1f.png)

Attached internal trace logs, TestResult.xml and complete console logs,

[ConsoleLogs.txt](https://github.com/nunit/nunit-console/files/5621178/ConsoleLogs.txt)
[InternalTrace.12672.log](https://github.com/nunit/nunit-console/files/5621179/InternalTrace.12672.log)
[InternalTrace.12672.Solidworks.DevTests.dll.log](https://github.com/nunit/nunit-console/files/5621180/InternalTrace.12672.Solidworks.DevTests.dll.log)
[Solidworks.DevTests.xml.txt](https://github.com/nunit/nunit-console/files/5621185/Solidworks.DevTests.xml.txt)

**Comment by ChrisMaddock** [comment] 2020-12-01 22:06
Hi @hemrajpatil1. 

This all looks like correct behaviour from the console. The exception message is displayed as a warning that your tests can't be unloaded correctly, but shouldn't affect the exit code or cause a hang. In this case, I would expect the error message to be shown, and the console to exit with 59, based on the number of failed tests. You can see the code for that here:

https://github.com/nunit/nunit-console/blob/f570ba81e1a3b7087110b854769048c25f15ef23/src/NUnitConsole/nunit3-console/ConsoleRunner.cs#L248-L263

I expect the reason you Jenkins job is hanging is the same reason that the test can't be unloaded - some resources which aren't correctly disposed of. I'd suggest digging in to that and trying to pinpoint the test that's causing the issue, maybe by bisecting your test assembly. You can see the sort of things that can prevent clean app domain unload [here](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.unload?view=net-5.0#remarks), as an idea of the sort of things you should be looking for.

**Comment by ChrisMaddock** [comment] 2020-12-27 12:22
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2020-12-27 12:22 UTC
Labels: confirm, is:bug
