### ISSUE TITLE
Object agent is not disposed

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit-console#102] opened 2016-10-20 08:57 UTC
Object agent is not disposed.
Is it OK?

``` c#
                RemoteTestAgent agent = new RemoteTestAgent(AgentId, Agency, engine.Services);

                try
                {
                    if (agent.Start())
                    {
                        log.Debug("Waiting for stopSignal");
                        agent.WaitForStop();
                        log.Debug("Stop signal received");
                    }
                    else
                        log.Error("Failed to start RemoteTestAgent");
                }
                catch (Exception ex)
                {
                    log.Error("Exception in RemoteTestAgent", ex);
                }
```

**Comment by CharliePoole** [comment] 2016-10-20 11:23
What method is this?

**Comment by constructor-igor** [comment] 2016-10-20 11:44
file \nunit-console\src\NUnitEngine\nunit-agent\Program.cs
class NUnitTestAgent

**Comment by CharliePoole** [comment] 2016-10-20 11:48
Solution to this is not so simple... I'll look at it in a day or two. The problem is that the wait does not end until the point where the engine is already disposed. The whole cycle of creation/disposal is too confusing.

**Comment by constructor-igor** [comment] 2016-10-20 12:08
If a solution is not so simple, let's reject the issue.

actually, Dispose calls RemoteTestAgent.Stop().
```c#
        public override void Stop()
        {
            log.Info("Stopping");
            // This causes an error in the client because the agent 
            // database is not thread-safe.
            //if (agency != null)
            //    agency.ReportStatus(this.ProcessId, AgentStatus.Stopping);


            stopSignal.Set();
        }
```

**Comment by CharliePoole** [comment] 2016-10-20 17:53
Exactly. But the life cycle is not clear, as is proven by the fact that it confused you. :-)

I'll look through all the related calls on the weekend. It may be that we only need some comments to make it clear.

**Comment by ChrisMaddock** [comment] 2020-09-01 18:08
Closing this, as this piece of code no longer exists in this form. 🙂

**Closed by ChrisMaddock** 2020-09-01 18:08 UTC
Labels: is:question, is:refactor
