### ISSUE TITLE
Nunit3-console fails to run tests for native windows 32 bit dll when run on Windows x64 OS

### ISSUE THREAD

**Issue by venkatasprayaga** [nunit/nunit-console#677] opened 2019-08-26 20:26 UTC
Please help us resolve this issue: Nunit3-console fails to run tests for native windows 32 bit dll when run on Windows x64 OS.

Below is the command output fails on Windows 64 but succeeds when run in Windows x86 machine:
c:\Tests>nunit3-console.exe --process=Separate --x86 --workers=1 .\<<unmanageddll>>.dll
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
Monday, August 26, 2019 3:47:29 PM

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17763.0
  CLR Version: 4.0.30319.42000

Test Files
    .\<<unmanageddll>>.dll

Errors, Failures and Warnings

1) Invalid : <<unmanageddll>>.dll
Could not load file or assembly '<<unmanageddll>>.dll' or one of its dependencies. The specified module could not be found.

Run Settings
    ProcessModel: Separate
    RunAsX86: True
    DisposeRunners: True
    WorkDirectory: c:\Tests
    NumberOfTestWorkers: 1
    ImageRuntimeVersion: 4.0.30319
    ImageRequiresX86: True
    ImageRequiresDefaultAppDomainAssemblyResolver: False

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-08-26 19:47:29Z
    End time: 2019-08-26 19:47:30Z
    Duration: 0.779 seconds

Results (nunit3) saved as TestResult.xml

c:\Tests>

**Comment by ChrisMaddock** [comment] 2019-08-28 09:42
I would also be suspicious of whether the `-x86` and `-process=Separate` flags work together. (They should, but you may be encountering a bug.)

`-process=Separate` is the default, if you're just running a single test assembly. If you remove that flag, does it help at all?

**Comment by ChrisMaddock** [comment] 2019-10-09 21:09
I've attempted to test this, but been unable to reproduce it. I used the same command line, and the simple test below to check an x86 process was being created.

```
        [Test]
        public void Test1()
        {
            Assert.That(Environment.Is64BitProcess, Is.False);
        }
```

@venkatasprayaga - without further information, I'm afraid there's nothing we can do here. I'm closing this issue for now, please feel free add any further information you can to reproduce this, and we can reopen.

**Closed by ChrisMaddock** 2019-10-09 21:09 UTC
Labels: confirm
