### ISSUE TITLE
Remove nunit-console-with-extensions Choco packaging

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-console#805] opened 2020-08-01 18:19 UTC
This looks to be something legacy which hasn't been updated in several releases. I've asked Charlie Poole/Rob Prouse if they can remove it from the choco site, as maintainers. We should also remove the packaging from the repo here.

https://www.chocolatey.org/packages/nunit-console-with-extensions

**Comment by CharliePoole** [comment] 2020-08-01 20:11
Don't we still do the NuGet package that includes extensions? Originally, the chocolatey packages were intended to give Chocolatey users the same functionality that the NuGet packages give to NuGet users.

**Comment by CharliePoole** [comment] 2021-09-09 15:34
AFAIK, maintainers can't delete packages. I have asked the chocolatey admins to remove the entry for this package.

**Comment by CharliePoole** [comment] 2021-09-10 00:47
Note from one of the Chocolatey admins...

> there isn't generally a way to completely delete packages as such. As this package never has had a version approved it won't show up in any search results, so the net effect is much the same as if it never existed.

I've confirmed that I can only get to the package by knowing the url. That seems good enough to me. Doing it "right" would mean uploading a new package and then deprecating it, which seems like to much trouble.

**Comment by CharliePoole** [comment] 2021-12-01 17:05
Closing without action

**Closed by CharliePoole** 2021-12-01 17:05 UTC
Labels: good first issue, is:build, pri:normal, help wanted
