### ISSUE TITLE
Cannot get configfile parameter to work

### ISSUE THREAD

**Issue by Roemer** [nunit/nunit-console#1173] opened 2022-03-09 16:42 UTC
I am trying to get a test running that uses an `app.config` file for values.

The project is very simple: Just a .NET 5.0 library project with an app.config with connection strings and a test that tries to read them.
I've also attached that project here: [TestLibrary.zip](https://github.com/nunit/nunit-console/files/8216455/TestLibrary.zip)

The project can be compiled with `dotnet build TestLibrary`
and then when I try to run the test with `nunit3-console.exe .\TestLibrary\TestLibrary.csproj --configfile=.\TestLibrary\app.config` it still cannot find the connection strings. Doesn't matter what path I define (relative to nunit, relative to the test library, absolute), always the same.

What am I doing wrong?

**Comment by CharliePoole** [comment] 2022-03-09 20:06
I suspect that the error may be in the VS Project Loader extension rather than the console or engine. To find out, please try running the test assembly directly, rather than the `.csproj` file.

**Comment by Roemer** [comment] 2022-03-11 07:44
I tried with using the dll instead of the csproj (`.\TestLibrary\bin\Debug\net5.0\TestLibrary.dll`) but with the same result, the config seems not to be loaded.

**Comment by pakinvadim** [comment] 2022-12-19 12:08
probably this should help http://charliepoole.org/technical/how-nunit-finds-config-files.html

**Comment by gfody** [comment] 2023-03-09 00:28
we're stuck on this as well. after migrating our tests project from net48 to net6.0 tests that access ConfigurationManager are being directed to `C:\BuildAgent\tools\NUnit.Console.3.16.2\bin\agents\net6.0\nunit-agent.dll.config` for some reason, previously they would read the file from the executing assembly's directory

**Comment by nickkfwong** [comment] 2023-04-28 08:03
I have the same issue, is there any workaround for it?

**Comment by kopfsick** [comment] 2024-06-04 12:05
Any update on this?

**Comment by CharliePoole** [comment] 2024-10-04 00:58
If anyone is still monitoring this old issue, please try using the console runner in our myget feed, version 3.18.3-dev00006.

**Comment by CharliePoole** [comment] 2024-11-27 16:42
Closing due to lack of further feedback and no repro case.

**Closed** 2024-12-02 00:00 UTC
Labels: Not Reproducible

**Comment by ketchup201** [comment] 2025-04-03 21:37
I believe I was able to reproduce the issue. I created a small test assembly and when I attempt to use nunit3-console, 13.19.2, I am finding that an unexpected configuration file is being used.

### **UnitTest1.cs**
```
        [Test]
        public void Test1()
        {
            // using Microsoft Test Explorer, this file path is
            // bin\Debug\net8.0\testhost.dll.config

            // using nUnit console, this file path is:
            // bin\Debug\net8.0\nunit3-console.dll.config

            var conf = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
            Console.WriteLine($"file path of configuration file is: {conf.FilePath}");
            Assert.Pass();
        }
```
### **nUnitSample.config**
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<appSettings>
		<add key="parameter" value="abcd"/>
	</appSettings>
</configuration>
```
### **nUnitSample.nunit**
```
<NUnitProject>
	<Config name="Debug" binpathtype="Auto" runtimeFramework="8.0" configfile="./nUnitSample.config">
		<assembly path=".\bin\Debug\net8.0\nUnitSample.dll" />
	</Config>
</NUnitProject>
```
### **Output**
```
D:\src2\csharp\nUnitSample>.\NUnit.Console-3.19.2\bin\net8.0\nunit3-console.exe nUnitSample.nunit --config=Debug
NUnit NetCore Console Runner 3.19.2 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
Thursday, April 3, 2025 2:31:56 PM

Runtime Environment
   OS Version: Microsoft Windows 10.0.22621
  Runtime: .NET 8.0.14

Test Files
    nUnitSample.nunit

file path of configuration file is: D:\src2\csharp\nUnitSample\bin\Debug\net8.0\nunit3-console.dll.config

Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2025-04-03 21:31:56Z
    End time: 2025-04-03 21:31:56Z
    Duration: 0.219 seconds

Results (nunit3) saved as TestResult.xml
```
I expected the configuration file path to be **D:\src2\csharp\nUnitSample.config** as set in the **configfile** attribute within the  **nUnitSample.nunit** file.

I could easily have an incorrect assumption, but this is the way we've been doing it for years using .NET Framework without issue. Is the configfile no longer supported, is there a bug, or am I doing something wrong??
