### ISSUE TITLE
Assembies are loaded incorrecty

### ISSUE THREAD

**Issue by kemsky** [nunit/nunit-console#1361] opened 2023-09-01 19:40 UTC
I got many random issues trying to run tests using console runner, but finally I found a reason.

Basically, bin folder contains blank dll ("\bin\Debug\net7.0\Microsoft.Data.SqlClient.dll"), which should be resolved to a more specific dll in the runtime folder (something like "bin\Debug\net7.0\runtimes\win\lib\net6.0\Microsoft.Data.SqlClient.dll") but it does not happen.

See full discussion here: https://github.com/dotnet/SqlClient/issues/2064, there is a detailed explanation.

There are many many other cases like this.

This is sample repo: https://github.com/kemsky/nunit-bug

**Comment by kemsky** [comment] 2023-09-01 19:52
I see that nunit4-netcore-console.exe somehow works, but how can I get it without building myself? There is no msi package, no dotnet tool, no release.

**Comment by OsirisTerje** [comment] 2023-10-16 19:32
Sorry for responding late on this.  We have several of the same issues. 
Which version of the console are you using?

**Comment by kemsky** [comment] 2023-10-16 20:26
@OsirisTerje, I've provided sample repo, there you can find all version information.

**Comment by OsirisTerje** [comment] 2023-10-16 20:34
<PackageReference Include="NUnit.ConsoleRunner" Version="3.16.3" GeneratePathProperty="true" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />

You're using both these together, they don't match.  See information in docs.nunit.org, under the adapter.

**Comment by manfred-brands** [comment] 2023-10-17 08:52
@kemsky I cloned your repo and cannot reproduce an error. Both `dotnet test` and `dotnet msbuild -t:RunTests` run fine.

I also do see the `runtimes` folder under `bin`.

**Comment by kemsky** [comment] 2023-10-17 14:52
@manfred-brands, it seems that some lower level dependency has been upgraded since I originally posted this bug which was 1,5 months ago. I can no longer reproduce it using original sample, but full test suite still fails with the same kind of errors.

 `dotnet-trace collect --providers Microsoft-Windows-DotNETRuntime:4`  shows that different assemblies are loaded, it loads `Microsoft.Extensions.Caching.Memory` from program files/dotnet/shared/asp instead of local version in the bin folder.

dotnet test --no-build works on the very same binaries.

So problem is still there, but there is no way to reproduce it easily.

@OsirisTerje, I removed `NUnit3TestAdapter` - makes zero difference.

**Comment by kemsky** [comment] 2023-10-17 15:15
@manfred-brands, original sample still fails when use use standalone runner:

```
NUnit Console 3.16.0 (Release)
Copyright (c) 2022 Charlie Poole, Rob Prouse
17 october 2023  15:13:32
```

**Comment by OsirisTerje** [comment] 2023-10-17 15:41
@kemsky You can try to upgrade to 3.16.3, then you at least get the latest changes there.

**Comment by CharliePoole** [comment] 2024-06-05 15:11
@kemsky Not clear which standalone runner you are using. There are, unfortunately, two different runners which display the same header information. What package did you install?

**Comment by CharliePoole** [comment] 2024-09-19 01:08
@kemsky I believe this issue is fixed by significant changes in how we locate dependencies in the latest dev build. Can you try to confirm that by using the latest from our MyGet feed? Meanwhile, I'll add your example solution to our test suite.

**Closed** 2024-09-30 14:45 UTC
Labels: Bug, Not Reproducible
