### ISSUE TITLE
Nunit3 Console throws System.Runtime.Remoting.RemotingException : Tcp transport error

### ISSUE THREAD

**Issue by vegesnacreativeworks** [nunit/nunit-console#676] opened 2019-08-23 11:17 UTC
am trying to run the Nunit3 test using Nunit 3.10 Console runner. i am getting below error.

Error :
System.Runtime.Remoting.RemotingException : Tcp transport error.
----> System.Runtime.Remoting.RemotingException : Connection closed
--RemotingException
Tcp transport error.
Server stack trace:
at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.ReceiveMessageStatus (System.IO.Stream networkStream, System.Byte[] buffer) [0x00017] in :0
at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, System.Runtime.Remoting.Channels.ITransportHeaders& responseHeaders, System.IO.Stream& responseStream) [0x0005e] in :0
at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg) [0x00066] in :0

Exception rethrown at [0]:
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, System.Runtime.Remoting.Messaging.IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x0014d] in <7a62ef3b49f14d16b21221b9b5a4792c>:0
at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr)
at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent.Run(NUnit.Engine.ITestEventListener,NUnit.Engine.TestFilter)
at NUnit.Engine.Runners.ProcessRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00025] in :0
RemotingException
Connection closed
at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.StreamRead (System.IO.Stream networkStream, System.Byte[] buffer, System.Int32 count) [0x00011] in :0
at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.ReceiveMessageStatus (System.IO.Stream networkStream, System.Byte[] buffer) [0x00000] in :0

i am using below sample command to run my unit tests
/mono /nunit-console-runner.3.10.0/tools/nunit3-console.exe /pathtodl/test.dll --trace=Verbose -test=Namespace.TestSmaple -output=outputfilepath -result=pathtoxml

my Csproject is build using Nunit 3.10.0 and XmarinUItest 3.0.3 version.

Pacakge information
 

Internal StackTrace
15:37:17.887 Error [ 1] ProcessRunner: Failed to run remote tests Tcp transport error.
15:37:17.897 Info [ 1] ProcessRunner: Unloading
15:37:18.932 Warning [ 1] ProcessRunner: Failed to unload the remote runner. Tcp transport error.
15:37:18.932 Error [ 1] ProcessRunner: System.Runtime.Remoting.RemotingException : Tcp transport error.
----> System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.
----> System.Net.Sockets.SocketException : Connection reset by peer
15:37:18.932 Error [ 1] ProcessRunner: --RemotingException
Tcp transport error.

Target Framework in the Csproject file is
v4.6.1

Additional Details:
Runtime Environment
OS Version: MacOSX 17.7.0.0
CLR Version: 4.0.30319.42000

Could you pls help me whether Nunit3 console runner works for Xamarin UI tests(3.0.3) version.

**Comment by ChrisMaddock** [comment] 2019-08-23 11:49
Please can you add the flag `--inprocess`, and see what error message you get then? Thanks

**Comment by vegesnacreativeworks** [comment] 2019-08-23 12:13
HI Chirs.. after adding the --inprocess flag i am not getting any errors in the Internal Trace Log. But still my tests are not running.

i am using below sample command to run the tests. (Not given the test name info etc)
mono  /nunit-console-runner.3.10.0/tools/nunit3-console.exe /pathtodll --trace=Debug --inprocess --test=Namespace.TestSmaple —output=outputfilepath —result=pathto.xml;format=nunit3

**Termianl shows below info**
Runtime Environment
   OS Version: MacOSX 17.7.0.0 
  CLR Version: 4.0.30319.42000

Test Files
   —— Dll info ——

Test Filters
    Test: —test info—

Now i am not getting any of the test status information in the Terminal. Below info is not displayed after giving --inprocess flag.
Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-08-23 11:56:10Z
    End time: 2019-08-23 11:56:12Z
    Duration: 2.233 seconds

**Comment by ChrisMaddock** [comment] 2019-08-23 12:30
Did you check both log files for an error? The log file which contains your assembly name should show which test was running at the time of the crash, if you remove that test, do things run seccessfully?

**Comment by vegesnacreativeworks** [comment] 2019-08-26 05:05
Hi Chris..

i have checked the log file which contains my dll. It does't show any of my current running test info. Even before that itself my execution is aborted.

PFB logs for the same.

InternalTrace: Initializing at level Debug
13:12:46.152 Debug [ 6] DefaultTestAssemblyBuilder: Loading /user/Mytest.dll in AppDomain test-domain-
13:12:46.228 Debug [ 6] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
13:12:46.229 Debug [ 6] DefaultTestAssemblyBuilder: Found 83 classes to examine
13:12:46.308 Debug [ 6] DefaultTestAssemblyBuilder: Found 36 fixtures with 74 test cases
13:12:46.365 Info  [ 6] DefaultTestAssemblyRunner: Running tests
13:12:46.373 Info  [ 6] Dispatcher: Initializing with 8 workers
13:12:46.374 Debug [ 6] WorkShift: Parallel shift adding queue ParallelQueue
13:12:46.374 Debug [ 6] WorkShift: Parallel shift adding queue ParallelSTAQueue
13:12:46.374 Debug [ 6] WorkShift: NonParallel shift adding queue NonParallelQueue
13:12:46.374 Debug [ 6] WorkShift: NonParallelSTA shift adding queue NonParallelSTAQueue
13:12:46.374 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#1
13:12:46.374 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#2
13:12:46.375 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#3
13:12:46.375 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#4
13:12:46.375 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#5
13:12:46.375 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#6
13:12:46.375 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#7
13:12:46.375 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelWorker#8
13:12:46.375 Debug [ 6] WorkShift: Parallel shift assigned worker ParallelSTAWorker
13:12:46.375 Debug [ 6] WorkShift: NonParallel shift assigned worker NonParallelWorker
13:12:46.375 Debug [ 6] WorkShift: NonParallelSTA shift assigned worker NonParallelSTAWorker
13:12:46.381 Debug [ 6] Dispatcher: Using NonParallel strategy for Mytest.dll
13:12:46.384 Info  [ 6] WorkShift: NonParallel shift starting
13:12:46.385 Info  [ 6] TestWorker: NonParallelWorker starting on thread [10]
13:12:46.386 Info  [ 6] WorkItemQueue: NonParallelQueue.0 starting
13:12:46.387 Info  [10] TestWorker: NonParallelWorker executing Mytest.dll
13:12:46.403 Debug [10] Dispatcher: Using Direct strategy for Mytest
13:12:46.403 Debug [10] Dispatcher: Using Direct strategy for TestScripts
13:12:46.403 Debug [10] Dispatcher: Using Direct strategy for LoginScreen
13:12:46.403 Debug [10] Dispatcher: Using NonParallel strategy for Login
13:12:46.403 Info  [10] TestWorker: NonParallelWorker executing Login
13:12:46.404 Info  [10] Dispatcher: Saving Queue State for Login
13:12:46.405 Debug [10] WorkItemQueue: NonParallelQueue.0 pausing
13:12:46.405 Info  [10] WorkItemQueue: NonParallelQueue.1 starting

**Comment by mikkelbu** [comment] 2019-08-26 11:19
Hi @vegesnacreativeworks Is it possible to see the exit code when the console fails (I would expect it to be printed when you run the console normally and when you run `--inprocess` you would need to fetch it manually)

**Comment by vegesnacreativeworks** [comment] 2019-08-26 11:26
HI Mikkelbu.. Could you pls help me with the details like how i can fetch the details Manually..
Thanks in Advance!

Below error i am getting in the console when i did't use --inprocess flag. Is this the info you are asking for?
1) Error : 
System.Runtime.Remoting.RemotingException : Tcp transport error.
  ----> System.Runtime.Remoting.RemotingException : Connection closed
--RemotingException
Tcp transport error.
Server stack trace: 
  at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.ReceiveMessageStatus (System.IO.Stream networkStream, System.Byte[] buffer) [0x00017] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, System.Runtime.Remoting.Channels.ITransportHeaders& responseHeaders, System.IO.Stream& responseStream) [0x0005e] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg) [0x00066] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
Exception rethrown at [0]: 
  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, System.Runtime.Remoting.Messaging.IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x0014d] in <7a62ef3b49f14d16b21221b9b5a4792c>:0 
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr)
  at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent.Run(NUnit.Engine.ITestEventListener,NUnit.Engine.TestFilter)
  at NUnit.Engine.Runners.ProcessRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00025] in <d5dabe0b10664f5d8da90fb102a841f8>:0

**Comment by mikkelbu** [comment] 2019-08-27 17:56
I was more interested in the output above `Error`. If I provoke an agent failure it get something like this (on windows), search for `exit code`.
```
PS C:\src\NUnit\nunit-console\bin\Release\net35> .\nunit3-console.exe C:\Users\Mikkel\Source\Repos\FailFast\FailFast\bin\Debug\FailFast.dll
NUnit Console Runner 3.11.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
27 August 2019 19:49:36

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.18362.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Users\Mikkel\Source\Repos\FailFast\FailFast\bin\Debug\FailFast.dll


Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code -2146232797
   at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Services\TestAgency.cs:line 331
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

Errors, Failures and Warnings

1) Error :
System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
--SocketException
An existing connection was forcibly closed by the remote host

Server stack trace:
   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 164

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-08-27 17:49:37Z
    End time: 2019-08-27 17:49:39Z
    Duration: 2.500 seconds

Results (nunit3) saved as TestResult.xml

NUnit.Engine.NUnitEngineUnloadException : Agent Process was terminated successfully after error.
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:49561
PS C:\src\NUnit\nunit-console\bin\Release\net35>
```

Regarding getting the exit code on MacOSX, then it depends on how you are executing the console. If you use bash as shell, then you can use `echo $?` on the prompt. But as this depends on the shell etc. it is probably easiest to google for how to retrieve the exit code.

**Comment by vegesnacreativeworks** [comment] 2019-08-28 05:56
Hi Mikkelbu..

Pls find the error log. Hope this should help you in identifying the issue.

I am running the script as shell script in the console.

Currently we are in RunMobiletests script
Testcase Execution start date and Time: Thu Aug 22 19:12:16 IST 2019
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
22 August 2019 19:12:17
Runtime Environment
   OS Version: MacOSX 17.7.0.0 
  CLR Version: 4.0.30319.42000
Test Files
    /Users/vsnr/Test/obj/Debug/mytest.dll
Test Filters
    Test: mytest.TestScripts.LoginScreen.Login.TC01_Login_UI
Errors, Failures and Warnings
1) Error : 
System.Runtime.Remoting.RemotingException : Tcp transport error.
  ----> System.Runtime.Remoting.RemotingException : Connection closed
--RemotingException
Tcp transport error.
Server stack trace: 
  at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.ReceiveMessageStatus (System.IO.Stream networkStream, System.Byte[] buffer) [0x00017] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, System.Runtime.Remoting.Channels.ITransportHeaders& responseHeaders, System.IO.Stream& responseStream) [0x0005e] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg) [0x00066] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
Exception rethrown at [0]: 
  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, System.Runtime.Remoting.Messaging.IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x0014d] in <7a62ef3b49f14d16b21221b9b5a4792c>:0 
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr)
  at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent.Run(NUnit.Engine.ITestEventListener,NUnit.Engine.TestFilter)
  at NUnit.Engine.Runners.ProcessRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00025] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
--
RemotingException
Connection closed
  at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.StreamRead (System.IO.Stream networkStream, System.Byte[] buffer, System.Int32 count) [0x00011] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.ReceiveMessageStatus (System.IO.Stream networkStream, System.Byte[] buffer) [0x00000] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-08-22 13:42:17Z
    End time: 2019-08-22 13:42:19Z
    Duration: 1.989 seconds
Results (nunit3) saved as /Users/vsnr/test/Results/Test.xml
NUnit.Engine.NUnitEngineUnloadException : System.Runtime.Remoting.RemotingException : Connection refused
Failed to stop the remote agent. System.Runtime.Remoting.RemotingException : Connection refused
--RemotingException
Connection refused
Server stack trace: 
  at System.Runtime.Remoting.Channels.Tcp.HostConnectionPool.CreateConnection () [0x0002f] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.Tcp.HostConnectionPool.GetConnection () [0x0009d] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.Tcp.TcpConnectionPool.GetConnection (System.String host, System.Int32 port) [0x00056] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, System.Runtime.Remoting.Channels.ITransportHeaders& responseHeaders, System.IO.Stream& responseStream) [0x00022] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
  at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg) [0x00066] in <a625ce6df6374e4a98cb2931a6b5bc3b>:0 
Exception rethrown at [0]: 
  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, System.Runtime.Remoting.Messaging.IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x0014d] in <7a62ef3b49f14d16b21221b9b5a4792c>:0 
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr)
  at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent.Stop()
  at NUnit.Engine.Agents.RemoteTestAgentProxy.Stop () [0x00000] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.ProcessRunner.Dispose (System.Boolean disposing) [0x0007b] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
TestCase Execution End date and Time: Thu Aug 22 19:12:19 IST 2019

**Comment by vegesnacreativeworks** [comment] 2019-09-03 05:28
@mikkelbu @ChrisMaddock : Hi, did you get a chance to look into the issue. is there any update pls.

**Comment by mikkelbu** [comment] 2019-09-04 07:06
@vegesnacreativeworks Sorry about the delay, but I've been very busy the last week. I don't know much about how the console behaves on MacOSX, and I cannot see anything in the error log to diagnose the problem, so I would propose the following:
* Try to run `--inprocess` and see what the exit code of the process is (for how to do this see my comment above, or google for it)
* Try to create a minimal example and see if that fails or is successful. Meaning a project containing only one test or a couple of tests, as few dependencies as possible to other packages etc.

**Comment by vegesnacreativeworks** [comment] 2019-09-06 11:20
HI Mikkelbu,

I have tried running my tests using --inprocess i am not getting any errors in the Internal Trace Log. But still my tests are not running.

i am using below sample command to run the tests. (Not given the test name info etc)
mono /nunit-console-runner.3.10.0/tools/nunit3-console.exe /pathtodll --trace=Debug --inprocess --test=Namespace.TestSmaple —output=outputfilepath —result=pathto.xml;format=nunit3

Termianl shows below info
Runtime Environment
OS Version: MacOSX 17.7.0.0
CLR Version: 4.0.30319.42000

Test Files
—— Dll info ——

Test Filters
Test: —test info—

Now i am not getting any of the test status information in the Terminal. Below info is not displayed after giving --inprocess flag.
Test Run Summary
Overall result: Failed
Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
Start time: 2019-09-05 11:56:10Z
End time: 2019-09-05 11:56:12Z
Duration: 2.233 seconds

2. i have tried creating .Net 4.7 solution with one one test in it using Xamarin Ui test (3.0.3) and Nunit 3.12 still i am getting the same issue.

**Comment by mikkelbu** [comment] 2019-09-07 18:27
But if the process exits, then what is the exit code?

**Comment by 29217321** [comment] 2020-02-17 09:53
I am seeing the same error also - do we have a workaround?

```
--RemotingException
Connection closed
Server stack trace: 
  at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.StreamRead (System.IO.Stream networkStream, System.Byte[] buffer, System.Int32 count) [0x00011] in <b695ac4837d1434284d6fe511da0893c>:0 
  at System.Runtime.Remoting.Channels.Tcp.TcpMessageIO.ReceiveMessageStream (System.IO.Stream networkStream, System.Runtime.Remoting.Channels.ITransportHeaders& headers, System.Byte[] buffer) [0x00012] in <b695ac4837d1434284d6fe511da0893c>:0 
  at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, System.Runtime.Remoting.Channels.ITransportHeaders& responseHeaders, System.IO.Stream& responseStream) [0x00080] in <b695ac4837d1434284d6fe511da0893c>:0 
  at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg) [0x00066] in <b695ac4837d1434284d6fe511da0893c>:0 

Exception rethrown at [0]: 
  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, System.Runtime.Remoting.Messaging.IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x0014d] in <6d03841284d248b2a69863e319721b74>:0 
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr)
  at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent.Stop()
  at NUnit.Engine.Agents.RemoteTestAgentProxy.Stop () [0x00000] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.ProcessRunner.Dispose (System.Boolean disposing) [0x00195] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.AbstractTestRunner.Dispose () [0x00000] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.MasterTestRunner.Dispose (System.Boolean disposing) [0x00013] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.Engine.Runners.MasterTestRunner.Dispose () [0x00000] in <d5dabe0b10664f5d8da90fb102a841f8>:0 
  at NUnit.ConsoleRunner.ConsoleRunner.RunTests (NUnit.Engine.TestPackage package, NUnit.Engine.TestFilter filter) [0x00163] in <5aaaf9e9937946f799ed7126b3850b46>:0 
  at NUnit.ConsoleRunner.ConsoleRunner.Execute () [0x000b6] in <5aaaf9e9937946f799ed7126b3850b46>:0 
  at NUnit.ConsoleRunner.Program.Main (System.String[] args) [0x00225] in <5aaaf9e9937946f799ed7126b3850b46>:0 
```

**Comment by ChrisMaddock** [comment] 2020-02-17 22:05
Hi @29217321 - this exception can be caused by a number of issue. Please can you create a new bug report, and provide the requested info in the bug report template. Thanks. 👍

**Comment by ChrisMaddock** [comment] 2020-02-17 22:06
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2020-02-17 22:06 UTC
Labels: confirm
