### ISSUE TITLE
This app can't run on your PC error while executing .dll file using Nunit console runner in Windows 10 PC

### ISSUE THREAD

**Issue by abdulkhameer** [nunit/nunit-console#425] opened 2018-06-01 04:31 UTC
![vm_issue](https://user-images.githubusercontent.com/11190751/40821160-d0e938a4-6582-11e8-9433-6da3de59285f.png)
Hi All,
I have automation scripts developed using nunit , and trying to execute the project .dll using Nunit console runner command line , but getting This app can't run on your PC error prompts and after closing this access denied message will be shown on command prompt. I tried the same in another Windows 10 machine which have same configuration as mine but it works. Only difference is , mine win10 enterprise another one win10 Pro. 

Does OS version matter for this error? or Firewall blocking my app to run? 
please help me on this.

thanks in advance

**Comment by mikkelbu** [comment] 2018-06-01 06:47
Hi @abdulkhameer.
This sounds more like a Windows problem than a nunit problem. I've tried to see if I could find any any prior NUnit issues with the above-mentioned message, but so far I've only found post relating to a general problem in Windows 10.

https://answers.microsoft.com/en-us/windows/forum/windows_10-power-winpc/this-app-cant-run-on-your-pc/d4869176-98fa-45b7-baf9-23c083335148
https://www.kapilarya.com/fix-this-app-cant-run-on-your-pc-windows-10

**Comment by ChrisMaddock** [comment] 2018-07-08 11:31
Closing this, as it looks like the problem may lie outside of NUnit.

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2018-07-08 11:31 UTC
Labels: is:question

**Comment by shadycraig** [comment] 2018-07-12 12:51
I had the same issue after installing 3.8.0 using the msi installer onto a fresh install of Windows 10 Pro.
I removed NUnit and downloaded the .zip instead and that works fine.
@abdulkhameer  could you try this and see if it works for you?

@ChrisMaddock Perhaps the issue lies with using the msi on Win 10?

**Comment by ChrisMaddock** [comment] 2018-07-12 15:18
@shadycraig That's very interesting. The msi and the zip contain the exact same executable - so it's odd that it would behave differently!

Google suggests that this error message may also be caused by SmartScreen, so I wonder if you're seeing a manifestation of this: https://github.com/nunit/nunit/issues/558

Is the error reproducible for you? If so, would you mind seeing if temporarily disabling smartscreen allows you to solve the problem?

If it does - I wonder if signing our msi's is the solution to this...

**Comment by shadycraig** [comment] 2018-07-23 12:41
@ChrisMaddock Yes it appears to be the same as https://github.com/nunit/nunit/issues/558
Strange that now I'm unable to reproduce the problem, smartscreen is still on.

**Comment by samuel-knutson** [comment] 2019-09-10 21:53
I faced a similar issue today with NUnit Console Runner 3.10.0. I originally installed this NUnit runner version on 8/27/2019, and it worked fine. Today, I started seeing this error "This app cannot run on your PC" when trying to run the `nunit3-console.exe` from the command line. I used the msi to remove the existing version, and then used the msi to re-install that same version (3.10.0). After the re-install, it started working again.

🤷‍♂
