### ISSUE TITLE
NUnit console fails when tests utilize reflection

### ISSUE THREAD

**Issue by espenekvang** [nunit/nunit-console#345] opened 2018-01-11 20:26 UTC
We have an issue where NUnit tests run green in Visual Studio 2017, but when running them through nunit-console they fail, reason for failing varies. We have created an example here to illustrate the behaviour:  https://github.com/espenekvang/nunit-failing/

It seems to be related to the fact that we are using reflection in the test, but we are not sure about this.

**Comment by CharliePoole** [comment] 2018-01-11 22:48
The example is great once somebody is working on the issue, but to evaluate the issue and decide who will work on it, it will help us to have some info first...
 * Version of the nunit framework you are using
 * The platform you are targeting
 * Version of the console runner you are using
 * The command-line you use to run the tests
 * Which tests fail unexpectedly and what messages you see

**Comment by espenekvang** [comment] 2018-01-12 04:30
- NUnit package version 3.9.0
- target framework: .NET Framework 4.6.2
- NUnit Console Runner version 3.7.0
- the tests are automatically run in the example when running `build.cmd`. Inside this script you will see that the command line used for nunit-runner is: `./tools/Nunit.ConsoleRunner/tools/nunit3-console.exe "--noheader" "--result=C:\dev\nunit-failing\testresults\UnitTestResults.xml" "--params=exclude=IgnoreOnVSTSBecauseOfNoAccessToOnPremResource;exclude=NeedsAadCertificateInLocalMachineStore" "C:\dev\nunit-failing\build\NUnit.Failing.Tests.Unit.dll`
- In the example there are two tests; one test without any reflection and one test that is using reflection to determine the result. The test without reflection, `TestWithoutReflection`, is never failing. The test called `TestIfAttributeExists` is only failing when running nunit-console-runner, but is passing using ReSharper testrunner or using the NUnit 3 Test Adapter inside Visual Studio. 
- when the test is failing, the following message is displayed from the nunit-console-runner: `1) Error : NUnit.Failing.Tests.Unit.SimpleControllerTests.TestIfAttributeExists
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at NUnit.Failing.Tests.Unit.SimpleControllerTests.GetSubtypeOf[TBaseType]() in C:\dev\nunit-failing\src\NUnit.Failing.Tests.Unit\SimpleControllerTests.cs:line 60
   at NUnit.Failing.Tests.Unit.SimpleControllerTests.GetControllerActionMethodsWithoutAttribute(String[] whitelist, Type[] attributeTypes) in C:\dev\nunit-failing\src\NUnit.Failing.Tests.Unit\SimpleControllerTests.cs:line 38
   at NUnit.Failing.Tests.Unit.SimpleControllerTests.TestIfAttributeExists() in C:\dev\nunit-failing\src\NUnit.Failing.Tests.Unit\SimpleControllerTests.cs:line 21
--FileNotFoundException`

**Comment by mikkelbu** [comment] 2018-01-12 20:33
Disclaimer: I know next to nothing about ASP.Net (I've not installed this in VS, so I've not examined how the behaviour is in VS).

I don't think that this is a problem with NUnit. If I make the test code output which assemblies it tries to load, then I see that it successfully loads all *.dlls in the `build` folder. Then it recurs to the subfolders where it fails in `build\_PublishedWebsites\NUnit.Failing\bin\` (on my machine loading `Microsoft.Build.Tasks.CodeAnalysis.dll`, but I don't think that the ordering is guaranteed).

Since I assume that you are only interested in examining your own *.dll(s) then one solution could be to change `SearchOption.AllDirectories` into `SearchOption.TopDirectoryOnly`. Otherwise, you would need to change the build-process to place all relevant *.dlls into `build\_PublishedWebsites\NUnit.Failing\bin\`, but I don't know how to do that.

**Comment by CharliePoole** [comment] 2018-01-12 20:50
This is probably not relevant to this issue, but I notice you set the run parameter "exclude" to two different values in your command line. There is no particular support for that and you will end up getting an exception thrown if you are using a recent version of the framework that tries to build a dictionary out of the values you pass. Frankly, I never thought of checking for this error when I added the feature!

**Comment by CharliePoole** [comment] 2018-01-12 20:56
Your error message lists a specific assembly, `System.IO.Compression`, which cannot be found when running under the console runner. What are you doing to ensure it's available?

**Comment by ChrisMaddock** [comment] 2018-02-15 21:58
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2018-02-15 21:58 UTC
Labels: confirm

**Comment by MartinGonzalez** [comment] 2018-02-24 03:26
I don't know if this will reopen the issue but

Using:
* Nunit 3.9.0
* Target Framework: .NET 4.5
* NUnit Console Runner 3.8.0
* Engine: Unity3d
* This code.
```
using NUnit.Framework;
using UnityEngine;

[TestFixture]
    public class MyEditorTests
    {

        [Test]
        public void Should_Pass()
        {
            Debug.Log("PASS"); //Part of UnityEngine Library (It uses reflection)
            Assert.IsTrue(true);
        }
   }
```
* Running: `mono NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe Temp/bin/Debug/Assembly-CSharp-Editor.dll`

Throws me this: 

```
1) Error :
NUnit.Engine.NUnitEngineException : The NUnit 3 driver encountered an error while executing reflected code.
  ----> System.InvalidCastException : Specified cast is not valid.
--NUnitEngineException


Server stack trace:
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject (System.String typeName, System.Object[] args) [0x0002c] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load (System.String testAssemblyPath, System.Collections.Generic.IDictionary`2[TKey,TValue] settings) [0x0009e] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.LoadDriver (NUnit.Engine.Extensibility.IFrameworkDriver driver, System.String testFile, NUnit.Engine.TestPackage subPackage) [0x00008]in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.LoadPackage () [0x000c4] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.TestDomainRunner.LoadPackage () [0x00017] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded () [0x00008] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.DirectTestRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Runners.AbstractTestRunner.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <a3ad5449913a4202999529a949a30f07>:0
  at NUnit.Engine.Agents.RemoteTestAgent.Run (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00000] in <a3ad5449913a4202999529a949a30f07>:0
  at (wrapper managed-to-native) System.Runtime.Remoting.RemotingServices:InternalExecute (System.Reflection.MethodBase,object,object[],object[]&)
  at System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (System.MarshalByRefObject target, System.Runtime.Remoting.Messaging.IMethodCallMessage reqMsg) [0x000b5] in<4fdc5ed61a074cafb49fa42deb20d521>:0

Exception rethrown at [0]:
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_remoting_wrapper (intptr,intptr)
  at (wrapper remoting-invoke) NUnit.Engine.Agents.RemoteTestAgent:Run (NUnit.Engine.ITestEventListener,NUnit.Engine.TestFilter)
  at NUnit.Engine.Runners.ProcessRunner.RunTests (NUnit.Engine.ITestEventListener listener, NUnit.Engine.TestFilter filter) [0x00025] in <a3ad5449913a4202999529a949a30f07>:0
--InvalidCastException
  at NUnit.Framework.Api.FrameworkController+LoadTestsAction..ctor (NUnit.Framework.Api.FrameworkController controller, System.Object handler) [0x00008] in <116d15b838ac4e24a87624af132b3294>:0
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <4fdc5ed61a074cafb49fa42deb20d521>:0
```

* Running: `nunit-console Temp/bin/Debug/Assembly-CSharp-Editor.dll`

Throws me this:
```
NUnit version 2.4.8Copyright (C) 2002-2007 Charlie Poole.Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.Copyright (C) 2000-2002 Philip Craig.All Rights Reserved.Runtime Environment -   OS Version: Unix 17.4.0.0  CLR Version: 4.0.30319.42000 ( 5.4.1.6 (2017-06/1f4613aa1ac Wed Oct 18 09:31:57 EDT 2017) ).FTests run: 1, Failures: 1, Not run: 0, Time: 0.078 secondsTest Case Failures:1) MyEditorTests.Should_Pass : System.MissingMethodException : Attempted to access a missing method.at (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,string,UnityEngine.Object)
at UnityEngine.DebugLogHandler.LogFormat (UnityEngine.LogType logType, UnityEngine.Object context, System.String format, System.Object[] args) [0x0000a] in <c1fc6d6821f64259a8f55
7776dfd86a1>:0
at UnityEngine.Logger.Log (UnityEngine.LogType logType, System.Object message) [0x00028] in <c1fc6d6821f64259a8f557776dfd86a1>:0at UnityEngine.Debug.Log (System.Object message) [0x00006] in <c1fc6d6821f64259a8f557776dfd86a1>:0
at MyEditorTests.Should_Pass () [0x00001] in /Users/martingonzalez/Desktop/NUnitConsoleTestsSampleApp/Assets/Editor/MyEditorTests.cs:11at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
```

**Comment by CharliePoole** [comment] 2018-09-07 19:26
@MartinGonzalez Sorry that nobody seems to have seen your comment! It appears from the first example that a different version of nunit is being accessed (by unity?) than the one that is loaded. Does Unity reference nunit in any way?

In your second example, using the 2.4.8 console runner against a test assembly that references NUnit 3.0 or higher is almost certain to give a missing method exception, just as you see there.

@millsy013 As folks add there +1s to issues, it often turns out that the precise issue they see is not what was originally proposed. Can you add some detail about what you are doing?

@ALL note that the error message about an error while reflecting is simply a result of the fact that the framework is called through reflection. It doesn't necessarily relate to your test code using reflection, although it clearly could.

**Comment by rprouse** [comment] 2018-09-07 22:06
@MartinGonzalez this isn't a reflection issue because you aren't using reflection in your test. As far as I can tell, this is just a Unity issue, possibly because Unity compile AOT. What project type and target are the tests you compiled above? Unity?

**Comment by MartinGonzalez** [comment] 2018-09-07 22:12
Guys! Thanks for the answer. Indeed is a Unity issue. `Debug.Log` is part of Unity Engine, I'm not an expert with Assemblies and Dlls but the library UnityEngine is compiled in another .dll, so when i run tests on this Assembly using code of other library throws MissingMethod.
 Running unit tests without Unity infrastructure worked fine.

Again, thanks!
