### ISSUE TITLE
AppDomains are not identical for two test assemblies when executing with --domain=Single

### ISSUE THREAD

**Issue by GraueEminenz79** [nunit/nunit-console#357] opened 2018-01-22 16:12 UTC
Hi,
me again. Please correct me (and close issue) if my expectation is wrong:
When executing two different test assemblies and enforcing the `--domain=Single` parameter
```
nunit3-console.exe A.dll B.dll --domain=Single
```
I assume the `AppDomain.CurrentDomain.FriendlyName;` to be identical for each and every test of test fixture A and B.
Yet I get two different AppDomains like:
`domain-someGuid-A.dll
domain-otherGuid-B.dll`

Is it mandatory to enforce `--process=Separate` as well?
^
EDIT: Answered my own question: as of now it is needed. Is it intended to stay that way (explicitly setting the process model)? Or is this a behaviour to be fixed, meaning to implicitly enforce the process model when calling --domain=Single for >1 test assemblies?

**Comment by CharliePoole** [comment] 2018-01-22 19:40
Of course, a two assemblies cannot use the same AppDomain unless they are already in the same process.

Historically (I say that a lot) NUnit V2 defaulted to running tests in process. Back then, just using the `--domain:Single` option worked as intended. Now we default to running each assembly in a separate process, so the `--domain:Single` option ends up meaning to run a single assembly in a single domain!

We could, of course, deduce from your use of `--domain:Single` that you intended to run the tests in a single separate process or in-process (we'd have to guess which one). We don't usually do that or haven't in the past anyway. 

Options on this that I can see:
1. Leave as is and clarify the docs
2. Give a warning about this and any other options that will have no real effect (e.g. `--process:Multiple` with only one assembly given`)
3. Assume `--process:Single` if you specify `--domain:Single`.

Personally, I don't like assumptions, other than the assumption that you knew what you typed. :smile:

**Comment by ChrisMaddock** [comment] 2018-01-22 21:05
I like option 2 😊 I wonder if 3 would be a more sensible default however - if process is unspecified.

**Comment by CharliePoole** [comment] 2018-01-22 21:43
@ChrisMaddock It could be if you are willing to risk the slippery slope of context-sensitive option validation. As it is now, any option that is valid is always valid. We don't try to predict whether the particular __combination__ of options is invalid, although there is a place where you could add that to the command-line options class..

If we did go with a more context-sensitive approach, we would have to restrict it to those options and their action __which the console runner is supposed to know about__. That is, we couldn't involve options that relate to the framework unless we wanted to build in specific knowledge of the NUnit 3 framework in the console runner - which I don't think we should do. In fact, this is an issue even for option 2: we can't give warnings that imply we know what framework will be used to run the test.

Historically (there I go again!) we have done this by ignoring things we don't understand. For example, if you use `--workers` when running tests against a different framework from NUnit 3, the setting is effectively ignored, not by the console, which just passes it on, but by the framework that receives it.

Put differently, it's possible to do 3 but a lot more complex to do right. :-) 

Simple example: you are running an nunit project, which includes `ProcessModel=Single` in the file. By default, the domains are separate. You use `--domain:Single` on the command-line to overrride. This is valid but the console runner can't know it is without looking inside the project and breaking encapsulation. This is the kind of corner case that led us to the principle of just passing on anything we can't understand.

**Comment by ChrisMaddock** [comment] 2018-01-22 21:55
Hmm.

The engine would know this combination of domain/process options is invalid however, wouldn't it? But I guess that would involve adding some sort of `ValidatePackage()` stage - so we had a cleaner way to respond with 'warnings' rather than just throwing exceptions...

**Comment by CharliePoole** [comment] 2018-01-22 22:06
Specifically, the engine instance that creates the AppDomains will know. However, in the default case, that would be the instance that is running under the agent. The process would already have been created. All that engine could do would be to post a warning saying that "--domain:Single" is redundant - it would only know about the setting and the fact that there is just one assembly. It would not know that there or were not any other assemblies running in other processes.

Of course, the primary engine could do more to analyze what is going to happen in other processes ahead of time and give a warning, but that's a slippery slope too because it means updating that primary engine whenever any secondary engines, agents or other types of external runners change their behavior.

**Comment by rprouse** [comment] 2018-01-25 01:50
The process and domain command line options have always had several possible conflicts and we originally decided to just leave them as-is with some documentation. To be honest, I don't think many people use those options now that we run each test assembly in it's own agent. So, I am only really in favor of the first option, documenting what the options do and how they conflict. I think once you understand what they do, it is fairly easy to deduce how they conflict 😄

**Comment by CharliePoole** [comment] 2022-01-03 18:56
Closing this since we are planning on removing the ability to run multiple tests in the same domain.

**Closed by CharliePoole** 2022-01-03 18:56 UTC
