### ISSUE TITLE
Nunit.Console 3.8 - Socket Exception

### ISSUE THREAD

**Issue by BlythMeister** [nunit/nunit-console#370] opened 2018-02-09 14:26 UTC
Since upgrading from 3.7 to 3.8 i more instances of a failed tests with "NUnit.Engine.NUnitEngineUnloadException"

> [17:06:51][Test:Run] NUnit.Engine.NUnitEngineUnloadException : Multiple exceptions encountered. Retrieve AggregatedExceptions property for more information
> [17:06:51][Test:Run]   ----> System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
> [17:06:51][Test:Run] Running build failed.
> [17:06:51][Test:Run] Error:
> [17:06:51][Test:Run] NUnit test failed. Process finished with exit code FatalError (-5).

Unfortunatly this error gives me no hint as to why the socket exception has occured, or where i can look to find out....

**Comment by ChrisMaddock** [comment] 2018-02-09 22:17
Did you previously see SocketExceptions in NUnit Console 3.7?

This is what https://github.com/nunit/nunit-console/issues/255 will now look like - if the socket exception occured whilst the test run was being cleaned up. It could either be that the test agent crashed during this process - or it could be an instance of a potential race condition we haven't been able to pin down. Try running with `--trace#Debug` - see what the agent logs look like when you get this exception.

If you didn't see SocketExceptions with 3.7, this may be a new issue. 😞

**Comment by BlythMeister** [comment] 2018-02-10 07:13
We did sometimes see socket exception 
I can try running with trace to see what I get.

Would it be possible to output the library which the missing agent was testing?
We pass around 200 DLL to nunit console so trying to work out which one caused the issue is near impossible.
But some extra logging here to give hints would be really useful.

**Comment by ChrisMaddock** [comment] 2018-02-10 11:01
Yes, so long as you’re running in separate processes, i think it would be? Definitely plans to do more to output better debug information here.

That would be a great pull request, if you’d be willing? It should be possible to catch the socketexception, and rethrow as an Nunitengine exception with the socket exception as the innerexception, and some more information in the exception message as to which app domain caused the issue.

**Comment by BlythMeister** [comment] 2018-02-10 12:15
The problem is that there is no longer a stack track to find out where the exception is coming from...I'll have a look see if I can add anything else around this error handling in the console runner itself to help users when nunit exceptions occur.
Essentially giving more context to the error.

**Comment by ChrisMaddock** [comment] 2018-02-11 23:34
I've been thinking about this some more...

I _think_ this console log would only come up in one of a couple of ways. 1) The race condition mentioned or 2) An unrelated bug causing the agent to otherwise crash during the unload process.

Something like https://github.com/nunit/nunit-console/issues/335 would help with the latter problem.

**Comment by BlythMeister** [comment] 2018-02-13 16:15
@ChrisMaddock is there a way to set where the tracelogs get put?

**Comment by CharliePoole** [comment] 2018-02-13 16:31
The logs are saved relative to the "work" directory if you set it using option `--work`.

Note that the "work" directory is the place where NUnit saves all logs and reports, it's not the Windows "working" directory. Bad naming on my part back when I'm afraid.

**Comment by BlythMeister** [comment] 2018-02-14 14:58
I have been able to capture the agent/trace logs and the only error in here is
```
Failed to stop the remote agent. An existing connection was forcibly closed by the remote host
```
[Nunit.zip](https://github.com/nunit/nunit-console/files/1724426/Nunit.zip)
So this leaves me none the wiser as to why the socket error is occurring.

**Comment by BlythMeister** [comment] 2018-02-14 18:56
I've done some digging on this and I can't work out the link between the process runner and the agent itself.
I can see the code in the agent which matches the logging and showing the agent stopping.
And I can see the error handling in the process runner.
I wonder if the dispose in process runner when it calls stop should catch a socket exception and treat that as a happy path.
The aim of the function is to stop the agent, if the agent has gone from the other end of the pipe then the net result is the agent has been stopped?

Would you accept a PR to that affect?

**Comment by CharliePoole** [comment] 2018-02-14 19:20
I don't know what the current team will accept, however, I can give a bit of background.

NUnit originally simply ignored any failure to unload a Process it an AppDomain by swallowing the exception. At some point, somebody wanted this reported, so we started down the path that took us to the point where we are today. We are piling fix upon fix to deal with what's essentially a non-issue for us.

IMO we should record information directly at the time a problem occurs but should not attempt to handle it through an exception in the runner.

**Comment by BlythMeister** [comment] 2018-02-14 19:54
I can see what you mean.

My ci build failing when actually the only thing wrong is that for some reason nunit agent didn't stop as expected is kind of annoying.
If the tests all pass, I'm happy 🙂

**Comment by ChrisMaddock** [comment] 2018-02-14 22:56
This isn’t related to app domain unload, is it? That would be a different stack trace/log if it was?

I believe this is a race condition in the agent shut down that we are aware of - @jnm2 did some digging, but it was difficult to pin down. Given we wanted to change the communication protocol anyway, the most prodictive solution seemed to be to invest time there instead.

In the meantime, I think something to catch this exception and discard is probably a worthwhile sticking plaster - fixing the actual cause is a big piece of work which has been hanging on for a while. 

@BlythMeister - my only concern with your idea is that the agent could genuinely crash during shut down, and your suggestion would hide that. How about something that catches the socketexception - then checks the exit code of the agent process (which I believe is stored somewhere), and swallows the exception only If the agent exited with a 0? I believe that would be possible - I’m not looking at the code right now.

I’d like to hear @jnm2’s thoughts before moving on here. 😊

**Comment by CharliePoole** [comment] 2018-02-15 00:12
@ChrisMaddock Catching the exception and not rethrowing in the agent doesn't necessarily mean hiding it. The agent can report the information in some way. I think it's trying to deduce the cause of the problem in the primary process that's causing us so much effort. 

The return code of the agent process is already available to us. I like your idea of checking it but I wouldn't necessarily throw another exception. Instead, I might just report it as a warning on the assembly level test suite for the particular assembly.

**Comment by jnm2** [comment] 2018-02-15 00:41
Sticking plaster sounds good. The five second pause before shutdown was the plaster IO thought we would ship, but anything really is fine. Too bad there's only so many of us!

**Comment by ChrisMaddock** [comment] 2018-02-15 08:27
Did you intend to close this Charlie?

**Comment by ChrisMaddock** [comment] 2018-02-15 08:28
And yes - warnings would be nice - but would be a bigger piece or work, I believe?

**Comment by BlythMeister** [comment] 2018-02-15 08:32
@ChrisMaddock i've pushed a set of sticky plaster fixes in #372 as well as including a stack trace to the error logs.

**Comment by ChrisMaddock** [comment] 2018-02-15 21:49
Fixed in https://github.com/nunit/nunit-console/pull/372

**Closed by ChrisMaddock** 2018-02-15 21:49 UTC
Labels: confirm

**Comment by aolszowka** [comment] 2018-07-15 01:16
We're running on Master as well (due to #290) and can confirm that this fix works for us.
