### ISSUE TITLE
SkipNonTestAssemblies does not skip non-test assemblies if they reference nunit.framework

### ISSUE THREAD

**Issue by ap0llo** [nunit/nunit-console#627] opened 2019-05-17 20:13 UTC
## Summary 

When a assembly references `nunit.framework` (e.g. containing a helper method that calls `Assert`), but does not contain any actual tests, `nunit3-console` exists with an error even though the ` --skipnontestassemblies` parameter is specified. 

## Steps to reproduce:

* Example project available at https://github.com/ap0llo/repro-nunit-console-skipnontestassemblies
* Repo contains two assemblies, neither of which have any tests in them
  * FailingAssembly contains a method calling `Assert.True` an thus has a reference to `nunit.framework.dll`
  * WorkingAssembly has no reference to `nunit.framework`
* Run both assemblies through nunit3-console:
```
nunit3-console.exe --skipnontestassemblies .\bin\net461\FailingAssembly.dll
nunit3-console.exe --skipnontestassemblies .\bin\net461\WorkingAssembly.dll
```
### Expected behavior

No tests are executed, but both calls complete without an error

### Actual behavior
Execution for `FailingAssembly` completes with error *No test fixtures were found*

```
NUnit Console Runner 3.6.1
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17763.0
  CLR Version: 4.0.30319.42000

Test Files
    .\bin\net461\FailingAssembly.dll


Errors, Failures and Warnings

1) Invalid : bin\net461\FailingAssembly.dll
No test fixtures were found.

Run Settings
    DisposeRunners: True
    SkipNonTestAssemblies: True
    WorkDirectory: C:\Users\Andreas\Desktop\nunittest
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-05-17 20:01:30Z
    End time: 2019-05-17 20:01:31Z
    Duration: 0.936 seconds

Results (nunit3) saved as TestResult.xml
```

Is this a bug or is this the intended behavior?

**Comment by CharliePoole** [comment] 2019-05-17 20:26
This is intended behavior.

The definition of a test assembly is one that references the nunit framework unless it is specifically marked as a nontest assembly using the NonTestAssemblyAttribute at the assembly level.

**Comment by mikkelbu** [comment] 2019-05-17 20:26
Looking at the old release notes I would say that it is intended behavior, and that you should place a `NonTestAssemblyAttribute` in FailingAssembly to making it pass.

https://github.com/nunit/docs/wiki/Console-Release-Notes says

> Added command line option --skipnontestassemblies to skip assemblies that do not contain tests without raising an error and to skip assemblies that contain the NUnit.Framework.NonTestAssemblyAttribute.

(too slow :))

**Closed by CharliePoole** 2019-05-17 20:26 UTC

**Comment by ap0llo** [comment] 2019-05-17 21:09
Okay, I didn't know about the attribute.
Thanks for clarifying.

**Comment by mikkelbu** [comment] 2019-05-17 21:16
@ap0llo It is also undocumented on our pages as far as I can tell. I'll create an issue for it in the docs repository and add some documentation (I only found it googling for `skipnontestassemblies`)

**Comment by CharliePoole** [comment] 2019-05-17 21:20
I deliberately didn't document it thinking only third party runner authors would need it. But here's a more common use case.
