### ISSUE TITLE
APP-CRASH during execution

### ISSUE THREAD

**Issue by brantkev** [nunit/nunit-console#264] opened 2017-07-17 12:56 UTC
I am trying to execute a test through Nunit3 Console runner.  The test contains approximately 1600 Specflow generated tests written in C#.  All test run successfully within Visual Studio 2015 with the Nunit adapter.  When executing using the following command:

_"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" --labels=All --out=TestResult.txt "--result=TestResult.xml;format=nunit2" c:\projects\ena\UAT\IntegrationTests\bin\debug\IntegrationTests.dll --where cat==uat_

The test runs for a period of time, then exits with error below:
Errors, Failures and Warnings

1) Error :
An existing connection was forcibly closed by the remote host

Server stack trace:
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
   at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Within the event view I find the following two entries:
Fault bucket 120796825787, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: nunit-agent.exe
P2: 3.6.1.0
P3: 58bdfcf4
P4: clr.dll
P5: 4.7.2053.0
P6: 58fa6d2a
P7: c00000fd
P8: 000000000004cd33
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD571.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_nunit-agent.exe_867da1ddb49ad7b5ad612b4863d40d8418bb4_7720ed5f_8b35dc38

Analysis symbol: 
Rechecking for solution: 0
Report Id: 764572ea-8e69-4b85-b178-b17b97fc32c8
Report Status: 0
Hashed bucket: f5a36acc77f76e4b66a136eb1d9e895e

AND:

Faulting application name: nunit-agent.exe, version: 3.6.1.0, time stamp: 0x58bdfcf4
Faulting module name: clr.dll, version: 4.7.2053.0, time stamp: 0x58fa6d2a
Exception code: 0xc00000fd
Fault offset: 0x000000000004cd33
Faulting process id: 0x9950
Faulting application start time: 0x01d2fef847896a8e
Faulting application path: C:\Program Files (x86)\NUnit.org\nunit-console\nunit-agent.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 764572ea-8e69-4b85-b178-b17b97fc32c8
Faulting package full name: 
Faulting package-relative application ID: 

I have been able to run successfully when reducing the number of test to about 500.  Is there a limit to the number of test that can be executed within Nunit Console?  Is there a way to increase the number?

**Comment by ChrisMaddock** [comment] 2017-07-17 13:56
This issue should be fixed in the v3.7 of NUnit Console.

Will you give it a try and let us know?

**Comment by brantkev** [comment] 2017-07-17 13:59
![nunit](https://user-images.githubusercontent.com/22029684/28271474-8cc7f86a-6ad6-11e7-8a61-1125d0809bce.JPG)

I have installed and update all to Nunit 3.7

**Comment by ChrisMaddock** [comment] 2017-07-17 14:03
Which console are you using here?

You log above is from an msi installation of the console, and is version 3.6.1. However, you've just posted a screenshots of NuGet packages? Have you changed how you're running the tests? 

If you can still reproduce the error in v3.7, then this is likely the same as https://github.com/nunit/nunit-console/issues/255. v3.7 appears to have fixed the majority of these issues, however.

**Comment by brantkev** [comment] 2017-07-17 14:27
I have upgraded and validated, receiving same error, same stack.  

![nunit_console](https://user-images.githubusercontent.com/22029684/28272787-855f0088-6ada-11e7-919c-93f4ec90c4b3.JPG)

**Comment by ChrisMaddock** [comment] 2017-07-17 14:46
Can you try @jnm2's specified fix, in this post: https://github.com/nunit/nunit-console/issues/255#issuecomment-315502568

**Comment by ChrisMaddock** [comment] 2017-07-17 14:47
I'm going to close this is a duplicate of #255 - but we'd appreciate your help in tracking down the source of the problem. @jnm2 is working on that on #255.

And just to answer your question...

>Is there a limit to the number of test that can be executed within Nunit Console? Is there a way to increase the number?

There shouldn't be, no. This is a bug, that's unfortunately currently proving difficult to reproduce.

**Closed by ChrisMaddock** 2017-07-17 14:47 UTC
Labels: confirm
