### ISSUE TITLE
Excepción de HRESULT: 0x80131015 with Oracle.DataAccess.client library

### ISSUE THREAD

**Issue by pemola** [nunit/nunit-console#771] opened 2020-05-13 09:26 UTC
Good morning,

I received an error: "DomainManager: Exception encountered unloading application domain: Error al descargar AppDomain. (Excepción de HRESULT: 0x80131015)" after executing my test (but the test passed)
I try to detect the line which causes it, and the result is that the error appears when I open the OracleConnection so I can`t understand it because I need to open the connection with the database.

This is the comand and the result: 

> C:\prueba\ejemplo>packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe api_ejemplo\api_ejemplo.Integracion.Test\bin\x64\Debug\api_ejemplo.Integracion.Test.dll --trace=Debug

> NUnit Console Runner 3.8.0
> Copyright (c) 2018 Charlie Poole, Rob Prouse

> Runtime Environment
>   OS Version: Microsoft Windows NT 10.0.18363.0
>  CLR Version: 4.0.30319.42000

> Test Files
>     api_ejemplo\api_ejemplo.Integracion.Test\bin\x64\Debug\api_ejemplo.Integracion.Test.dll

> Run Settings
     DisposeRunners: True
     InternalTraceLevel: Debug
     WorkDirectory: C:\prueba\ejemplo
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.7.2
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

> Test Run Summary
  > Overall result: Passed
  > Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  > Start time: 2020-05-13 09:04:44Z
   > End time: 2020-05-13 09:04:47Z
   >  Duration: 2.683 seconds

> Results (nunit3) saved as TestResult.xml

> NUnit.Engine.NUnitEngineUnloadException : Agent Process was terminated successfully after error.
>   ----> NUnit.Engine.NUnitEngineUnloadException : Exception encountered unloading application domain
>   ----> NUnit.Engine.NUnitEngineException : Exception encountered unloading application domain: Error al descargar AppDomain. (Excepción de HRESULT: 0x80131015)
> Application domain name: domain-
> Application domain BaseDirectory: C:\prueba\ejemplo\api_ejemplo_microservicio\api_ejemplo.Integracion.Test\bin\x64\Debug\`

And the code that produces the error (reduces to the minimun):

```
public List<string> GetDato()
        {
            List<string> lista = new List<string>();

            OracleConnection conexion = null;

            try
            {
                conexion = new OracleConnection(cadenaconexion);
                conexion.Open();
            }
            catch (Exception e)
            {
                throw;
            }
            finally
            {
                if (conexion.State == ConnectionState.Open)
                {
                    conexion.Close();
                    conexion.Dispose();
                }
            }
            return lista;
        }
```
I uses ODP.NET 4.122.18.3 for 64 bits and Framework 4.7.2

[InternalTrace.20656.api_ejemplo.Integracion.Test.dll.log](https://github.com/nunit/nunit-console/files/4620943/InternalTrace.20656.api_ejemplo.Integracion.Test.dll.log)
[InternalTrace.32540.log](https://github.com/nunit/nunit-console/files/4620944/InternalTrace.32540.log)
[nunit-agent_20656.log](https://github.com/nunit/nunit-console/files/4620945/nunit-agent_20656.log)

Thank you!

**Comment by mikkelbu** [comment] 2020-05-13 11:33
Hi @pemola Some comments. 

How is this method called from the test? Can you provide some context.
It seems that you are only closing and disposing the `conexion` if the state is `Open`, but isn't it safe always to dispose the connection? So you can use a `using` pattern (https://docs.microsoft.com/en-us/dotnet/api/system.data.oracleclient.oracleconnection?view=netframework-4.8)

**Comment by pemola** [comment] 2020-05-13 12:01
> Hi @pemola Some comments.
> 
> How is this method called from the test? Can you provide some context.
> It seems that you are only closing and disposing the `conexion` if the state is `Open`, but isn't it safe always to dispose the connection? So you can use a `using` pattern (https://docs.microsoft.com/en-us/dotnet/api/system.data.oracleclient.oracleconnection?view=netframework-4.8)

Thank you for your answer

This is the test code (reduced also):

```
 [Test]
        public void GetDatosTest()
        {
            //Arrange
            AccesoDatos.Persistence.PruebaDAO datos = new AccesoDatos.Persistence.PruebaDAO();

            //Act
            List<string> lista = datos.GetDato();

            //Assert
            lista.Should().HaveCountGreaterThan(0);
      }
```

I tried also with the using pattern but I got the same result. Only when I comment the line **conexion.Open();** I achieve to avoid the error

**Comment by ChrisMaddock** [comment] 2020-05-17 01:25
Hi @pemola, 

This issue occurs when your tests don't clean up after themselves completely. From the code you've posted, I agree it's likely to be caused by the database connection not being closed cleanly, but I'm afraid none of us are Oracle experts here, so it's difficult for us to help with that!

What I can tell you, is that in later versions of the NUnit Console, we downgraded this issue from being an error to a warning. So if you upgrade your version of the console, it will allow your tests to complete without error. That said, I'd really recommend fixing the cause of the problem however, when you can. 🙂

**Comment by ChrisMaddock** [comment] 2020-05-25 19:58
Closing this, as it looks like the problem may lie outside of NUnit.

Happy to reopen if anyone has more to add. 🙂

**Closed** 2020-05-25 19:59 UTC
Labels: closed:notabug, is:question

**Comment by pemola** [comment] 2020-05-26 08:51
> Hi @pemola,
> 
> This issue occurs when your tests don't clean up after themselves completely. From the code you've posted, I agree it's likely to be caused by the database connection not being closed cleanly, but I'm afraid none of us are Oracle experts here, so it's difficult for us to help with that!
> 
> What I can tell you, is that in later versions of the NUnit Console, we downgraded this issue from being an error to a warning. So if you upgrade your version of the console, it will allow your tests to complete without error. That said, I'd really recommend fixing the cause of the problem however, when you can. 🙂

Thank you very much! I'll try the latest version of Nunit until I could resolve the problem with Oracle
