### ISSUE TITLE
NUnit temp file not found

### ISSUE THREAD

**Issue by FestTestQA** [nunit/nunit-console#679] opened 2019-08-29 13:13 UTC
Hi, I'm using TC build 66342 and running an NUnit step to execute automated UI tests.

Recently the Nunit step fails at the last hurdle which is producing an html report.

I've attached a healthy build log vs the failing one.

Could you please advise?

_[Step 5/6] Results (nunit3) saved as C:\BuildAgent\temp\buildTmp\PRW70RxgSYUTUlsqRwM9y2yPCVmj2RtH.nunit.xml
[15:53:44]
[Step 5/6] Results (nunit2) saved as C:\BuildAgent\work\5d8dc0169a1aa61/VerySimpleServiceChargeMatrix_SpecFlowTestResult.xml_

vs 

_[12:55:56]
[Step 5/6] Could not find a part of the path 'C:\BuildAgent\temp\agentTmp\eTCrWl19o8iLZFxGWohhtOcBalkg8AG5.nunit.xml'.
[12:55:56]
[Step 5/6] Process exited with code -2
[12:55:56]
[Step 5/6] NUnit process finished with negative exit code -2 (unexpected failure). Reporting step failure.
[12:55:56]
[Step 5/6] Publishing artifacts
[12:55:56]
[Step 5/6] Process exited with code -2 (Step: NUnit (NUnit))
[12:55:56]
[Step 5/6] Step NUnit (NUnit) failed
[12:55:58]
[Step 5/6] Error message is logged_

**Comment by FestTestQA** [comment] 2019-08-29 13:17
![Screenshot - 29_08_2019 , 14_12_05](https://user-images.githubusercontent.com/42983374/63943482-aa5a5600-ca67-11e9-9811-8b13079a243d.png)

**Comment by FestTestQA** [comment] 2019-09-08 17:17
Nikolay Pianikov (TeamCity) 
Sep 6, 13:52 CEST 
Hi
Looks like this issue because of [this change](https://github.com/nunit/nunit/commit/5cf290157cebd36c51111bdf0bcab3ec08d7d93f) and it was fixed [here](https://github.com/nunit/nunit-console/issues/501). Try downgrading NUnit 3 console to 3.8

**Comment by mikkelbu** [comment] 2019-09-08 18:25
@FestTestQA We need some more context to help you.
* Which version of NUnit and NUnit-console are you using.
* When you say "Recently the Nunit step fails". What happened here. Did you upgrade NUnit or the console?
* How exactly are you executing the tests?
* `buildTmp` and `agentTmp` are two different temp folders of TC, so perhaps something changed in the configuration of TC?
* Can you provide some more of the log (or try to increase the verbosity of the log), so that we have more information

The first change you are linking to is a change to the build process of NUnit itself, so this will only affect you if you are compiling NUnit project and running the NUnit tests using our cake build-script. The second change just creates a folder if it does not exist

I'm a bit unsure about
> Try downgrading NUnit 3 console to 3.8

As the changes you are linking to does not have anything to do with 3.8, but are changes in later releases.

**Comment by FestTestQA** [comment] 2019-09-08 20:47
Hi,

1. Using NUnit 3.10
2. Usung NUnit Console 3.10
3. The steps started failing randomly with no obvous change to framework, TC version, packages etc.
4. The tests are being executed in TeamCity using the NUnit runner
5. Logs of 1 build and 1 agent are now attached
[Build_log.log.zip](https://github.com/nunit/nunit-console/files/3588038/Build_log.log.zip)
[teamcity-agent.zip](https://github.com/nunit/nunit-console/files/3588039/teamcity-agent.zip)

**Comment by ChrisMaddock** [comment] 2019-09-09 12:06
Hi @FestTestQA.

On your response from TeamCity support, I think there may be an incorrect link. The change linked to is a change to the framework's own build script, which is unreleated to how the console would run on your machine. @NikolayPianikov - looking at the pre-edit version of that comment, I believe you've looked at this before - able to shed any light?

Please can you retrieve the NUnit logs, rather than the TeamCity ones? You can get these by adding -`--trace=Debug` to your console command line. You should then find multiple log files created in `C:\BuildAgent\work\5d8dc0169a1aa61\LogiPro.Tests\bin\Debug` - please could you share them all?

**Comment by ChrisMaddock** [comment] 2019-09-09 12:10
Summary from the log files: The console is being started with this command line:

```
Starting: C:\BuildAgent\work\5d8dc0169a1aa61\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe C:\BuildAgent\temp\agentTmp\W9q2ZBiIs9GapKbOeQRNJt825AdbRfbN.nunit --result=C:\BuildAgent\temp\agentTmp\W9q2ZBiIs9GapKbOeQRNJt825AdbRfbN.nunit.xml --noheader --where cat==SimpleMultiNoReserve&&cat!=Ignore --labels=On --result=C:\BuildAgent\work\5d8dc0169a1aa61/SimpleServiceChargeMatrix_Multiple_NoReserves_SpecFlowTestResult.xml;format=nunit2 --out=C:\BuildAgent\work\5d8dc0169a1aa61/SimpleServiceChargeMatrix_Multiple_NoReserves_SpecFlowTestResult.txt
```

TeamCity is then unable to find a results file in the below location:
```
Could not find a part of the path 'C:\BuildAgent\temp\agentTmp\W9q2ZBiIs9GapKbOeQRNJt825AdbRfbN.nunit.xml'.
```

What I am suspicious of, is that TeamCity appears to create the nunit project file as normal, but then be unable to find it to upload as an artifact. (However, it is running 39 tests from _somewhere_)

```
[16:31:50]W:	 [Step 5/6] Publishing artifacts
[16:31:50] :		 [Publishing artifacts] Collecting files to publish: [C:\BuildAgent\temp\agentTmp\W9q2ZBiIs9GapKbOeQRNJt825AdbRfbN.nunit => .teamcity\bt52_RUNNER_39]
[16:31:50]W:		 [Publishing artifacts] Artifacts path 'C:/BuildAgent/temp/agentTmp/W9q2ZBiIs9GapKbOeQRNJt825AdbRfbN.nunit' not found
```

@NikolayPianikov - any ideas why that would happen?

**Comment by FestTestQA** [comment] 2019-09-09 13:30
I've kicked off anotther TC build with tracing enabled...

**Comment by NikolayPianikov** [comment] 2019-09-09 15:04
I cannot reproduce this issue, but as I know 'Could not find a part of the path ...' is message from a dotnet exception. TeamCity does not use this xml report and just appends it for a build story. TeamCity cannot find a file there, but it is not a problem, just a warning. From the log: TeamCity runs nunit3-console, but the nunit console fails with exit code `-2` and shows the error `'Could not find a part of ...`.

The `teamcity-agent.log` build log file is quite strange. Looks like several TeamCity agents are running in parallel using a single home directory. Could you make sure each TeamCity agent has own home directory.

**Comment by ChrisMaddock** [comment] 2019-10-05 14:20
Closing this, as there's not enough information to understand/reproduce the problem.

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2019-10-05 14:20 UTC
Labels: confirm
