### ISSUE TITLE
Explore option bypass --where expressions

### ISSUE THREAD

**Issue by dariogriffo-fourth** [nunit/nunit-console#41] opened 2016-08-24 13:39 UTC
When running nunit3-console with --explore and --where "EXPRESSION" nunit3-console will bypass the --where expression.
Attached is an image showing what I'm doing to reproduce this locally.
I added 4 tests
2 with specflow (1 with a tag called "One", another with a tag "Two")
2 regular nunit tests (1 with a tag called "One", another with a tag "Two")
When running tests with --where = "cat != One" is works fine, only 1 specflow + 1 non specflow runs
When running the app with --where and --explore I see all the tests in the screen.

Note: The dll is called TestSpecflow but there are only 2 specflow tests.

![explore](https://cloud.githubusercontent.com/assets/13639216/17932551/6c935d3e-6a08-11e6-8f8c-4ccf1e6cb987.png)

**Comment by CharliePoole** [comment] 2016-08-24 13:45
This is a duplicate of nunit/nunit#1143. The console and engine supply a filter, but the frameworks is not using it in the explore operation.

**Closed by CharliePoole** 2016-08-24 13:45 UTC
