### ISSUE TITLE
NUnit3 console execute on .netCore 3.1" on Windows command line-InvalidCastException : Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.

### ISSUE THREAD

**Issue by sundarj6** [nunit/nunit-console#792] opened 2020-06-23 23:32 UTC
Does Nunit3.11.1 support .netCore 3.1 applications or not.?
In the release notes says it support.
A simple .netCore3.1 application ( A console application) throws the exception as follows
C:\>cd C:\NUnit\NUnit.Console-3.11.1\bin\net35

C:\NUnit\NUnit.Console-3.11.1\bin\net35>nunit3-console.exe C:\Users\source\repos\DemoNew\DemoNew\bin\Debug\netcoreapp3.1\DemoNew.dll
NUnit Console Runner 3.11.1 (.NET 2.0)
Copyright (c) 2020 Charlie Poole, Rob Prouse
Tuesday, June 23, 2020 7:20:04 PM

Runtime Environment
   OS Version: Microsoft Windows NT 6.2.9200.0
   Runtime: .NET Framework CLR v4.0.30319.42000

Test Files
    C:\Users\source\repos\DemoNew\DemoNew\bin\Debug\netcoreapp3.1\DemoNew.dll

Errors, Failures and Warnings

1) Error :
NUnit.Engine.NUnitEngineException : The NUnit 3 driver encountered an error while executing reflected code.
  ----> System.InvalidCastException : Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
--NUnitEngineException
The NUnit 3 driver encountered an error while executing reflected code.

Server stack trace:
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine.core\Drivers\NUnit3FrameworkDriver.cs:line 179
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine.core\Drivers\NUnit3FrameworkDriver.cs:line 99
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine.core\Runners\DirectTestRunner.cs:line 162
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage() in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine.core\Runners\DirectTestRunner.cs:line 152
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded() in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine.core\Runners\DirectTestRunner.cs:line 262
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine.core\Runners\DirectTestRunner.cs:line 210
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\Users\Chris\Documents\git\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 163
--
InvalidCastException
Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2020-06-23 23:20:04Z
    End time: 2020-06-23 23:20:05Z
    Duration: 1.404 seconds

Results (nunit3) saved as TestResult.xml

**Comment by CharliePoole** [comment] 2020-06-24 00:04
The 3.11.1 NUnit Framework supports .NET Core but the Console runner does not yet support it. We hope to have support in the 3.12 release of the console runner.

For now, your options are 
1. Run using NUnitLite, which is distributed along with the NUnit framework.
2. Use dotnet CLI.
3. Run in the test explorer under Visual Studio.

Options 2 and 3 require use of the NUnit 3 VS adapter.

**Comment by ChrisMaddock** [comment] 2020-06-26 16:03
Thanks Charlie. Closing this as a duplicate of #475

**Closed by ChrisMaddock** 2020-06-26 16:03 UTC
Labels: confirm, is:bug
