### ISSUE TITLE
UnitTest randomly failing

### ISSUE THREAD

**Issue by borisrangelov** [nunit/nunit-console#449] opened 2018-08-14 10:06 UTC
There is a very strange behavior with our unit tests. One of them seems to randomly fail without any helpful error message, plus the overall result is passed. 

This is the result from the console:
 **Test Run Summary**
  **Overall result: Passed**
  **Test Count: 2551, Passed: 2550, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0**
    **Failed Tests - Failures: 1, Errors: 0, Invalid: 0**
  **Start time: 2018-08-14 09:28:56Z**
    **End time: 2018-08-14 09:29:56Z**
    **Duration: 60.814 seconds**

**Results (nunit3) saved as build\UnitTest\TestResults.xml**
**Running build failed.**
**Error:**
**NUnit test failed (1).**

But in the TestRusults.xml from the same job everything seems to be ok and all 2551 tests have passed.
So something clearly doesn't add up here.

Here is a snippet from the TestResults.xml:
`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="2551" result="Passed" total="2551" passed="2551" failed="0" inconclusive="0" skipped="0" asserts="3830" engine-version="3.8.0.0" clr-version="4.0.30319.42000" start-time="2018-08-14 09:28:56Z" end-time="2018-08-14 09:29:56Z" duration="60.813952">`

Is this a known issue?
Is there a workaround or anything we can do to prevent the test from randomly failing?

**Comment by ChrisMaddock** [comment] 2018-08-14 11:12
Can you share the entire TestResults xml, and entire console output please?

Randomly failing tests are normally something to do with how the tests are written - although I'm not immediately sure why there's no information on what failed.

**Comment by borisrangelov** [comment] 2018-08-14 12:39
Is it possible to send you this as a private message?

**Comment by ChrisMaddock** [comment] 2018-08-14 16:49
Sure - chrismaddock@live.co.uk. 👍

**Comment by pchinery** [comment] 2018-08-15 07:03
Just to clarify: It's not a randomly failing test, but the console runner randomly failing. As you can see in the console summary, it states

     Test Count: 2551, Passed: 2550, Failed: 1

The XML is:

     <test-run id="2" testcasecount="2551" result="Passed" total="2551" passed="2551" failed="0"

And this is for the same run. It looks like there might be a race condition inside the NUnit runner that causes the last test not to be tracked correctly.

If there really is a failing test, the test name is written to the console, but when this happens, it does not name any failed tests.

We hope that you have an idea what we could try to either give you more information or work around this issue.

**Comment by ChrisMaddock** [comment] 2018-08-15 20:32
@borisrangelov - thanks for sending over the logs. In the spirit of open source, let's continue debugging in the public forum! 😄 

Your TestResult.xml contains one failed `<test-case>` - you can see which one by searching for `result="Failed"`. What's causing the issue, is that the `<test-suite>` element which contains the test-case is reporting `result="Passed"` - which is unexpected - we would expect a test-suite to fail, if any of it's sub-tests fail.

Could you take a look at the tests in question, and see if you can produce a minimal example, based on what's going on there? This doesn't seem to be a common problem - so are you doing anything unusual? Perhaps asynchronous?

One last thought (a long shot!) - in the Gitlab log you sent, it reads like you might be starting the nunit3-console command line twice - straight after each other. (Your command line is printed on both lines 3235 and 3236. Could you investigate if that is happening - and if so, perhaps there's a way the two processes could be interacting, and getting mixed up a long the way. (I'm not sure exactly how they could 'get mixed up' off the top of my head - but this seems to be enough of an unusual issue to question this!)

**Comment by pchinery** [comment] 2018-08-16 06:57
I think the "double call" of nunit3-console is just an overly eager logging from the FAKE (F# MAKE) NUnit 3 target, but we'll investigate on that as well.

It's strange though, that the XML file reports all tests as passed but lists a failed test in the details, thanks for pointing that out. We'll try to get down to the essence of the problem and hopefully can provide something helpful.

**Comment by ChrisMaddock** [comment] 2018-09-17 09:36
@borisrangelov @pchinery Did you manage to dig anything up on this one? 🙂

**Comment by ChrisMaddock** [comment] 2018-10-08 12:47
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2018-10-08 12:47 UTC
Labels: confirm
