### ISSUE TITLE
Class Level Custom Properties are not rendered when using where filters

### ISSUE THREAD

**Issue by GitClickOk** [nunit/nunit-console#845] opened 2020-12-19 20:38 UTC
Hello, I'm using:
- NUnit Console Runner 3.12.0-beta1
- Microsoft Windows 10.0.19042
- .NET Core 3.1.10

When discovering tests using NUnit Console Runner, the class level attributes are not generated if using --where filter. Here I did an example to reproduce this problem, just create a basic test with "dotnet new nunit", and use this code:

```
using System;
using NUnit.Framework;

namespace Tests
{
    [CustomIdAttribute("42")]
    public class BaseTest
    {
    }

    [CustomIdAttribute("7")]
    public class MyTest : BaseTest
    {
        [Test]
        [CustomTextAttribute("Hello")]
        public void Test1()
        {
            Assert.Pass();
        }
    }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
    public class CustomIdAttribute : PropertyAttribute
    {
        public CustomIdAttribute(string id) : base(id)
        {
        }
    }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
    public class CustomTextAttribute : PropertyAttribute
    {
        public CustomTextAttribute(string text) : base(text)
        {
        }
    }
}
```

If I execute the command to discover all tests:
`nunit3-console.exe "C:\NUnitConsoleBug\bin\Debug\netcoreapp3.1\Tests.dll" --explore=nunit`
Everything works nicely:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="0" runstate="Runnable" testcasecount="1">
  <test-suite type="Assembly" id="1-1002" name="Tests.dll" fullname="C:/NUnitConsoleBug/bin/Debug/netcoreapp3.1/Tests.dll" runstate="Runnable" testcasecount="1">
    <properties>
      <property name="_PID" value="15200" />
      <property name="_APPDOMAIN" value="nunit3-console" />
    </properties>
    <test-suite type="TestSuite" id="1-1003" name="Tests" fullname="Tests" runstate="Runnable" testcasecount="1">
      <test-suite type="TestFixture" id="1-1000" name="MyTest" fullname="Tests.MyTest" classname="Tests.MyTest" runstate="Runnable" testcasecount="1">
        <properties>
          <property name="CustomId" value="7" />
        </properties>
        <test-case id="1-1001" name="Test1" fullname="Tests.MyTest.Test1" methodname="Test1" classname="Tests.MyTest" runstate="Runnable" seed="415270478">
          <properties>
            <property name="CustomText" value="Hello" />
          </properties>
        </test-case>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>
```
Please note I can correctly see the `<property name="CustomId" value="7" />` generated in the file. But If I execute this command:
`nunit3-console.exe "C:\NUnitConsoleBug\bin\Debug\netcoreapp3.1\Tests.dll" --explore=nunit --where "CustomText == Hello"`, the result does not appears my CustomId:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="0" runstate="Runnable" testcasecount="1">
  <test-suite type="Assembly" id="1-1004" name="Tests.dll" fullname="C:/NUnitConsoleBug/bin/Debug/netcoreapp3.1/Tests.dll" runstate="Runnable" testcasecount="1">
    <test-suite type="TestSuite" id="1-1005" name="Tests" fullname="Tests" runstate="Runnable" testcasecount="1">
      <test-suite type="TestFixture" id="1-1006" name="MyTest" fullname="Tests.MyTest" runstate="Runnable" testcasecount="1">
        <test-case id="1-1001" name="Test1" fullname="Tests.MyTest.Test1" methodname="Test1" classname="Tests.MyTest" runstate="Runnable" seed="776107706">
          <properties>
            <property name="CustomText" value="Hello" />
          </properties>
        </test-case>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>
```

Is this a bug in NUnit Console? Or am I doing something wrong?

**Comment by mikkelbu** [comment] 2020-12-19 23:46
I think that this is a duplicate of nunit/nunit#3611. @GitClickOk can you see if updating to the latest NUnit framework build solves the problem (not the console). The latest builds can be found here - https://www.myget.org/feed/nunit/package/nuget/NUnit.
If it solves the problem, then it will be solved in NUnit 3.13.

**Comment by ChrisMaddock** [comment] 2020-12-20 00:03
Thanks Mikkel! I knew this was familiar, but couldn't find the old issue at all! 😄

**Comment by GitClickOk** [comment] 2020-12-20 04:51
Hey, @mikkelbu and @ChrisMaddock, it works!

Is there some specific reason why I can't see this version in [Nuget](https://www.nuget.org/packages/NUnit/)? The max version there is 3.12.0.

**Comment by CharliePoole** [comment] 2020-12-20 05:23
Because it's not yet released. Note that the link is to MyGet rather than NuGet. That's where the development feed is.

**Comment by ChrisMaddock** [comment] 2020-12-27 12:21
Thanks all - I'll close this now. 🙂

**Closed by ChrisMaddock** 2020-12-27 12:21 UTC
Labels: confirm, is:bug
