### ISSUE TITLE
Nunit Agent leads to very high Power Usage and high CPU

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit-console#901] opened 2021-02-21 19:50 UTC
Hi
I noticed that the Nunit Agent leads to very high Power Usage and high CPU.
Any idea?
Best Regards,
Nadeem Bader

**Comment by rprouse** [comment] 2021-02-22 00:13
@NadeemBader whenever we've investigated this in the past, it turned out to be the user's code that was being tested that caused the problems, not the agent which is just the test runner. The test runner has been extensively profiled and is fairly efficient. The only time the agent causes problems is when your tests cause massive test results to be produced, but once again, that is usually your code 😉

**Comment by NadeemBader** [comment] 2021-02-22 10:05
Hi
Thank you for your reply
In previous post, I indicated high Power Usage... but let me be more specific: It leads to high CPU and memory (I modified the title too):

![image](https://user-images.githubusercontent.com/44542344/108691995-c5930e00-7504-11eb-97a6-0f542bba49cf.png)

I have a console application which contains the below code. By running the console application, the Nunit Agent start to run and the tests runs properly, but during the tests I see high CPU and memory. The CPU sometimes become even 18% which is high.

```
                string finalRes = string.Empty;
                using (ITestEngine engine = TestEngineActivator.CreateInstance())
                {
                    using (ITestRunner runner = engine.GetRunner(package))
                    {
                        var filter = new TestFilter(query);
                        var result = runner.Run(new TestEventDispatcher(), filter);

                        finalRes = result.Attributes["result"].Value;
                        Console.WriteLine($"Result State: {finalRes}");

                        try
                        {
                            var resultService = engine.Services.GetService<IResultService>();

                            var resultWriter = resultService.GetResultWriter("nunit3", null);
                            resultWriter.WriteResultFile(result, nUnitXMLResultPath);
                        }
                        catch (Exception e)
                        {
                            Console.WriteLine($"{e.Message}");
                        }
                    }

                    if (finalRes.Equals("Passed"))
                    {
                        break;
                    }
                }
```

Any suggestions?

Best Regards,
Nadeem Bader

**Comment by CharliePoole** [comment] 2021-02-22 15:32
Your execution code doesn't seem to have anything wrong with it. You haven't shown the content of your TestEventDispatcher, so a further test would be to pass one that does nothing. IIRC, passing null will accomplish that.

When @rprouse said the problem is usually with the user code, I believe he meant the code in your tests. That will take some debugging of course.

Before doing that, however, I wonder why you believe that 14% CPU utilization is high in this case? What is the nature of the tests you are running? They are clearly not bound by the CPU.

**Comment by NadeemBader** [comment] 2021-02-23 17:40
Actually, I didn't understand your point regarding TestEventDispatcher(). Should I pass the instance of it an an input to the Run method (As I do in my code)? Or to pass "null" object?
Hope you can clarify that? and does that has any effect on CPU and Memory?

In addition, the test actually testing an applications with advanced visualizations (Based on Microsoft WPF). Does that has any effect on CPU and Memory?

**Comment by CharliePoole** [comment] 2021-02-23 20:19
Let me clarify... You are creating an instance of `TestEventDispatcher`. As you have not posted its code, I don't know what it does. So from my viewpoint, I have to wonder if its purpose is to take up a lot of CPU and memory. :smile:

Of course, I know there is an internal class in the code of the NUnit console runner with the same name, but it wouldn't make any sense for you to be using that unless you have adapted it in some way to work with your runner.

So bottom line... I don't know if `TestEventDispatcher` affects CPU and memory, as I don't know what it does.

Re WPF... Yes indeed, that could take up a lot of resources, particularly if your tests or the application doesn't free them up. Many GUI applications don't bother to free resources, leaving that for the closing of the overall application. But that never works well in a testing environment, where resources that are normally only allocated once are repeatedly re-allocated.

**Comment by NadeemBader** [comment] 2021-02-25 11:59
I'm continue investigating it from my side based on your comments - Thank you.
Please don't close this Issue for now

**Comment by NadeemBader** [comment] 2021-02-27 22:14
When working with Nunit 2, the NUnit Agent process is not displayed as separate process in Task Manager and as a result, the high CPU is displayed next to the application that runs the nunit tests. For example:

![image](https://user-images.githubusercontent.com/44542344/109401802-7ceeb100-7959-11eb-9956-566d28e7bd30.png)


But, when working with Nunit 3, the Nunit Agent process is displayed as a separate process and the high CPU is displayed to it:

![image](https://user-images.githubusercontent.com/44542344/109401791-65afc380-7959-11eb-9541-ad11e17e8053.png)


Can I make the NUnit Agent process hidden\displayed in Task Manager by changing some configurations in the c# code that I posted in previous posts?

**Comment by CharliePoole** [comment] 2021-02-27 23:25
My guess is that you are running NUnit V2 in a way that it doesn't use an agent... i.e. running in-process. Depending on the version of the NUnit V2 console you are using, different options are available and different defaults may apply.

Beginning with NUnit 3.0, the default for the console runner was to run every test assembly in a different process (i.e. agent).

Of course, if I understand correctly, you are not using the console at all, so the behavior will depend on what options you pass to the engine - at least in the case of NUnit 3. For NUnit V2, you have not actually said how your runner is running those tests, so I can't give you an exact answer. What NUnit assemblies do you use to run under V2?

**Comment by NadeemBader** [comment] 2021-02-28 00:59
In both version I'm not using the nunit console exe, but I'm running the tests using the c# code directly.

_**### Nunit 2:**_

Here is my code in Nunit 2:

                ```
TestPackage testPackage;
                AppDomain runnerDomain;
                RemoteTestRunner remoteTestRunner;
                AndFilter andFilter;
                OrFilter orFilter;
                NotFilter notFilter;
                ITestFilter lastFilter = null;

               testPackage = new TestPackage("<DLL Path>");
               runnerDomain = AppDomain.CreateDomain("Runner Domain");
               runnerDomain.SetData("APP_CONFIG_FILE", "<App.Config file>");

                remoteTestRunner = RemoteTestRunner.CreateInstance(runnerDomain, 0);
                remoteTestRunner.Load(testPackage);

               TestResult testResult = remoteTestRunner.Run(new NullListener(), lastFilter, false, LoggingThreshold.All);
               XmlResultWriter writer = new XmlResultWriter(nUnitXMLResultPath);
```

The following package is installed in the running application:

![image](https://user-images.githubusercontent.com/44542344/109404589-3eb0bc00-7970-11eb-9512-3362185a7505.png)


_**### Nunit 3:**_ 

Here are the installed packages:

![image](https://user-images.githubusercontent.com/44542344/109404659-d1e9f180-7970-11eb-8ebb-34bd99c86321.png)


Based on the code that I posted in previous post, how can i make the Nunit Agent is hidden?

**Comment by CharliePoole** [comment] 2021-02-28 03:08
I'll repeat from my previous comments: an agent is a process. If you have an agent, you have a process and there's no way to make it hidden from the Task Manager.

There is no agent under your NUnit V2 version because you are not creating one. You are using low-level classes and creating a RemoteTestRunner directly in an AppDomain you own. There is no separate process because you create the runner in your process. There are higher level calls you can make to run tests in various ways, including in a separate process.

To be frank, your code for running the V2 tests is a bit surprising to me. You use the Visual Studio adapter, which is intended use under the Visual Studio test window, rather than using NUnitV2.Core directly. Of course, it works, because the adapter package includes the components from NUnitV2.Core, in addition to a lot of other code you are not using.

Maybe instead of "Why is it working this way?" we should ask the question of what you actually want to accomplish. How do you __want__ your tests to be run?

**Comment by NadeemBader** [comment] 2021-03-03 15:44
Thanks for clarifying the point.
Since my focus now on nunit3, it is important for me to understand the CPU when working on this version of nunit.

By trying to run the tests directly using nunit3-console.exe, seems that the CPU is similar somehow to what i see when I run them using the c# code:

![image](https://user-images.githubusercontent.com/44542344/109831015-b66c3880-7c47-11eb-81be-8eeb289a5e29.png)

But in some cases, I was wonder that the CPU value is 0 even the tests are running:

![image](https://user-images.githubusercontent.com/44542344/109831139-d3087080-7c47-11eb-97af-dbd8644467c8.png)

Any idea?

**Comment by CharliePoole** [comment] 2021-03-03 16:23
0% could mean that your test code is in a wait state, perhaps due to IO you perform. Could also happen if your test launches a child process of its own.

**Comment by CharliePoole** [comment] 2022-03-09 04:38
There has been no feedback on this for a year, so I'm closing.

**Closed by CharliePoole** 2022-03-09 04:38 UTC
Labels: Needs Confirmation
