### ISSUE TITLE
.NET Core engine only works when located in same directory as test assembly

### ISSUE THREAD

**Issue by beloquintana** [nunit/nunit-console#710] opened 2019-11-18 13:26 UTC
I am trying to run tests using NUnit.Engine.Api in Net Core, but I am getting this error:

Could not load file or assembly 'NUnitTestNetCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

My code is:

            ITestEngine nunitEngine = TestEngineActivator.CreateInstance();

            TestPackage package = new TestPackage("Test DLL Path");
            package.AddSetting("WorkDirectory", @"Test DLL WorkDirectory PATH");

            var filterService = nunitEngine.Services.GetService<ITestFilterService>();
            ITestFilterBuilder builder = filterService.GetTestFilterBuilder();

            TestFilter emptyFilter = builder.GetFilter();
            TestEventListner testListener = new TestEventListner();

            using (ITestRunner runner = nunitEngine.GetRunner(package))
            {
                XmlNode result = runner.Run(testListener, emptyFilter);
            }

I am using:
.NET Core 3.0
NUnit.Engine 3.10.0
NUnit.Engine.Api 3.10.0

**Comment by ChrisMaddock** [comment] 2019-11-18 19:45
What you have looks like it should be fine - although I'm not on a machine I can check on now. What is NUnitTestNetCore, is that your test assembly? I presume both your test assembly and 'runner' (the project this code is in) is .NET Core 3.0?

**Comment by beloquintana** [comment] 2019-11-18 19:51
Yes, NUnitTestNetCore is my test assembly.
I am using .NET Core 3.0 for my both solutions: test assembly and 'runner'.

NUnit.Engine.Api should run ok in .NET Core 3.0?

**Comment by ChrisMaddock** [comment] 2019-11-18 21:11
Yes, should do. Would be keen to hear about anything further you can debug and work out. 🙂 

The error message suggests that the test assembly can't be found. I presume you've tried specifying the path fully etc? Might be worth getting debug logs printed, and seeing if that helps identify what's failing. (Add setting `InternalTraceLevel` => `Debug` to your TestPackage)

**Comment by beloquintana** [comment] 2019-11-19 13:08
I am using the full path of my test assembly: D:\AppsTemp\NUnitNetCore2\NUnitNetCore2\bin\Debug\netcoreapp3.0\NUnitNetCore2.dll

**Exception**:
An exception occurred in the driver while loading tests.

   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.Load(String testAssembly, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)

**InternalTraceLevel => Debug:**
InternalTrace: Initializing at level Debug
09:47:53.797 Debug [ 1] ServiceManager: Added SettingsService
09:47:53.800 Debug [ 1] ServiceManager: Added DriverService
09:47:53.800 Debug [ 1] ServiceManager: Added RecentFilesService
09:47:53.800 Debug [ 1] ServiceManager: Added TestFilterService
09:47:53.800 Debug [ 1] ServiceManager: Added ExtensionService
09:47:53.800 Debug [ 1] ServiceManager: Added ProjectService
09:47:53.800 Debug [ 1] ServiceManager: Added ResultService
09:47:53.800 Debug [ 1] ServiceManager: Added DefaultTestRunnerFactory
09:47:53.801 Info  [ 1] ServiceManager: Initializing SettingsService
09:47:53.814 Info  [ 1] ServiceManager: Initializing DriverService
09:47:53.815 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
09:47:53.818 Info  [ 1] ServiceManager: Initializing RecentFilesService
09:47:53.818 Debug [ 1] ServiceManager: Request for service ISettings satisfied by SettingsService
09:47:53.818 Info  [ 1] ServiceManager: Initializing TestFilterService
09:47:53.818 Info  [ 1] ServiceManager: Initializing ExtensionService
09:47:53.821 Info  [ 1] ExtensionService: Scanning nunit.engine assembly for extension points
09:47:53.825 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/NUnitV2Driver, Type=NUnit.Engine.Extensibility.IFrameworkDriver
09:47:53.825 Info  [ 1] ExtensionService: Scanning nunit.engine.api assembly for extension points
09:47:53.826 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IService, Type=NUnit.Engine.IService
09:47:53.826 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/ITestEventListener, Type=NUnit.Engine.ITestEventListener
09:47:53.826 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IDriverFactory, Type=NUnit.Engine.Extensibility.IDriverFactory
09:47:53.826 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IProjectLoader, Type=NUnit.Engine.Extensibility.IProjectLoader
09:47:53.826 Info  [ 1] ExtensionService:   Found Path=/NUnit/Engine/TypeExtensions/IResultWriter, Type=NUnit.Engine.Extensibility.IResultWriter
09:47:53.847 Info  [ 1] ServiceManager: Initializing ProjectService
09:47:53.848 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
09:47:53.848 Info  [ 1] ServiceManager: Initializing ResultService
09:47:53.848 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
09:47:53.848 Info  [ 1] ServiceManager: Initializing DefaultTestRunnerFactory
09:47:53.848 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
09:47:53.848 Debug [ 1] ServiceManager: Request for service ITestFilterService satisfied by TestFilterService
09:47:53.849 Debug [ 1] ServiceManager: Request for service IProjectService satisfied by ProjectService
09:47:53.850 Debug [ 1] ServiceManager: Request for service ExtensionService satisfied by ExtensionService
09:47:53.850 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
09:47:53.851 Debug [ 1] ServiceManager: Request for service ITestRunnerFactory satisfied by DefaultTestRunnerFactory
09:47:54.819 Debug [ 1] ServiceManager: Request for service IDriverService satisfied by DriverService

Do you have any example of NUnit.Engine using NetCore ?

**Comment by ChrisMaddock** [comment] 2019-11-19 19:56
> Do you have any example of NUnit.Engine using NetCore ?

Have a look at the nunit3-vs-adapter repo. I don't think it uses the API assembly, but does something very similar. (And using the API assembly shouldn't make a difference...afaik!) Let us know if you manage to track down the problem! 🙂

**Comment by beloquintana** [comment] 2019-11-20 17:15
I still have the same problem.
The only way that works is when I run the TestEngine in the same project where I have the test code.

**Comment by ChrisMaddock** [comment] 2020-01-01 16:21
Adding this to 3.11 - we need to make sure this is working properly before the next release.

**Comment by ChrisMaddock** [comment] 2020-01-04 14:45
Hey @beloquintana,

Best I can tell you at this point is that I agree with you - this doesn't seem to be working as intended!

**Comment by ChrisMaddock** [comment] 2020-01-04 16:16
Ok - the only way things currently seem to work is if your runner and tests are published into the same directory. This of course shouldn't be the case, but seems to be a limitation of the currently functionality.

My current feeling is that we need to be using .NET Core specific functionality to load the assembly properly - which means we need a .NET Core 'agent', rather than trying to load assembly in-process in our current .NET standard engine. That's on our roadmap, but a big job - so I think we might have to release 3.11 with this limitation, taking account of the fact that this isn't a 'new' issue, and will be resolved in our long term plan. Looks like that also really rules out inprocess running for .NET Core tests. (Which is something I think will please @CharliePoole!)

@jnm2 - I know you know a bit about this area. I'd appreciate your thoughts if this sounds realistic, or if I'm going totally in the wrong direction?

**Comment by ChrisMaddock** [comment] 2020-01-04 16:34
Ok - I have a hack for 3.11 that I'm going to PR in a minute. I styill think the proper solution is as above.

**Comment by beloquintana** [comment] 2020-01-06 12:41
Thanks @ChrisMaddock. I will appreciate a lot when you can solve this issue. In my current work I am using a lot this functionality with .Net Framework and we are migrating to NetCore.

**Comment by ChrisMaddock** [comment] 2020-01-26 14:01
Moving this to 3.12. It's a major issue, but not a regression - and I'm keen to get 3.11 out, rather than delaying any further.

**Comment by jnm2** [comment] 2020-02-02 20:40
@ChrisMaddock 

> @jnm2 - I know you know a bit about this area. I'd appreciate your thoughts if this sounds realistic, or if I'm going totally in the wrong direction?

It's both realistic and something that has been bothering me about the framework too.  IIRC the framework is doing the equivalent of `Assembly.Load(new AssemblyName { Name = Path.GetFileNameWithoutExtension(assemblyPath) })`. I'd rather the framework got out of the game of loading assemblies.

A .NET Standard build of the framework makes sense to me as long as it does not load the test assemblies itself. A .NET Standard build of the engine doesn't make sense to me right now, whether in-proc or with a .NET Core agent. What .NET Standard platform other than .NET Framework and .NET Core are we going to be on where we can `Process.Start` an agent or where we can load assemblies given a file path?

**Closed** 2020-06-26 12:37 UTC
Labels: is:bug, pri:high

**Comment by dimizele** [comment] 2021-08-30 10:50
Hello,

I am trying to do this in my project as well, and seem to be having the same problem. The difference is I am using .Net 5. I get the same error Cannot find file or assembly. 
My code is pretty basic :

`public void TestRunner()
        {
            // Get an interface to the engine
            ITestEngine engine = TestEngineActivator.CreateInstance();

            TestPackage package = new TestPackage("C:\\Users\\dimitri.zhelkov\\source\\repos\\PoCInCore\\TestStuff\\bin\\Debug\\net5.0\\TestStuff.dll");

            // Get a runner for the test package
            ITestRunner runner = engine.GetRunner(package);

            // Run all the tests in the assembly
            XmlNode testResult = runner.Run(listener: null, TestFilter.Empty);
        }`

When I try to start it from the same assembly it seems to be working. Writing it here because it seems very closely related to this one

**Comment by StudioLE** [comment] 2022-07-29 17:00
@dimizele I was having the same issue and it looks like calling ` Assembly.LoadFrom()` prior to creating the `new TestPackage()` ensures the assembly and its dependencies are loaded.

Using your example:

```c#
public void TestRunner()
{
        // Get an interface to the engine
        ITestEngine engine = TestEngineActivator.CreateInstance();

        // Load assembly
        string dll = "C:\\Users\\dimitri.zhelkov\\source\\repos\\PoCInCore\\TestStuff\\bin\\Debug\\net5.0\\TestStuff.dll";
        Assembly assembly = Assembly.LoadFrom(dll);
        TestPackage package = new TestPackage(dll);

        // Get a runner for the test package
        ITestRunner runner = engine.GetRunner(package);

        // Run all the tests in the assembly
        XmlNode testResult = runner.Run(listener: null, TestFilter.Empty);
    }

```
