### ISSUE TITLE
Multiple tests are running with 'where' unique expression

### ISSUE THREAD

**Issue by stassilla** [nunit/nunit-console#1200] opened 2022-07-08 04:58 UTC
Good day,
I have the following test method with parameters:

`

namespace TestModule
{

    [TestClass]

    public class UnitTest : TestInitializer
    {
        [TestCase(1, TestName = "FirstParam"), GUID("1a313409-0c9a-4b87-8939-ae8cd8513eec")]
        [TestCase(2, TestName = "SecondParam"), GUID("2a313409-0c9a-4b87-8939-ae8cd8513eec")]

        public void TestMethodRun1(int num)
        {
            Thread.Sleep(1000);
            Console.WriteLine(num);
        }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
    public class GUIDAttribute : PropertyAttribute
    {
        public GUIDAttribute(string propertyValue)
        {
            if (!Guid.TryParse(propertyValue, out Guid guid))
            {
                throw new NotSupportedException($"The propertyValue '{propertyValue}' is not a proper Guid format!");
            }
            base.Properties.Add("GUID", propertyValue);
        }
    }
}
`

Console command:
nunit3-console.exe "C:\..\TestModule.dll" --where=GUID==1a313409-0c9a-4b87-8939-ae8cd8513eec

Console output:
![image](https://user-images.githubusercontent.com/8993895/177919167-7e86ae9e-4e5f-4ec3-9c85-0233fbd49940.png)

Am I missing additional expression or such feature is not supported?
Thank you.

Nunit: 3.13.3
Console: 3.15.2
Engine: 3.15.2
Engine.Api: 3.15.2
Installed via nuget

**Comment by mikkelbu** [comment] 2022-07-31 18:23
The problem is that the attributes does not work the way you think (note that this has nothing to do with NUnit, but this is how attributes work in C#).

So
```csharp
    [TestCase(1, TestName = "FirstParam"), GUID("1a313409-0c9a-4b87-8939-ae8cd8513eec")]
    [TestCase(2, TestName = "SecondParam"), GUID("2a313409-0c9a-4b87-8939-ae8cd8513eec")]
    public void TestMethodRun1(int num)
...
```
is equivalent to 
```csharp
    [TestCase(1, TestName = "FirstParam")`]
    [GUID("1a313409-0c9a-4b87-8939-ae8cd8513eec")]
    [TestCase(2, TestName = "SecondParam")]
    [GUID("2a313409-0c9a-4b87-8939-ae8cd8513eec")]
    public void TestMethodRun1(int num)
...
```
or 
```csharp
    [TestCase(1, TestName = "FirstParam")`]
    [TestCase(2, TestName = "SecondParam")]
    [GUID("1a313409-0c9a-4b87-8939-ae8cd8513eec"), GUID("2a313409-0c9a-4b87-8939-ae8cd8513eec")]
    public void TestMethodRun1(int num)
...
```
So the where statement will run both tests as both tests are decorated with the guid.

I think the only way to decorate one of the test cases with some sort of id is to use a `TestCaseSource` or similar. I'll close this issue as answered, but not that will still see additional comments on this issue.

**Closed by mikkelbu** 2022-07-31 18:23 UTC
