### ISSUE TITLE
Unhandled exception + uninformative message

### ISSUE THREAD

**Issue by mogikanin** [nunit/nunit-console#125] opened 2016-10-31 09:16 UTC
Exception occurs if specify path to non-existent solution file. See screen.
![nunit_runner_bug](https://cloud.githubusercontent.com/assets/840681/19849327/a86ab312-9f63-11e6-85ef-b8c850e376c4.png)

P.S. installed NUnit.ConsoleRunner.3.5.0 and NUnit.Extension.VSProjectLoader.3.5.0

**Comment by ChrisMaddock** [comment] 2016-10-31 09:33
No repro with a general non-exsitent solution file.

@mogikanin - I think this may be a duplicate of #29, and it might be your `--domain=Multiple` flag which is causing the exception. Can you see if removing that makes the difference?

**Comment by mogikanin** [comment] 2016-10-31 09:44
Yes, without `--domain=Multiple` there is a correct error message that file not found, and no exception in result.

**Comment by ChrisMaddock** [comment] 2016-10-31 09:46
Great, will close this as a duplicate. Thanks for confirming! 👍

**Closed by ChrisMaddock** 2016-10-31 09:46 UTC
Labels: confirm, is:bug
