### ISSUE TITLE
SocketException: An existing connection was forcibly closed by the remote host (3.10.0)

### ISSUE THREAD

**Issue by champlin2** [nunit/nunit-console#608] opened 2019-04-17 21:02 UTC
Using Jenkins when our build process completes the automation tests are kicked off on four different Jenkins slave machines to test our code in different environments.  For each build at least one of the four slaves immediately exits (without running any tests) with the following error:

Unhandled Exception: NUnit.Engine.NUnitEngineException: Remote test agent exited with non-zero exit code -1073741510
    at NUnit.Engine.Services.TestAgency.OnAgentExit(Object sender, EventArgs e)
    at System.Diagnostics.Process.OnExited()
    at System.Diagnostics.Process.RaiseOnExited()
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
 
Errors, Failures and Warnings
 
1) Error : 
System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
--SocketException
An existing connection was forcibly closed by the remote host
 
Server stack trace: 
    at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
    at System.Runtime.Remoting.Channels.SocketStream.Read(Byte[] buffer, Int32 offset, Int32 size)
    at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
    at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
    at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
    at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
    at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
    at System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()
    at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
    at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
 
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter)

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-04-17 20:39:26Z
     End time: 2019-04-17 20:39:32Z
    Duration: 6.369 seconds

We only have one assembly that contains the tests so our command line is just nunit3-console <dll name>.  If we re-run the job with the same DLL it works fine.

I'm assuming this is related to https://github.com/nunit/nunit-console/issues/266 (although the actual exit code is slightly different than some other reports I've seen of this problem).  And while I see there is an attempt to move to a different remoting procedure (https://github.com/nunit/nunit-console/pull/576) I was wondering if there was anything we can do in the meantime to avoid this error so we can reliably get the tests to run across all four environments for every build?

If there is any other information you want me to capture I can do that as this happens very regularly.

**Comment by ChrisMaddock** [comment] 2019-04-17 21:42
Can you run with —trace=Debug please, and share the agent logs?

**Comment by champlin2** [comment] 2019-04-17 23:31
[InternalTrace.8032.log](https://github.com/nunit/nunit-console/files/3091912/InternalTrace.8032.log)
[InternalTrace.5524.EvxAutomation.dll.log](https://github.com/nunit/nunit-console/files/3091914/InternalTrace.5524.EvxAutomation.dll.log)
[nunit-agent_5524.log](https://github.com/nunit/nunit-console/files/3091915/nunit-agent_5524.log)

**Comment by ChrisMaddock** [comment] 2019-04-19 18:30
-1073741510 is the error code returned when a windows process is forcibly terminated, e.g. by Ctrl+C in the console, or a user logging out.

It looks like something is force killing the `nunit-agent-x86.exe` process in this run. It seems to look like the problem here might be in your Jenkins set up rather than anything in NUnit - so I'm going to close this issue for now, but please post further if you find something to suggest otherwise, and we can reopen.

**Closed by ChrisMaddock** 2019-04-19 18:30 UTC

**Comment by saiparth** [comment] 2023-02-03 04:32
Hi @ChrisMaddock
This issue still reproducing occasionally. Previously we used .net 4.6.2 with NUnit 3.10. everything was fine. If there is less space in server then appears to be frequent. I am not sure
```
<message><![CDATA[System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host]]></message>
      <stack-trace><![CDATA[--SocketException
An existing connection was forcibly closed by the remote host
   at NUnit.Engine.Communication.Transports.Tcp.SocketReader.GetNextMessage() in C:\projects\nunit-console\src\NUnitEngine\nunit.engine.core\Communication\Transports\Tcp\SocketReader.cs:line 42
   at NUnit.Engine.Communication.Transports.Tcp.TestAgentTcpProxy.TestRunResult(ITestEventListener listener) in C:\projects\nunit-console\src\NUnitEngine\nunit.engine\Communication\Transports\Tcp\TestAgentTcpProxy.cs:line 116
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\projects\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 138
]]>
```
I am not finding any other logs. using nunit console 3.16.2 with .net 6
