### ISSUE TITLE
FileNotFoundException external API dll not found

### ISSUE THREAD

**Issue by AritzOlea** [nunit/nunit-console#621] opened 2019-05-06 13:05 UTC
I want to unit test a method from other project which uses a variable type defined in an external DLL (AutoCAD API's acdbmgd.dll).

When running the tests I get IO.FileNotFoundException and I don't know how to solve this.

[test.zip](https://github.com/nunit/nunit-console/files/3148011/test.zip)

**Comment by rprouse** [comment] 2019-05-07 00:17
@AritzOlea the problem is that the AutoCAD `acdbmgd.dll` is a managed wrapper around native DLLs. When you reference .NET assemblies that wrap native DLLs they don't get copied into the bin directory so they are not found when running tests. You need to copy in all of the native assemblies that the AutoCAD assembly depends on.

Does your main program even load and run? My understanding is that `acdbmgd.dll` is part of the ObjectARX sdk, so you should reach out to their support on how to use it. If you are trying to reference it because you have an AutoCAD product installed, my understanding is that you should not be doing that. Of course, my understanding is based solely on Google searches.

Good luck fixing this. I am going to close this as a question. If you have further questions, post here, we will see them.

**Closed by rprouse** 2019-05-07 00:17 UTC

**Comment by AritzOlea** [comment] 2019-05-07 08:44
You are right, the main program doesn't run, it generates a DLL library which is loaded by AutoCAD.

Maybe this isn't the way I should follow..

Is there a way to run unit tests at the same time the main project is being launched in Debug mode in Visual Studio launching the AutoCAD application? Maybe I can pass the loaded application's process identificator to the NUnit tester.

**Comment by cpetry** [comment] 2024-11-13 07:10
Did anyone find a solution for this?
I’m stuck at the very same problem

**Comment by cpetry** [comment] 2024-11-13 15:15
Well seems like the only solution for now is to wrap and split as much as possible away from AutoCAD api as possible.
No dependencies in test project, no problem
