### ISSUE TITLE
Error code -100 without any other usefull information in test run

### ISSUE THREAD

**Issue by ShinKaiRyuu** [nunit/nunit-console#808] opened 2020-08-04 18:59 UTC
Hi, we have met with some strange behaviour after extending our tests with extra multithreading. Before there was no problem with running test in parallel, but now strange -100 error code appear in the middle of test run - its falls entire run from being successfullly finished.  Test runs is going in TeamCity with NUnit console 3.11.1 
Process exited with code -100
NUnit process finished with negative exit code -100 (unexpected failure). Reporting step failure.
How can we found the reason for this unexpected failure.
![image](https://user-images.githubusercontent.com/2714369/89333470-ada98900-d69d-11ea-8e7b-6fa2b5a0e620.png)

**Comment by ChrisMaddock** [comment] 2020-08-04 19:13
Hi @ShinKaiRyuu,

Are you able to reproduce this outside of TeamCity? I expect you'll see more information on the cause of the crash if you're able to do that.

If not, I'd suggest adding the `--trace=Debug` option to your command line, and taking a look in the logs for any further information. Happy to take a look and advise, if you're able to share them.

**Comment by ChrisMaddock** [comment] 2020-08-15 12:09
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂

**Closed by ChrisMaddock** 2020-08-15 12:09 UTC
Labels: is:question
