### ISSUE TITLE
NUnit 3 console runs test for nunit.framework.dll v2 in parallel mode

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#33] opened 2016-08-17 16:47 UTC
Is it expected behavior? If it is true the TC extensions works incorrectly for this case.
As I know nunit.framework.dll v2 have no attributes for parallel mode. And this issue is critical for the TC extension. Related issue is https://github.com/nunit/teamcity-event-listener/issues/14

**Comment by rprouse** [comment] 2016-08-17 17:00
I believe that NUnit 3 will run multiple NUnit 2 test assemblies in parallel, but the tests within the v2 tests will not be run in parallel. Is the trouble with multiple assemblies?

**Comment by NikolayPianikov** [comment] 2016-08-17 17:02
Yes, the the trouble with multiple assemblies.

**Comment by rprouse** [comment] 2016-08-17 17:06
Why is this a problem for the TC extension? v3 tests run the same way. I assume you handle that?

**Comment by NikolayPianikov** [comment] 2016-08-17 17:13
Extensions receives 2 message one after another:

1:

`<start-suite id="1-1005" name="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Common.Test.dll" fullname="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Common.Test.dll" />`

2:

`<start-suite id="1-1431" name="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Web.Test.dll" fullname="C:\Projects\GitHub\nunit-teamcity-event-listener\bin\Debug\1167775801\mocks\MAP.Web.Test.dll" />`

After that 

3:
`<start-suite id="1-1006" name="MAP" fullname="MAP" />`

Question: What assembly corresponds `<start-suite id="1-1006" name="MAP" fullname="MAP" />` ?
We have a bunch unstructured messages from different assemblies

**Comment by NikolayPianikov** [comment] 2016-08-17 17:17
Some kind of XML but from several different files at the same time :)

**Comment by CharliePoole** [comment] 2016-08-17 18:19
The issue is that the v2 driver is using the same prefix for both assemblies. Both drivers should get their prefixes from a common source.

**Comment by ChrisMaddock** [comment] 2020-01-04 18:50
Fixed in #564 I believe.

**Closed by ChrisMaddock** 2020-01-04 18:50 UTC
Labels: is:bug, pri:low
