### ISSUE TITLE
nunit3-console returns different exit codes when nunit.framework.dll was not found

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-console#142] opened 2016-12-05 10:50 UTC
For "Multiple" and "Separate" modes it returns -100
[Case1.zip](https://github.com/nunit/nunit-console/files/630814/Case1.zip)
For "InProcess" mode it returns -2
[Case2.zip](https://github.com/nunit/nunit-console/files/630815/Case2.zip)

**Comment by mikkelbu** [comment] 2019-01-18 21:08
I remember when I took this issue I could reproduce the problem, but now both variants return -100. For Case1 - `--process=Multiple` - it looks like a failure in a test, whereas in Case2 - `--process=InProcess` - it looks like the failure is before running the tests. This is probably due to the difference in the "process-mode".

@NikolayPianikov should we close this issue, since they return the same exit code now? I think that it will be difficult to make the two variants behave exactly the same.

**Case1**
```
PS C:\Temp\ConsoleReturnCodes\Case1\Case1> .\run.cmd

C:\Temp\ConsoleReturnCodes\Case1\Case1>"C:\src\NUnit\nunit-console\bin\Release\net20\nunit3-console.exe" mocks\foo.tests.dll --process=Multiple
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2018 Charlie Poole, Rob Prouse
18 January 2019 21:50:58

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    mocks\foo.tests.dll


Errors, Failures and Warnings

1) Error : C:\Temp\ConsoleReturnCodes\Case1\Case1\mocks\foo.tests.dll
NUnit.Engine.NUnitEngineException : An exception occurred in the driver while loading tests.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework, Version=3.6.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
--NUnitEngineException
An exception occurred in the driver while loading tests.

Server stack trace:
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 145
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage() in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 131
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded() in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 250
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 189
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 162
--
FileNotFoundException
Could not load file or assembly 'nunit.framework, Version=3.6.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Drivers\NUnit3FrameworkDriver.cs:line 171
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Drivers\NUnit3FrameworkDriver.cs:line 84
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 141

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-01-18 20:50:58Z
    End time: 2019-01-18 20:50:59Z
    Duration: 0.377 seconds

Results (nunit3) saved as TestResult.xml

C:\Temp\ConsoleReturnCodes\Case1\Case1>echo exit code: -100
exit code: -100
```
**Case2**
```
PS C:\Temp\ConsoleReturnCodes\Case2\Case2> .\run.cmd

C:\Temp\ConsoleReturnCodes\Case2\Case2>"C:\src\NUnit\nunit-console\bin\Release\net20\nunit3-console.exe" mocks\foo.tests.dll --process=InProcess
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2018 Charlie Poole, Rob Prouse
18 January 2019 21:52:20

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    mocks\foo.tests.dll

NUnit.Engine.NUnitEngineException : An exception occurred in the driver while loading tests.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'nunit.framework, Version=3.6.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.

--NUnitEngineException
An exception occurred in the driver while loading tests.
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 145
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage() in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 131
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded() in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 250
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 189
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\MasterTestRunner.cs:line 385
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\MasterTestRunner.cs:line 157
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter) in C:\src\NUnit\nunit-console\src\NUnitConsole\nunit3-console\ConsoleRunner.cs:line 216
--
FileNotFoundException
Could not load file or assembly 'nunit.framework, Version=3.6.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Drivers\NUnit3FrameworkDriver.cs:line 171
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Drivers\NUnit3FrameworkDriver.cs:line 84
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage) in C:\src\NUnit\nunit-console\src\NUnitEngine\nunit.engine\Runners\DirectTestRunner.cs:line 141


C:\Temp\ConsoleReturnCodes\Case2\Case2>echo exit code: -100
exit code: -100
```

**Comment by NikolayPianikov** [comment] 2019-01-21 11:51
@mikkelbu ok, let's close it, besides, I do not receive any negative feedback from other people regarding this problem. @rprouse, @CharliePoole any objections?

**Closed** 2019-02-23 19:04 UTC
Labels: is:bug, pri:low
